{
  "hash": "ea5f1b604d161660bdb9470d92ae41c3",
  "result": {
    "markdown": "---\ntitle: \"Lesson 2: Introduction to Categorical Data Analysis\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#C2352F\"\ndate: \"04/03/2024\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"Lesson 2: Introduction to Categorical Data Analysis\"\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n---\n\n::: {.cell}\n\n:::\n\n\n# Learning Objectives\n\n1.  Recognize the motivation for and focus of our course (categorical responses)\n\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n\n3.  Determine if a single proportion differs from a population value\n\n4.  Determine if two proportions differ from each other\n\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n\n# Learning Objectives\n\n::: lob\n1.  Recognize the motivation for and focus of our course (categorical responses)\n:::\n\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n\n3.  Determine if a single proportion differs from a population value\n\n4.  Determine if two proportions differ from each other\n\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n\n## What is Categorical Data Analysis?\n\n-   In BSTA 512/612 (linear regression), we focused on [continuous responses/outcomes]{style=\"color:#34AC8B; font-weight: bold;\"}\n\n    -   We included [categorical variables only as covariates]{style=\"color:#34AC8B; font-weight: bold;\"} (aka predictors, independent variables, explanatory variables)\n\n    -   Examples from 512/612: life expectancy (in years), IAT score (ranging from -2 to 2)\n\n   \n\n-   Categorical data analysis focuses on the statistical methods for [categorical responses/outcomes]{style=\"color:#213c96; font-weight: bold;\"}\n\n    -   Explanatory (or ‘independent’) variable can be of any type (continuous or categorical)\n\n## Types of Variables\n\n![](./images/types_data.png){fig-align=\"center\"}\n\n## Types of Variables: Outcomes we will cover in this course\n\n![](./images/types_data_2.png){fig-align=\"center\"}\n\n## What does this course cover?\n\n-   Strategies for assessing association between categorical response variable and a [one explanatory variable]{style=\"color:#34AC8B; font-weight: bold;\"}\n\n    -   Hypothesis testing\n    -   Measure of association\n    -   Simple logistic regression\n\n   \n\n-   Statistical modeling strategies for assessing association between the categorical response variable and a [set of explanatory variables]{style=\"color:#213c96; font-weight: bold;\"}\n\n    -   Logistic regression\n\n        -   For binary, ordinal, and multinomial outcomes\n\n    -   Poisson regression\n\n        -   For counts outcomes\n\n## Poll everywhere question 1\n\n# Learning Objectives\n\n1.  Recognize the motivation for and focus of our course (categorical responses)\n\n::: lob\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n:::\n\n3.  Determine if a single proportion differs from a population value\n\n4.  Determine if two proportions differ from each other\n\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n\n## Binomial Distribution\n\n-   Consider a sample of $n$ independent trials, each of which can have only two possible outcomes (\"success\" and \"failure\")\n\n-   For each trial: $$\\begin{align} P( \\text{success}) & = p \\\\\n                      P( \\text{failure}) & = 1- p = q \\end{align}$$\n\n-   **Binomial distribution:** distribution of the number of successes in n independent trials\n\n-   The probability mass function for the binomial distribution is: $$P(X=k) = {n \\choose k} p^k q^{n-k}, \\text{ for } k = 0, 1, ..., n$$\n\n    -   $E(X) = np$\n    -   $Var(X) = npq = np(1-p)$\n\n## Binomial Distribution\n\n-   Consider a sample of $n$ independent trials, each of which can have only two possible outcomes (\"success\" and \"failure\")\n\n-   For each trial: $$\\begin{align} P( \\text{success}) & = p \\\\\n                      P( \\text{failure}) & = 1- p = q \\end{align}$$\n\n-   **Binomial distribution:** distribution of the number of successes in n independent trials\n\n-   The probability mass function for the binomial distribution is: $$P(X=k) = {n \\choose k} p^k q^{n-k}, \\text{ for } k = 0, 1, ..., n$$\n\n    -   $E(X) = np$\n    -   $Var(X) = npq = np(1-p)$\n\n![](./images/binomial_q.png){.absolute top=\"70%\" right=\"5%\" width=\"800\"}\n\n## Binomial Distribution: R commands\n\nR commands with their [input]{style=\"color:#34AC8B\"} and [output]{style=\"color:#213c96\"}:\n\n| R code     | What does it return?                                                                                                         |\n|--------------------|----------------------------------------------------|\n| `rbinom()` | returns [sample of random variables]{style=\"color:#213c96\"} with [specified binomial distribution]{style=\"color:#34AC8B\"}    |\n| `dbinom()` | returns [probability]{style=\"color:#213c96\"} of getting [certain number of successes]{style=\"color:#34AC8B\"}                 |\n| `pbinom()` | returns [cumulative probability]{style=\"color:#213c96\"} of getting [certain number or less]{style=\"color:#34AC8B\"} successes |\n| `qbinom()` | returns [number of successes]{style=\"color:#213c96\"} corresponding to [desired quantile]{style=\"color:#34AC8B\"}              |\n\n## Binomial Distribution Example\n\n::: example\n::: ex-title\nExample\n:::\n\n::: ex-cont\nIf the probability that one white blood cell is a lymphocyte is 0.2, compute the probability of 2 lymphocytes out of 10 white blood cells\n:::\n:::\n\n$$P(X=2) = {10 \\choose 2} 0.2^2 (1-0.2)^{10-2}  = 0.3020$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(2, 10, 0.2) %>% round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.302\n```\n:::\n:::\n\n\n## Normal Approximation of the Binomial Distribution\n\n-   Also known as: **Sampling distribution of** $\\widehat{p}$\n\n-   IF $X\\sim \\text{Binomial}(n,p)$ and $np>10$ and $nq = n(1-p) > 10$\n\n    -   Ensures sample size ($n$) is moderately large and the $p$ is not too close to 0 or 1\n    -   Other resources use other criteria (like $npq>5$ or $np>5$)\n    -   When looking at a sample, we use $\\widehat{p}$ instead of $p$ to check this!!\n\n \n\n-   THEN approximately $𝑋\\sim \\text{Normal}\\big(\\mu_X = np, \\sigma_X = \\sqrt{np(1-p)} \\big)$\n\n    -   Or we often write this as the sampling distribution of $\\widehat{p}$: $$\\widehat{p} \\sim \\text{Normal}\\bigg(\\mu_{\\widehat{p}} = p, \\sigma_{\\widehat{p}} = \\sqrt{\\dfrac{p(1-p)}{n}}\\bigg)$$\n\n-   [Pretty good video behind the intuition of this](https://www.youtube.com/watch?v=CCqWkJ_pqNU&ab_channel=jbstatistics) (Watch 00:00 - 05:40)\n\n# Learning Objectives\n\n1.  Recognize the motivation for and focus of our course (categorical responses)\n\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n\n::: lob\n3.  Determine if a single proportion differs from a population value\n:::\n\n4.  Determine if two proportions differ from each other\n\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n\n## Estimate and Confidence Interval of Single Proportion\n\n-   Estimate of proportion:\n\n$$\n\\widehat{p} = \\dfrac{\\# \\text{successes}}{\\# \\text{successes} + \\# \\text{failures}}\n$$\n\n-   Use the sampling distribution of $\\widehat{p}$ to construct the confidence interval:\n\n    -   $(1-\\alpha)\\%$ confidence interval for estimate proportion:\n\n$$\\begin{align} \\widehat{p} &\\pm z^*_{(1-\\alpha/2)} \\cdot SE_{\\hat{p}} \\\\ \\widehat{p} &\\pm z^*_{(1-\\alpha/2)} \\cdot \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}} \\end{align}$$\n\n-   Using $SE_{\\hat{p}} = \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$ - instead of $\\sigma_{p} = \\sqrt{\\frac{p(1-p)}{n}}$ - because we don't know exactly what $p$ is\n\n## \n\n::: example\n::: ex-title\nSmoking status example\n:::\n\n::: ex-cont\nA cross-sectional study of 8681 patients was conducted to evaluate the nature of smoking status among people. Of the 8681 people, 4840 were nonsmokers and 3841 were smokers.\n:::\n:::\n\n**Needed steps:**\n\n1.  Estimate proportion $\\widehat{p}$\n2.  Check that $n\\widehat{p}>10$ and $n(1-\\widehat{p})>10$ in order to make normal approximation\n3.  Construct 95% confidence interval\n4.  Write interpretation\n\n##  {.smaller}\n\n::: example\n::: ex-title\nSmoking status example\n:::\n\n::: ex-cont\nA cross-sectional study of 8681 patients was conducted to evaluate the nature of smoking status among people. Of the 8681 people, 4840 were nonsmokers and 3841 were smokers.\n:::\n:::\n\n::: columns\n::: column\n1.  Estimate proportion $\\widehat{p}$ $$ \\widehat{p} = \\dfrac{3841}{3841 + 4840} = \\dfrac{3841}{8681} = 0.44246$$\n2.  Check that $n\\widehat{p}>10$ and $n(1-\\widehat{p})>10$ in order to make normal approximation $$ n\\widehat{p} = 8681\\cdot0.4425 = 3841 > 10$$ $$ n(1-\\widehat{p}) = 8681\\cdot(1-0.4425) = 4840 > 10$$\n:::\n\n::: column\n3.  Construct 95% confidence interval\n\n$$ \\widehat{p} \\pm z^*_{0.975} \\cdot \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 3841, n = 8681, correct = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  3841 out of 8681, null probability 0.5\nX-squared = 114.73, df = 1, p-value < 2.2e-16\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.4319827 0.4529896\nsample estimates:\n        p \n0.4424605 \n```\n:::\n:::\n\n\n4.  Write interpretation of **estimate**\n\nThe estimated proportion of smokers is 0.442 (95% CI: 0.432, 0.453).\n\nAdditional interpretation of CI: We are 95% confident that the (population) proportion of smokers is between 0.432 and 0.453.\n:::\n:::\n\n## Poll everywhere question 2\n\n# Learning Objectives\n\n1.  Recognize the motivation for and focus of our course (categorical responses)\n\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n\n3.  Determine if a single proportion differs from a population value\n\n::: lob\n4.  Determine if two proportions differ from each other\n:::\n\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n\n## Estimate and Confidence Interval for Difference in Proportions\n\n-   Use the sampling distribution of $\\widehat{p}_1$ and $\\widehat{p}_2$ to construct the confidence interval:\n\n    -   $(1-\\alpha)\\%$ confidence interval for estimate difference in proportions:\n\n$$\\begin{align} \\widehat{p}_1 - \\widehat{p}_2 &\\pm z^*_{(1-\\alpha/2)} \\cdot SE_{\\hat{p}_1 - \\hat{p}_2} \\\\ \\widehat{p}_1 - \\widehat{p}_2 &\\pm z^*_{(1-\\alpha/2)} \\cdot \\sqrt{\n\\frac{\\hat{p}_1\\cdot(1-\\hat{p}_1)}{n_1} + \\frac{\\hat{p}_2\\cdot(1-\\hat{p}_2)}{n_2}} \\end{align}$$\n\n-   Using $SE_{\\hat{p}_1 - \\hat{p}_2} = \\sqrt{\\frac{\\hat{p}_1\\cdot(1-\\hat{p}_1)}{n_1} + \\frac{\\hat{p}_2\\cdot(1-\\hat{p}_2)}{n_2}}$ because we don't know exactly what $p_1$ and $p_2$ are\n\n## Poll Everywhere Question 3\n\n## Example: Strong Heart Study (1/2)\n\n::: columns\n::: {.column width=\"65%\"}\nThe [Strong Heart Study](https://strongheartstudy.org/) is an ongoing study of American Indians residing in 13 tribal communities in three geographic areas (AZ, OK, and SD/ND) to study prevalence and incidence of cardiovascular disease and to identify risk factors. We will be examining the 4-year cumulative incidence of diabetes with one risk factor, glucose tolerance.\n\n \n\n-   **Impaired glucose:** normal or impaired glucose tolerance at baseline visit (between 1988 and 1991)\n\n     \n\n-   **Diabetes:** Indicator of diabetes at follow-up visit (roughly four years after baseline) according to two-hour oral glucose tolerance test\n:::\n\n::: {.column width=\"35%\"}\n![](./images/home_box3.png){width=\"500\"}\n:::\n:::\n\n## Example: Strong Heart Study (2/2)\n\nThere is a total of 1664 American Indians in the dataset, with the following distribution of folks with diabetes and glucose tolerance:\n\n \n\n::: columns\n::: {.column width=\"60%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n#shs_data = read.csv(file = here(\"./data/SHS_data.csv\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nSHS = tibble(Diabetes = c(rep(\"Not diabetic\", \n                   1338), \n                   rep(\"Diabetic\", 326)),\n              Glucose = c(rep(\"Normal\", \n                  1004),#Not diabetic\n          rep(\"Impaired\", 334),\n          rep(\"Normal\", \n              128), #Diabetic\n          rep(\"Impaired\", 198)))\n```\n:::\n\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Displaying the contingency table in R\"}\nSHS %>% tabyl(Glucose, Diabetes) %>% \n  adorn_totals(where = c(\"row\", \"col\")) %>% \n  gt() %>% \n  tab_stubhead(label = \"Glucose Impairment\") %>%\n  tab_spanner(label = \"Diabetes\", \n              columns = c(\"Not diabetic\", \"Diabetic\")) %>%\n  tab_options(table.font.size = 45)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"sgfdsvxfhq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#sgfdsvxfhq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sgfdsvxfhq thead, #sgfdsvxfhq tbody, #sgfdsvxfhq tfoot, #sgfdsvxfhq tr, #sgfdsvxfhq td, #sgfdsvxfhq th {\n  border-style: none;\n}\n\n#sgfdsvxfhq p {\n  margin: 0;\n  padding: 0;\n}\n\n#sgfdsvxfhq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 45px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sgfdsvxfhq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sgfdsvxfhq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sgfdsvxfhq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sgfdsvxfhq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sgfdsvxfhq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sgfdsvxfhq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sgfdsvxfhq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sgfdsvxfhq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sgfdsvxfhq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sgfdsvxfhq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sgfdsvxfhq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sgfdsvxfhq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sgfdsvxfhq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sgfdsvxfhq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgfdsvxfhq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sgfdsvxfhq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sgfdsvxfhq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sgfdsvxfhq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgfdsvxfhq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sgfdsvxfhq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgfdsvxfhq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sgfdsvxfhq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgfdsvxfhq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sgfdsvxfhq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgfdsvxfhq .gt_left {\n  text-align: left;\n}\n\n#sgfdsvxfhq .gt_center {\n  text-align: center;\n}\n\n#sgfdsvxfhq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sgfdsvxfhq .gt_font_normal {\n  font-weight: normal;\n}\n\n#sgfdsvxfhq .gt_font_bold {\n  font-weight: bold;\n}\n\n#sgfdsvxfhq .gt_font_italic {\n  font-style: italic;\n}\n\n#sgfdsvxfhq .gt_super {\n  font-size: 65%;\n}\n\n#sgfdsvxfhq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sgfdsvxfhq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sgfdsvxfhq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sgfdsvxfhq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sgfdsvxfhq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sgfdsvxfhq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sgfdsvxfhq .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Glucose\">Glucose</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Diabetes\">\n        <span class=\"gt_column_spanner\">Diabetes</span>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Total\">Total</th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Not diabetic\">Not diabetic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Diabetic\">Diabetic</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Glucose\" class=\"gt_row gt_left\">Impaired</td>\n<td headers=\"Not diabetic\" class=\"gt_row gt_right\">334</td>\n<td headers=\"Diabetic\" class=\"gt_row gt_right\">198</td>\n<td headers=\"Total\" class=\"gt_row gt_right\">532</td></tr>\n    <tr><td headers=\"Glucose\" class=\"gt_row gt_left\">Normal</td>\n<td headers=\"Not diabetic\" class=\"gt_row gt_right\">1004</td>\n<td headers=\"Diabetic\" class=\"gt_row gt_right\">128</td>\n<td headers=\"Total\" class=\"gt_row gt_right\">1132</td></tr>\n    <tr><td headers=\"Glucose\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"Not diabetic\" class=\"gt_row gt_right\">1338</td>\n<td headers=\"Diabetic\" class=\"gt_row gt_right\">326</td>\n<td headers=\"Total\" class=\"gt_row gt_right\">1664</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n:::\n:::\n\n## \n\n::: example\n::: ex-title\nStrong Heart Study\n:::\n\n::: ex-cont\nWhat is the difference in proportions for American Indians that have diabetes comparing individuals with normal vs. impaired glucose?\n:::\n:::\n\n**Needed steps:**\n\n1.  Estimate the difference in proportions\n2.  Check that each cell has at least 10 individuals\n3.  Construct 95% confidence interval\n4.  Write interpretation of estimate\n\n##  {.smaller}\n\n::: example\n::: ex-title\nStrong Heart Study\n:::\n\n::: ex-cont\nWhat is the difference in proportions for American Indians that have diabetes comparing individuals with normal vs. impaired glucose?\n:::\n:::\n\n::: columns\n::: column\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"ncszcysolg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ncszcysolg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ncszcysolg thead, #ncszcysolg tbody, #ncszcysolg tfoot, #ncszcysolg tr, #ncszcysolg td, #ncszcysolg th {\n  border-style: none;\n}\n\n#ncszcysolg p {\n  margin: 0;\n  padding: 0;\n}\n\n#ncszcysolg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 28px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ncszcysolg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ncszcysolg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ncszcysolg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ncszcysolg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ncszcysolg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ncszcysolg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ncszcysolg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ncszcysolg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ncszcysolg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ncszcysolg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ncszcysolg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ncszcysolg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ncszcysolg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ncszcysolg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ncszcysolg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ncszcysolg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ncszcysolg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ncszcysolg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ncszcysolg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ncszcysolg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ncszcysolg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ncszcysolg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ncszcysolg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ncszcysolg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ncszcysolg .gt_left {\n  text-align: left;\n}\n\n#ncszcysolg .gt_center {\n  text-align: center;\n}\n\n#ncszcysolg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ncszcysolg .gt_font_normal {\n  font-weight: normal;\n}\n\n#ncszcysolg .gt_font_bold {\n  font-weight: bold;\n}\n\n#ncszcysolg .gt_font_italic {\n  font-style: italic;\n}\n\n#ncszcysolg .gt_super {\n  font-size: 65%;\n}\n\n#ncszcysolg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ncszcysolg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ncszcysolg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ncszcysolg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ncszcysolg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ncszcysolg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ncszcysolg .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Glucose\">Glucose</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Diabetes\">\n        <span class=\"gt_column_spanner\">Diabetes</span>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Total\">Total</th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Not diabetic\">Not diabetic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Diabetic\">Diabetic</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Glucose\" class=\"gt_row gt_left\">Impaired</td>\n<td headers=\"Not diabetic\" class=\"gt_row gt_right\">334</td>\n<td headers=\"Diabetic\" class=\"gt_row gt_right\">198</td>\n<td headers=\"Total\" class=\"gt_row gt_right\">532</td></tr>\n    <tr><td headers=\"Glucose\" class=\"gt_row gt_left\">Normal</td>\n<td headers=\"Not diabetic\" class=\"gt_row gt_right\">1004</td>\n<td headers=\"Diabetic\" class=\"gt_row gt_right\">128</td>\n<td headers=\"Total\" class=\"gt_row gt_right\">1132</td></tr>\n    <tr><td headers=\"Glucose\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"Not diabetic\" class=\"gt_row gt_right\">1338</td>\n<td headers=\"Diabetic\" class=\"gt_row gt_right\">326</td>\n<td headers=\"Total\" class=\"gt_row gt_right\">1664</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n1.  Estimate the difference in proportions $$ \\widehat{p}_1 -\\widehat{p}_2 = \\dfrac{198}{532} - \\dfrac{128}{1132} = 0.2591$$\n\n2.  Check that each cell has at least 10 individuals\n:::\n\n::: column\n3.  Construct 95% confidence interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = table(SHS$Glucose, SHS$Diabetes), \n          correct = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  table(SHS$Glucose, SHS$Diabetes)\nX-squared = 152.6, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.2126963 0.3055162\nsample estimates:\n   prop 1    prop 2 \n0.3721805 0.1130742 \n```\n:::\n:::\n\n\n4.  Write interpretation of **estimate**\n\nThe estimated difference in proportion of diabetic American Indians comparing is 0.259 (95% CI: 0.213, 0.306).\n\nAdditional interpretation of CI: We are 95% confident that the difference in (population) proportions of American Indians who have normal glucose tolerance and impaired glucose tolerance that developed diabetes is between 0.213 and 0.306.\n:::\n:::\n\n## McNemar's Test\n\n-   McNemar’s test should be used if data is from a matched pairs study\n\n \n\n-   What is a matched-pairs study?\n\n    -   Participants are paired based on key characteristics\n    -   Each participant within a pair will be assigned to different treatment groups\n\n-   Categorical test that is parallel to the \"paired t-test\"\n\n \n\n-   R packages and functions\n\n    -   Normal approximation: `mcnemar.test()` in built-in `stats` package\n    -   Exact test: `mcnemar.exact()` in `exact2x2` package\n\n \n\n-   **If you would like more information of McNemar’s test, please see Rosner TB: 10.4 and 10.5: Paired Samples**\n\n## Summary so far\n\n-   Introduced categorical data as the response in analysis\n-   Reviewed an important distribution (Binomial distribution) for categorical data analysis\n-   Estimated a single proportion from a sample with its confidence interval\n-   Estimated a difference in proportions from a sample with its confidence interval\n\n   \n\n-   Can we expand this to ask a more general question about association between a response and explanatory variable?\n\n    -   What if there is more than 2 categories for either variable?\n\n# Learning Objectives\n\n1.  Recognize the motivation for and focus of our course (categorical responses)\n\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n\n3.  Determine if a single proportion differs from a population value\n\n4.  Determine if two proportions differ from each other\n\n::: lob\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n:::\n\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n\n## Contingency Tables (R x C)\n\n-   R X C contingency tables\n\n    -   Contains information for two discrete variables: one has R categories and the other has C categories.\n\n    -   Refers to the number of rows (R) and number of columns (C) in the table\n\n \n\n-   For two proportions: focused on 2 X 2 contingency tables\n\n    -   R = 2, C = 2\n\n \n\n-   Expand our contingency tables to variables with 2 or more categories\n\n    -   Categories can be ordinal or nominal\n\n## Contingency Table: Example\n\nLet's say we are interested in learning the association between the development of breast cancer and age at first birth. Our first step is typically to present the observed data:\n\n![](./images/Conting_tab_ex.png){fig-align=\"center\" width=\"511\"}\n\n-   This is a 2 x 5 contingency table\n\n## Test Association/Trend of R X C Contingency Table\n\n \n\n::: columns\n::: {.column width=\"46%\"}\n\nIf [both variables are nominal]{style=\"color:#213c96; font-weight: bold;\"}, a [test of general association]{style=\"color:#213c96; font-style: italic;\"} will be sufficient\n\n-   Test of general association is the same regardless of R and C\n-   Test used for 2x2 contingency table same as 5x3 contingency table\n-   We will cover:\n\n    -   Chi-squared test\n    -   Fisher Exact test\n\n:::\n::: {.column width=\"6%\"}\n:::\n::: {.column width=\"48%\"}\n\nIf [one or both variables are ordinal]{style=\"color:#34AC8B; font-weight: bold;\"}, a [test of trend]{style=\"color:#34AC8B; font-style: italic;\"} may be of interest\n\n-   Treats ordinal variables as quantitative rather than qualitative (nominal scale)\n-   Test of trend has greater power than the test of general association\n-   We will cover:\n\n    -   Cochran-Armitage test\n    -   Mantel-Haenszel test\n\n:::\n:::\n\n## Poll Everywhere Question 4\n\n## Test of General Association\n\n-   **General research question:** Are two variables (both categorical, nominal) associated with each other?\n\n \n\n-   Translated to a hypothesis test:\n\n    -   $H_0$ : There is no association between the two variables / The variables are independent\n    -   $H_1$ : There is an association between the two variables / The variables are not independent\n\n   \n\n-   We have two options for testing general association:\n\n    1.  Chi-squared test\n    2.  Fisher’s Exact test\n\n## Test of General Association: SHS Example\n\n-   **Main question:** Do American Indians with impaired glucose tolerance have a different incidence of diabetes?\n\n    -   Is glucose tolerance associated with diabetes incidence among American Indians?\n\n-   We have two variables, and both variables have two nominal categories\n\n    -   Diabetes outcome: Not diabetic and Diabetic\n    -   Glucose tolerance: Normal or Impaired\n  \n \n\n-   Answer research question with a test of general association\n\n-   Hypothesis:\n\n    -   $H_0$ : There is no association between glucose tolerance and diabetes / Glucose tolerance and diabetes are independent\n    -   $H_1$ : There is an association between glucose tolerance and diabetes / Glucose tolerance and diabetes are not independent\n\n# Learning Objectives\n\n1.  Recognize the motivation for and focus of our course (categorical responses)\n\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n\n3.  Determine if a single proportion differs from a population value\n\n4.  Determine if two proportions differ from each other\n\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n\n::: lob\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n:::\n\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n\n## Chi-squared test\n\n-   Test to see how likely is it that we observe our data given the null hypothesis (no association)\n\n \n\n-   We use the null to calculate the expected cell counts and compare them to the observed cell counts\n\n \n\n-   Requirements to conduct Chi-squared test (expected cell counts)\n\n    -   For 2 x 2 contingency table:\n\n        -   No expected cell counts should be less than 10\n\n    -   For contingency table with 3x2, 3x3, 4x4, etc.:\n\n        -   No more than 20% of expected cell counts are less than 5\n        -   No expected cell counts are less than 1\n\n## Chi-squared test: Process\n\n1.  Check that the [**expected cell counts**]{style=\"color:#34AC8B\"} threshold is met\n\n2.  Set the [**level of significance**]{style=\"color:#34AC8B\"} $\\alpha$\n\n3.  Specify the [**null**]{style=\"color:#34AC8B\"} ( $H_0$ ) and [**alternative**]{style=\"color:#34AC8B\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#34AC8B\"}\n\n    -   In symbols\n    -   In words\n    -   Alternative: one- or two-sided?\n\n4.  Calculate the [**test statistic**]{style=\"color:#34AC8B\"} and [**p-value**]{style=\"color:#34AC8B\"} for Chi-squared test in R\n\n    -   We will not discuss the test statistic's equation\n\n5.  Write a [**conclusion**]{style=\"color:#34AC8B\"} to the hypothesis test\n\n    -   Do we reject or fail to reject $H_0$?\n    -   Write a conclusion in the context of the problem\n\n## Chi-squared test: Expected Cell Counts\n\n-   Is the sample size big enough for the chi-square test to be adequate? What are the expected cell counts?\n\n \n\n-   If you want an explanation of how to calculate by hand, please see Vu and Harringtion TB (section 8.3.1, page 405)\n\n \n\n-   Too time consuming for this class, but R does it quickly using the `expected()` function in the `epitools` package\n\n## Chi-squared test: Expected Cell Counts\n\n-   In the Strong Heart Study...\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSHS_table = table(SHS$Glucose, SHS$Diabetes)\nSHS_table\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          \n           Diabetic Not diabetic\n  Impaired      198          334\n  Normal        128         1004\n```\n:::\n\n```{.r .cell-code}\nlibrary(epitools)\nexpected(SHS_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          \n           Diabetic Not diabetic\n  Impaired  104.226      427.774\n  Normal    221.774      910.226\n```\n:::\n:::\n\n\n \n\n::: columns\n::: {.column width=\"15%\"}\n:::\n\n::: {.column width=\"28%\"}\n::: hl3\nAll expected counts \\> 5\n:::\n:::\n\n::: {.column width=\"38%\"}\n:::\n:::\n\n## Chi-squared test: SHS Example\n\n::: columns\n::: column\n1.  Check expected cell counts threshold\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpected(SHS_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          \n           Diabetic Not diabetic\n  Impaired  104.226      427.774\n  Normal    221.774      910.226\n```\n:::\n:::\n\n\nAll expected cells are greater than 5.\n\n2.  $\\alpha = 0.05$\n\n3.  Hypothesis test:\n\n    -   $H_0$ : There is no association between glucose tolerance and diabetes\n    -   $H_1$ : There is an association between glucose tolerance and diabetes\n:::\n\n::: column\n4.  Calculate the test statistic and p-value for Chi-squared test in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(x = SHS_table, correct = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  SHS_table\nX-squared = 152.6, df = 1, p-value < 2.2e-16\n```\n:::\n:::\n\n\n5.  Conclusion to the hypothesis test\n\nWe reject the null hypothesis that glucose tolerance and diabetes are not associated ($p<2.2\\cdot10^{-16}$). There is sufficient evidence that glucose tolerance and diabetes incidence are associated among American Indians.\n:::\n:::\n\n# Learning Objectives\n\n1.  Recognize the motivation for and focus of our course (categorical responses)\n\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n\n3.  Determine if a single proportion differs from a population value\n\n4.  Determine if two proportions differ from each other\n\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n\n::: lob\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n:::\n\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n\n## Fisher's Exact Test\n\n-   Only necessary when expected counts in one or more cells is less than 5\n-   Given row and column totals fixed, computes exact probability that we observe our data or more extreme data\n-   Consider a general 2 x 2 table:\n\n![](./images/fisher_tab.png){fig-align=\"center\"}\n\n-   The exact probability of observing a table with cells (a, b, c, d) can be computed based on the hypergeometric distribution\n\n$$P(a, b, c, d) = \\dfrac{(a+b)!\\cdot(c+d)!\\cdot(a+c)!\\cdot(b+d)!}{n!\\cdot a!\\cdot b!\\cdot c!\\cdot d!}$$\n\n-   Numerator is fixed and denominator changes\n\n## Fisher's Exact test: Process\n\n1.  Check the [**expected cell counts**]{style=\"color:#34AC8B\"}\n\n2.  Set the [**level of significance**]{style=\"color:#34AC8B\"} $\\alpha$\n\n3.  Specify the [**null**]{style=\"color:#34AC8B\"} ( $H_0$ ) and [**alternative**]{style=\"color:#34AC8B\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#34AC8B\"}\n\n    -   In symbols\n    -   In words\n    -   Alternative: one- or two-sided?\n\n4.  Calculate the [**test statistic**]{style=\"color:#34AC8B\"} and [**p-value**]{style=\"color:#34AC8B\"} for Fisher Exact test in R\n\n    -   We will not discuss the test statistic's equation\n\n5.  Write a [**conclusion**]{style=\"color:#34AC8B\"} to the hypothesis test\n\n    -   Do we reject or fail to reject $H_0$?\n    -   Write a conclusion in the context of the problem\n\n## Fisher's Exact test: SHS Example (not appropriate use of Fisher's Exact)\n\n::: columns\n::: column\n1.  Check expected cell counts threshold\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpected(SHS_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          \n           Diabetic Not diabetic\n  Impaired  104.226      427.774\n  Normal    221.774      910.226\n```\n:::\n:::\n\n\nWe're going to pretend they are less than 5.\n\n2.  $\\alpha = 0.05$\n\n3.  Hypothesis test:\n\n    -   $H_0$ : There is no association between glucose tolerance and diabetes\n    -   $H_1$ : There is an association between glucose tolerance and diabetes\n:::\n\n::: column\n4.  Calculate the test statistic and p-value for Chi-squared test in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(x = SHS_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  SHS_table\np-value < 2.2e-16\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 3.576595 6.048639\nsample estimates:\nodds ratio \n  4.644825 \n```\n:::\n:::\n\n\n5.  Conclusion to the hypothesis test\n\nWe reject the null hypothesis that glucose tolerance and diabetes are not associated ($p<2.2\\cdot10^{-16}$). There is sufficient evidence that glucose tolerance and diabetes incidence are associated among American Indians.\n:::\n:::\n\n# Learning Objectives\n\n1.  Recognize the motivation for and focus of our course (categorical responses)\n\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n\n3.  Determine if a single proportion differs from a population value\n\n4.  Determine if two proportions differ from each other\n\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n\n::: lob\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n:::\n\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n\n## Test of Trend\n\n-   If [one or both variables are ordinal]{style=\"color:#34AC8B; font-weight: bold;\"}, a [test of trend]{style=\"color:#34AC8B; font-style: italic;\"} may be of interest\n\n    -   Treats ordinal variables as quantitative rather than qualitative (nominal scale)\n    -   Test of trend has greater power than the test of general association\n    -   You can use a test of general association for non-ordinal variables\n\n \n\n-   Two tests of trend that we we learn:\n\n    -   **Cochran-Armitage test**\n\n        -   Tests association between a *binary* response and an *ordinal* explanatory variable\n\n    -   **Mantel-Haenszel test**\n\n        -   Test association between an *ordinal* response and an *ordinal* explanatory variable\n\n## Cochran-Armitage test\n\n-   Cochran-Armitage test for trend will determine if there is association between a [binary response variable]{style=\"color:#34AC8B; font-weight: bold;\"} and an [ordinal variable with 3 or more categories]{style=\"color:#34AC8B; font-weight: bold;\"}\n\n \n\n-   It will test the trend of the proportions over the ordinal variable\n\n    -   Answers the question: Does the proportion of people with a \"successful\" outcome increase as the ordinal explanatory variable increases?\n  \n \n\n-   Cochran-Armitage test for trend is only suitable for 2 x C contingency tables\n\n## Cochran-Armitage test: Hypothesis Test\n\n::: columns\n::: column\n::: definition\n::: def-title\nNull Hypothesis ($H_0$)\n:::\n\n::: def-cont\nThe proportions of successes are the same across all C ordinal values of the explanatory variable. $$p_1 = p_2 = ... = p_C$$\n:::\n:::\n:::\n\n::: column\n::: proof1\n::: proof-title\nAlternative Hypothesis ($H_1$)\n:::\n\n::: proof-cont\nThe proportions of successes tend to increase as ordinal value of the explanatory variable increases\n\n$$p_1 \\leq p_2 \\leq ... \\leq p_C$$\n\nOR\n\nThe proportions of successes tend to decrease as ordinal value of the explanatory variable increases\n\n$$p_1 \\geq p_2 \\geq ... \\geq p_C$$\n:::\n:::\n:::\n:::\n\n## Cochran-Armitage test: Process\n\n1.  Set the [**level of significance**]{style=\"color:#34AC8B\"} $\\alpha$\n\n2.  Specify the [**null**]{style=\"color:#34AC8B\"} ( $H_0$ ) and [**alternative**]{style=\"color:#34AC8B\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#34AC8B\"}\n\n    -   In symbols\n    -   In words\n    -   Alternative: one- or two-sided?\n\n3.  Calculate the [**test statistic**]{style=\"color:#34AC8B\"} and [**p-value**]{style=\"color:#34AC8B\"} for Cochran-Armitage test in R\n\n    -   We will not discuss the test statistic's equation\n    -   Just know it follows a Normal distribution\n\n4.  Write a [**conclusion**]{style=\"color:#34AC8B\"} to the hypothesis test\n\n    -   Do we reject or fail to reject $H_0$?\n    -   Write a conclusion in the context of the problem\n\n## Cochran-Armitage test: Example (1/3)\n\nWe are interested in learning the association between the development of breast cancer and age at first birth among people who have given birth\n\n \n \n \n \n\n![](./images/Cancer_conting.png){fig-align=\"center\"}\n\n \n \n\n## Cochran-Armitage test: Example (2/3)\n\n-   Before we go into the hypothesis test procedure, we need to construct the contingency table in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCancer = c(320, 1206, 1011, 463, 220)\nNo_Cancer = c(1422, 4432, 2893, 1092, 406)\nbscancer = matrix (c(Cancer, No_Cancer), nrow = 2, byrow = T)\nrownames(bscancer) = c(\"Cancer\",\"No Cancer\")\ncolnames(bscancer) = c(\"<20\",\"20-24\",\"25-29\",\"30-34\",\">=35\")\nbscancer\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           <20 20-24 25-29 30-34 >=35\nCancer     320  1206  1011   463  220\nNo Cancer 1422  4432  2893  1092  406\n```\n:::\n:::\n\n\n-   It does not need to be pretty to use in function\n\n## Cochran-Armitage test: Example (3/3)\n\n::: columns\n::: column\n1.  $\\alpha = 0.05$\n\n2.  Hypothesis test:\n\n    -   $H_0$: The proportions of breast cancer are the same for all age levels of first birth. $$p_1 = p_2 = ... = p_5$$\n    -   $H_1$: The proportions of breast cancer tends to increase as level of age of first birth increases\n\n$$p_1 \\leq p_2 \\leq ... \\leq p_5$$\n:::\n\n::: column\n3.  Calculate the test statistic and p-value for Cochran-Armitage test in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DescTools)\nCochranArmitageTest(bscancer)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tCochran-Armitage test for trend\n\ndata:  bscancer\nZ = 11.358, dim = 5, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n:::\n:::\n\n\n4.  Conclusion to the hypothesis test\n\nWe reject the null hypothesis that proportions of breast cancer are the same for all age levels of first birth ($p<2.2\\cdot10^{-16}$). There is sufficient evidence that the proportion of of breast cancer increase as the the age at first birth increases.\n:::\n:::\n\n# Learning Objectives\n\n1.  Recognize the motivation for and focus of our course (categorical responses)\n\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n\n3.  Determine if a single proportion differs from a population value\n\n4.  Determine if two proportions differ from each other\n\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n\n::: lob\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n:::\n\n## Mantel-Haenszel test\n\n-   When both variables are ordinal, we can conduct Mantel-Haenszel test of trend for linear association\n\n-   Mantel-Haenszel test for linear trend is suitable for any R x C contingency tables with two ordinal variables\n\n-   Hypothesis test:\n\n::: columns\n::: column\n::: definition\n::: def-title\nNull Hypothesis ($H_0$)\n:::\n\n::: def-cont\nThere is no correlation between the two variables $$ \\rho = 0$$\n:::\n:::\n:::\n\n::: column\n::: proof1\n::: proof-title\nAlternative Hypothesis ($H_1$)\n:::\n\n::: proof-cont\nThere is correlation between the two variables\n\n$$ \\rho \\neq 0$$\n:::\n:::\n:::\n:::\n\n## Mantel-Haenszel test: Process\n\n1.  Set the [**level of significance**]{style=\"color:#34AC8B\"} $\\alpha$\n\n2.  Specify the [**null**]{style=\"color:#34AC8B\"} ( $H_0$ ) and [**alternative**]{style=\"color:#34AC8B\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#34AC8B\"}\n\n    -   In symbols\n    -   In words\n    -   Alternative: one- or two-sided?\n\n3.  Calculate the [**test statistic**]{style=\"color:#34AC8B\"} and [**p-value**]{style=\"color:#34AC8B\"} for Mantel-Haenszel test in R\n\n    -   We will not discuss the test statistic's equation\n\n4.  Write a [**conclusion**]{style=\"color:#34AC8B\"} to the hypothesis test\n\n    -   Do we reject or fail to reject $H_0$?\n    -   Write a conclusion in the context of the problem\n\n## Mantel-Haenszel test: Example (1/3)\n\nA water treatment company is studying water additives and investigating how they affect clothes washing (through measurements of abrasions, wearing, and color loss). \n\nThe treatments studies where no treatment (plain water), the standard treatment, and a double dose of the standard treatment, called super. Washability was measured as low, medium and high. \n\nAre levels of washability associated with treatment?\n\n \n\n![](./images/water_conting.png){fig-align=\"center\"}\n\n \n\n## Mantel-Haenszel test: Example (2/3)\n\n-   Before we go into the hypothesis test procedure, we need to construct the contingency table in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwater = matrix (c(27, 14, 5, 10, 17, 26, 5, 12, 50), nrow = 3, byrow = T)\nrownames(water) = c(\"plain\",\"standard\",\"super\")\ncolnames(water) = c(\"low\",\"medium\",\"high\")\nwater\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         low medium high\nplain     27     14    5\nstandard  10     17   26\nsuper      5     12   50\n```\n:::\n:::\n\n\n-   It does not need to be pretty to use in function\n\n## Mantel-Haenszel test: Example (3/3)\n\n::: columns\n::: column\n1.  $\\alpha = 0.05$\n\n2.  Hypothesis test:\n\n    -   $H_0$: Water treatment and washability are not correlated. $$ \\rho = 0$$\n    -   $H_1$: Water treatment and washability are correlated.\n\n$$ \\rho \\neq 0$$\n:::\n\n::: column\n3.  Calculate the test statistic and p-value for Mantel-Haenszel test in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DescTools)\nMHChisqTest(water)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tMantel-Haenszel Chi-Square\n\ndata:  water\nX-squared = 50.602, df = 1, p-value = 1.132e-12\n```\n:::\n:::\n\n\n4.  Conclusion to the hypothesis test\n\nWe reject the null hypothesis that there is no correlation between washability and water treatment ($p = 1.13 \\cdot 10^{-12} < 0.05$). There is sufficient evidence that level of water treatment is associated with washability.\n:::\n:::\n\n# Learning Objectives\n\n1.  Recognize the motivation for and focus of our course (categorical responses)\n\n2.  Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation\n\n3.  Determine if a single proportion differs from a population value\n\n4.  Determine if two proportions differ from each other\n\n5.  Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables\n\n6.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test\n\n7.  Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test\n\n8.  Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test\n\n9.  Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test\n\n## More resources\n\n-   [For a refresher or review](https://niederhausen.github.io/BSTA_511_F23/weeks/week_07.html) of one proportion and differences in proportions\n\n    -   And their power calculations\n\n    -   From Meike's BSTA 511 course (see Day 12!)\n    \n-   [For a refresher or review](https://niederhausen.github.io/BSTA_511_F23/weeks/week_08.html) of Chi-squared test or Fisher's Exact test\n\n    -   From Meike's BSTA 511 course (see Day 13!)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}