
schedule:
  - unit: "Summarizing Data"
    materials:
      - href: weeks/week_01_sched.qmd
        date: 01/08/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_02_sched.qmd
        date: 1/17/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_03_sched.qmd
        date: 1/22/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_04_sched.qmd
        date: 1/29/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_05_sched.qmd
        date: 2/5/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_06_sched.qmd
        date: 2/12/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_07_sched.qmd
        date: 2/21/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_08_sched.qmd
        date: 2/26/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_09_sched.qmd
        date: 3/4/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_10_sched.qmd
        date: 3/11/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_11_sched.qmd
        date: 3/18/24
        calendar-color: "#F14124"
        calendar-color2: "#FFFFFF"
        
      - href: homework/HW0.qmd
        title: "HW 0 due"
        date: 1/11/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF"
      - href: homework/HW1.qmd
        title: "HW 1 due"
        date: 1/25/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF"
      - title: "HW 2 due"
        href: homework/HW2.qmd
        date: 2/1/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF" 
      - title: "HW 3 due"
        href: homework/HW3.qmd
        date: 2/15/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF" 
      - title: "HW 4 due 2/25"
        href: homework/HW4.qmd
        date: 2/23/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF" 
      - title: "HW 5 due"
        href: homework/HW5.qmd
        date: 3/7/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF" 

      - title: "Quiz 1"
        date: 1/29/24        
        calendar-color: "#FF8021"
        calendar-color2: "#FFFFFF" 
      - title: "Quiz 2"
        date: 2/21/24        
        calendar-color: "#FF8021"
        calendar-color2: "#FFFFFF" 
      - title: "Quiz 3"
        date: 3/11/24        
        calendar-color: "#FF8021"
        calendar-color2: "#FFFFFF" 

      - title: "Lab 1 due"
        href: labs/Lab_01.qmd
        date: 1/18/24
        calendar-color: "#34AC8B"
        calendar-color2: "#FFFFFF"      
      - title: "Lab 2 due"
        href: labs/Lab_02.qmd
        date: 2/8/24
        calendar-color: "#34AC8B"
        calendar-color2: "#FFFFFF" 
      - title: "Lab 3 due 3/3"
        href: labs/Lab_03.qmd
        date: 3/1/24
        calendar-color: "#34AC8B"
        calendar-color2: "#FFFFFF" 
      - title: "Lab 4 due"
        href: labs/Lab_04.qmd
        date: 3/14/24
        calendar-color: "#34AC8B"
        calendar-color2: "#FFFFFF" 
      - title: "Final Project Due"
        href: labs/Project_report_instructions.qmd
        date: 3/21/24        
        calendar-color: "#34AC8B"
        calendar-color2: "#FFFFFF" 
        
      - title: "Virtual Class"
        date: 2/26/24
        calendar-color: "#A7EA52"
        calendar-color2: "#FFFFFF" 
      - title: "Virtual Class"
        date: 2/28/24
        calendar-color: "#A7EA52"
        calendar-color2: "#FFFFFF" 
        
      - title: "No Class: MLKJ Day"
        date: 1/15/24
        calendar-color: "#A7EA52"
        calendar-color2: "#FFFFFF" 
      - title: "No Class: Pres Day"
        date: 2/19/24
        calendar-color: "#A7EA52"
        calendar-color2: "#FFFFFF" 
        
      - title: "Midterm feedback due"
        href: https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURTVVRDNEMzhHVFRUQTRIVDdLSE1BNlFIWC4u
        date: 2/23/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF" 

        
auto-publish:
  timezone: "America/Los_Angeles"
  live-as-of: "Sys.time()"
  notes-1-release: "Friday, 17:00" # for Tu/Weds notes
  notes-2-release: "Friday, 17:00" # for Thu/Fri notes

instructors:
  - name: Andrew Bray
    email: "andrewbray@berkeley.edu"
    quartopub-name: andrew
  - name: Iain Carmichael
    email: "iain@berkeley.edu"
    quartopub-name: iainc
  - name: Silas Gifford
    email: "silascs@berkeley.edu"
    quartopub-name: silas
  - name: Jeremy Sanchez
    email: "jeremysanchez@berkeley.edu"
    quartopub-name: sanchez
  - name: Shobhana Stoyanov
    email: "shobhana@berkeley.edu"
    quartopub-name: shobhana
    
semester: "Fall, 2023"

