
schedule:
  - unit: "Summarizing Data"
    materials:
      - href: weeks/week_01_sched.qmd
        date: 04/01/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_02_sched.qmd
        date: 04/08/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_03_sched.qmd
        date: 04/15/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_04_sched.qmd
        date: 04/22/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_05_sched.qmd
        date: 04/29/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_06_sched.qmd
        date: 5/6/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_07_sched.qmd
        date: 5/13/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_08_sched.qmd
        date: 5/20/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_09_sched.qmd
        date: 5/29/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_10_sched.qmd
        date: 6/3/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
      - href: weeks/week_11_sched.qmd
        date: 6/10/24
        calendar-color: "#213c96"
        calendar-color2: "#FFFFFF"
        
      - href: homework/HW1.qmd
        title: "HW 1 due"
        date: 4/11/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF"
      - title: "HW 2 due"
        href: homework/HW2.qmd
        date: 4/25/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF" 
      - title: "HW 3 due"
        href: homework/HW3.qmd
        date: 5/9/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF" 
      - title: "HW 4 due"
        href: homework/HW4.qmd
        date: 5/23/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF" 
      - title: "HW 5 due"
        href: homework/HW5.qmd
        date: 6/6/24
        calendar-color: "#4FADF3"
        calendar-color2: "#FFFFFF" 

      - title: "Quiz 1"
        date: 4/22/24        
        calendar-color: "#E2534D"
        calendar-color2: "#FFFFFF" 
      - title: "Quiz 2"
        date: 5/13/24        
        calendar-color: "#E2534D"
        calendar-color2: "#FFFFFF" 
      - title: "Quiz 3"
        date: 6/3/24        
        calendar-color: "#E2534D"
        calendar-color2: "#FFFFFF" 

      - title: "Lab 1 due"
        href: labs/Lab_01.qmd
        date: 4/18/24
        calendar-color: "#34AC8B"
        calendar-color2: "#FFFFFF"      
      - title: "Lab 2 due"
        href: labs/Lab_02.qmd
        date: 5/2/24
        calendar-color: "#34AC8B"
        calendar-color2: "#FFFFFF" 
      - title: "Lab 3 due"
        href: labs/Lab_03.qmd
        date: 5/16/24
        calendar-color: "#34AC8B"
        calendar-color2: "#FFFFFF" 
      - title: "Lab 4 due"
        href: labs/Lab_04.qmd
        date: 5/30/24
        calendar-color: "#34AC8B"
        calendar-color2: "#FFFFFF" 
      - title: "Final Project Due"
        href: labs/Project_report_instructions.qmd
        date: 6/13/24        
        calendar-color: "#34AC8B"
        calendar-color2: "#FFFFFF" 
        
      - title: "No Class: Mem Day"
        date: 5/27/24
        calendar-color: "#A7EA52"
        calendar-color2: "#FFFFFF" 
        
      - title: "Midterm feedback due"
        href: https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURTVVRDNEMzhHVFRUQTRIVDdLSE1BNlFIWC4u
        date: 5/9/24
        calendar-color: "#C2352F"
        calendar-color2: "#FFFFFF" 

        
auto-publish:
  timezone: "America/Los_Angeles"
  live-as-of: "Sys.time()"
  notes-1-release: "Friday, 17:00" # for Tu/Weds notes
  notes-2-release: "Friday, 17:00" # for Thu/Fri notes
