project:
  type: website
  output-dir: docs

website:
  title: "Categorical Data Analysis"
  navbar:
    background: primary
    search: true
    logo: "images/Bsta513.png"
    foreground: "#fff"
    collapse-below: sm
    right:
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: homeworks.qmd
        text: Homework
      - href: project.qmd
        text: Projects
        
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - section: "Course Info"
        contents:
          - href: instructors.qmd
            text: Instructors
          - href: syllabus.qmd
            text: Syllabus
          - href: schedule.qmd
            text: Schedule
          - resources.qmd
          - quizzes.qmd
      - section: "Course Materials"
        contents:
          - href: weeks.qmd
          - href: lessons.qmd
          - href: homeworks.qmd
            text: Homework
          - href: project.qmd
            text: Project
          - href: readings.qmd
          
execute:
  freeze: auto

format:
  html:
    theme:
      - sandstone_NW.scss
    toc: true

