---
title: "Lessons"
date: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
    highlight-style: ayu
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #C2352F;
  background-color: #fff;
  padding: 0px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #C2352F;
  padding: 10px;
}
```

+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lesson    | Topic                                                        | Slides                                                                                                                                                 | Annotated Slides                                                                                                                                                          | Recording(s)                                                                                                                                                                                                                                         |
+===========+==============================================================+:======================================================================================================================================================:+:=========================================================================================================================================================================:+:====================================================================================================================================================================================================================================================:+
| 1         | File Organization within R                                   | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/01_File_Organization_R/01_File_Organization_R.qmd)]{style="color:#f8f5f0;"}                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                                                                                        | [[{{< iconify mdi video size=34px >}}](https://echo360.org/section/3d2de378-ed40-415a-8caf-8c75f3b5d9ff/public)]{style="color:#f8f5f0;"}                                                                                                             |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2         | Introduction to Categorical Analysis                         | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/02_Intro_CDA/02_Intro_CDA.qmd)]{style="color:#f8f5f0;"}                                       | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/02_Intro_CDA/02_Intro_CDA_notes.pdf)]{style="color:#f8f5f0;"}                                       | [[{{< iconify mdi video size=34px >}}](https://echo360.org/media/97486deb-8346-4aef-a24e-a77a7350a6f2/public)]{style="color:#f8f5f0;"}                                                                                                               |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3         | Measurement of Association for Contingency Tables            | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/03_Meas_Assoc_CT/03_Meas_Assoc_CT.qmd)]{style="color:#f8f5f0;"}                               | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/03_Meas_Assoc_CT/03_Meas_Assoc_CT_notes.pdf)]{style="color:#f8f5f0;"}                               | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_a2cd2099-5666-4143-b05a-a1e020f96c16_dffa6d24-1dbf-45aa-8ff9-abe9b32c4e9e_2024-04-08T13:00:00.000_2024-04-08T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4         | Measurements of Association and Agreement                    | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree.qmd)]{style="color:#f8f5f0;"}                         | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree_notes.pdf)]{style="color:#f8f5f0;"}                         | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/2efcec30-2c02-454a-b2d8-e64057b6846a/classroom#sortDirection=desc)]{style="color:#f8f5f0;"}                                                                                        |
|           |                                                              |                                                                                                                                                        |                                                                                                                                                                           |                                                                                                                                                                                                                                                      |
|           |                                                              |                                                                                                                                                        |                                                                                                                                                                           | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_a2cd2099-5666-4143-b05a-a1e020f96c16_dffa6d24-1dbf-45aa-8ff9-abe9b32c4e9e_2024-04-10T13:00:00.000_2024-04-10T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5         | Simple Logistic Regression                                   | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/05_Simple_logistic_reg/05_Simple_logistic_reg.qmd)]{style="color:#f8f5f0;"}                   | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/05_Simple_logistic_reg/05_Simple_logistic_reg_notes.pdf)]{style="color:#f8f5f0;"}                   | [[{{< iconify mdi video size=34px >}}](https://echo360.org/media/5ab6c501-bc15-427e-9199-766526c7f9eb/public)]{style="color:#f8f5f0;"}                                                                                                               |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 6         | Tests for GLMs using Likelihood function                     | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/06_Tests_GLMs/06_Tests_GLMs.qmd)]{style="color:#f8f5f0;"}                                     | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/06_Tests_GLMs/06_Tests_GLMs_notes.pdf)]{style="color:#f8f5f0;"}                                     | [[{{< iconify mdi video size=34px >}}](https://echo360.org/media/f28738d1-e2bf-47b7-9a2b-25075009f371/public)]{style="color:#f8f5f0;"}                                                                                                               |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7         | Predictions and Visualizations in Simple Logistic Regression | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/07_Pred_Viz/07_Pred_Viz.qmd)]{style="color:#f8f5f0;"}                                         | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/07_Pred_Viz/07_Pred_Viz_notes.pdf)]{style="color:#f8f5f0;"}                                         | [[{{< iconify mdi video size=34px >}}](https://echo360.org/media/b3390bba-c038-473b-a418-4f3caec0d9c6/public)]{style="color:#f8f5f0;"}                                                                                                               |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8         | Interpretations and Visualizations of Odds Ratios            | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/08_Interpretations_SLR/08_Interpretations_SLR.qmd)]{style="color:#f8f5f0;"}                   | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/08_Interpretations_SLR/08_Interpretations_SLR_notes.pdf)]{style="color:#f8f5f0;"}                   | [[{{< iconify mdi video size=34px >}}](https://echo360.org/media/47cae393-9579-40a1-8555-eb26e3add5dc/public)]{style="color:#f8f5f0;"}                                                                                                               |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9         | Missing Data                                                 | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/09_Missing_data/09_Missing_data.pdf)]{style="color:#f8f5f0;"}                                 | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/09_Missing_data/09_Missing_data_notes.pdf)]{style="color:#f8f5f0;"}                                 | [[{{< iconify mdi video size=34px >}}](https://echo360.org/media/6ef21281-6334-4139-ab89-0809aefa370b/public)]{style="color:#f8f5f0;"}                                                                                                               |
|           |                                                              |                                                                                                                                                        |                                                                                                                                                                           |                                                                                                                                                                                                                                                      |
|           | Activity:                                                    | [[{{< iconify clarity group-solid size=29px >}}](/lectures/09_Missing_data/09_Activity_dogs.pptx)]{style="color:#f8f5f0;"}                             |                                                                                                                                                                           |                                                                                                                                                                                                                                                      |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10        | Multiple Logistic Regression                                 | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/10_Multiple_logistic_regression/10_Multiple_logistic_regression.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/10_Multiple_logistic_regression/10_Multiple_logistic_regression_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/media/bde13efd-786f-445e-99c8-1e78cadf5981/public)]{style="color:#f8f5f0;"}                                                                                                               |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11        | Interactions                                                 | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/11_Interactions/11_Interactions.qmd)]{style="color:#f8f5f0;"}                                 | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/11_Interactions/11_Interactions_notes.pdf)]{style="color:#f8f5f0;"}                                 | [[{{< iconify mdi video size=34px >}}](https://echo360.org/media/262f895d-25ac-4dc2-a3b9-cb467d2750c6/public)]{style="color:#f8f5f0;"}                                                                                                               |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13        | Numerical Problems                                           |                                                                                                                                                        |                                                                                                                                                                           |                                                                                                                                                                                                                                                      |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14        | Assessing Model Fit                                          |                                                                                                                                                        |                                                                                                                                                                           |                                                                                                                                                                                                                                                      |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15        | Model Building Strategies                                    |                                                                                                                                                        |                                                                                                                                                                           |                                                                                                                                                                                                                                                      |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16        | Revisit interpretations                                      |                                                                                                                                                        |                                                                                                                                                                           |                                                                                                                                                                                                                                                      |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 17        | Poisson Regression                                           |                                                                                                                                                        |                                                                                                                                                                           |                                                                                                                                                                                                                                                      |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 18        | Log-binomial regression                                      |                                                                                                                                                        |                                                                                                                                                                           |                                                                                                                                                                                                                                                      |
+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```{r}
#| echo: false

g=3
```
