---
title: "Project Central"
date: "4/1/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
  pdf: default
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #C2352F;
  background-color: #fff;
  padding: 0px;
}
```

## Labs

+-------------------------------------------------------------------------------+----------+------------------------------------------------------+
| Lab                                                                           | Due Date | Topics                                               |
+===============================================================================+==========+======================================================+
| [Lab 1](/project/Lab_01_instructions.qmd)                                     | 4/18     | Exploring the question and data                      |
+-------------------------------------------------------------------------------+----------+------------------------------------------------------+
| [Lab 2](/project/Lab_02_instructions.qmd)                                     | 5/2      | EDA continued + Simple logistic regression           |
+-------------------------------------------------------------------------------+----------+------------------------------------------------------+
| [Lab 3](/project/Lab_03_instructions.qmd)                                     | 5/16     | Multiple logistic regression + optional missing data |
|                                                                               |          |                                                      |
| [Optional missing data code if you want to try it](/project/Missing_data.qmd) |          |                                                      |
+-------------------------------------------------------------------------------+----------+------------------------------------------------------+
| [Lab 4](/project/Lab_04_instructions.qmd)                                     | 5/30     | Building and interpreting final model                |
+-------------------------------------------------------------------------------+----------+------------------------------------------------------+

## Report

[Report Instructions](/project/Project_report_instructions.qmd)

Due 6/13/2024

```{r}
#| echo: false
g=3
```

## Information and Resources on Food Insecurity

This project will discuss food insecurity and unmet basic needs. If you have experienced or are experiencing food insecurity, and this project impacts your mental health or ability to work, please let me know. We can work on an alternative analysis with a different dataset.

If you are currently experiencing food insecurity or not meeting your basic needs, here are some resources for Oregon residents:

-   [Oregon One elegibility page](https://one.oregon.gov/)

    -   You can apply for benefits including medical, food, cash, or child care assistance
    -   This is one way to apply to multiple benefits

-   [Oregon Health Plan](https://www.oregon.gov/oha/hsd/ohp/pages/splash.aspx)

-   The Oregon Food Bank has a [food finder](https://foodfinder.oregonfoodbank.org/)

In addition to these statewide resources, as students, there are other resources available to you:

-   [Food Assistance and Basic Needs for OHSU students](https://www.ohsu.edu/education/food-assistance-and-basic-needs)

    -   Includes information on [SNAP program](https://www.oregon.gov/odhs/food/pages/snap.aspx)

    -   Includes information on free groceries available to students at the Food Resource Center

        -   You can even order it online and pick it up!

-   You can email basicneeds\@ohsu.edu for help getting assistance or connecting you to the following services:

    -   Manage your finances
    -   Access emergency funds
    -   Find legal services
    -   Apply for SNAP
    -   Find child care
    -   Find housing

## Reading and listening sources
