---
title: "613 Readings"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
  pdf: default
editor_options: 
  chunk_output_type: console
---

These reading assignments are for 613 students only. 613 students, you must complete all the readings by 6/6. I have included some recommended due dates that will keep you on track if you would like.

| Reading | Recommended Due Date | Link to Sakai                                                    | Article                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|------------------|------------------|------------------|------------------|
| 1       | 4/11 \@ 11pm         | [{{< iconify ph link-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify material-symbols article size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/onedrive.aspx?FolderCTID=0x012000313CF7F10467BC479DC8A23F258AB10C&id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FS2024%5FBSTA%5F513%5F613%2FStudent%5Ffiles%2FReadings%5F613%2FReading%5F01%5FJCEM%5FWalter%5F2000%5FChoiceofEffectMeasure%2Epdf&parent=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FS2024%5FBSTA%5F513%5F613%2FStudent%5Ffiles%2FReadings%5F613) |
| 2       | 4/25 \@ 11pm         | [{{< iconify ph link-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify material-symbols article size=34px >}}](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S2024_BSTA_513_613/Student_files/Readings_613/Reading_02_Interrater_agreement.Kappa_statistic.pdf?csf=1&web=1&e=XKrQKl)                                                                                                                                                                                                                                                                     |
| 3       | 5/2 \@ 11pm          | [{{< iconify ph link-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify material-symbols article size=34px >}}](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S2024_BSTA_513_613/Student_files/Readings_613/Reading_03_Gallis_ModelingBin_Outcomes_AnnGlobHealth_2019%5B1%5D.pdf?csf=1&web=1&e=6Flm3W)                                                                                                                                                                                                                                                    |
| 4       | 5/16 \@ 11pm         | [{{< iconify ph link-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify material-symbols article size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/onedrive.aspx?FolderCTID=0x012000313CF7F10467BC479DC8A23F258AB10C&id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FS2024%5FBSTA%5F513%5F613%2FStudent%5Ffiles%2FReadings%5F613%2FReading%5F04%5Fpurposeful%20selection%20using%20R%2Epdf&parent=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FS2024%5FBSTA%5F513%5F613%2FStudent%5Ffiles%2FReadings%5F613)           |
| 5       | 5/30 \@ 11pm         | [{{< iconify ph link-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify material-symbols article size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/onedrive.aspx?FolderCTID=0x012000313CF7F10467BC479DC8A23F258AB10C&id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FS2024%5FBSTA%5F513%5F613%2FStudent%5Ffiles%2FReadings%5F613%2FReading%5F05%5FMultivariable%5For%5FMultivariate%2Epdf&parent=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FS2024%5FBSTA%5F513%5F613%2FStudent%5Ffiles%2FReadings%5F613)            |

### Instructions for each assignment

For each reading assignment, students will write a summary including:

-   study background,

-   why the author think the research important,

-   statistical methods used to address the research question,

-   and a discussion/critique on whether you agree or disagree with the authors'  science and statistics.

You may write complete sentences under each bullet point. Please keep your summary to less than 1 page (margins are up to you). There are no requirements on formatting for references. 
