<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="quarto-1.3.450" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />


<title>Categorical Data Analysis – BSTA 513/613 Syllabus</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>

<!-- htmldependencies:E3FAD763 -->
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-sm navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="/index.html" class="navbar-brand navbar-brand-logo">
    <img src="/images/Bsta513.png" alt="" class="navbar-logo" />
    </a>
    <a class="navbar-brand" href="/index.html">
    <span class="navbar-title">Categorical Data Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
  aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"
  onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="/syllabus.html" rel="" target="">
 <span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/schedule.html" rel="" target="">
 <span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/homeworks.html" rel="" target="">
 <span class="menu-text">Homework</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/project.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn"
      data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" 
      aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation"
      onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <h1 class="quarto-secondary-nav-title"></h1>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" 
      aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation"
      onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Course Info</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/instructors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Instructors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/syllabus.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/quizzes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quizzes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Course Materials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/weeks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Weekly Pages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/lessons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lessons</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/homeworks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/readings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">613 Readings</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" ></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <div id="quarto-toc-target"></div>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BSTA 513/613 Syllabus</h1>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">April 12, 2024</p>
    </div>
  </div>
    
  </div>
  

</header>
<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#description" id="toc-description">Description</a>
  <ul>
  <li><a href="#course-learning-objectives" id="toc-course-learning-objectives">Course Learning Objectives</a></li>
  </ul></li>
  <li><a href="#instructors" id="toc-instructors">Instructors</a></li>
  <li><a href="#meeting-times" id="toc-meeting-times">Meeting Times</a></li>
  <li><a href="#materials" id="toc-materials">Materials</a>
  <ul>
  <li><a href="#textbooks" id="toc-textbooks">Textbooks</a></li>
  <li><a href="#online-resources" id="toc-online-resources">Online Resources</a></li>
  </ul></li>
  <li><a href="#assessment" id="toc-assessment">Assessment</a></li>
  <li><a href="#assessment-breakdown" id="toc-assessment-breakdown">Assessment Breakdown</a>
  <ul>
  <li><a href="#grading-requirements" id="toc-grading-requirements">Grading &amp; Requirements</a></li>
  <li><a href="#homework-grading" id="toc-homework-grading">Homework grading</a></li>
  <li><a href="#lab-grading" id="toc-lab-grading">Lab grading</a></li>
  <li><a href="#viewing-grades-in-sakai" id="toc-viewing-grades-in-sakai">Viewing Grades in Sakai</a></li>
  </ul></li>
  <li><a href="#course-instructor-evaluations" id="toc-course-instructor-evaluations">Course &amp; Instructor Evaluations</a>
  <ul>
  <li><a href="#ongoing-course-feedback" id="toc-ongoing-course-feedback">Ongoing Course Feedback</a></li>
  <li><a href="#mid-quarter-feedback" id="toc-mid-quarter-feedback">Mid-quarter Feedback</a></li>
  <li><a href="#final-course-feedback" id="toc-final-course-feedback">Final Course Feedback</a></li>
  </ul></li>
  <li><a href="#schedule" id="toc-schedule">Schedule</a></li>
  <li><a href="#how-to-succeed-in-this-course" id="toc-how-to-succeed-in-this-course">How to succeed in this course</a>
  <ul>
  <li><a href="#resources" id="toc-resources">Resources</a></li>
  <li><a href="#assignments" id="toc-assignments">Assignments</a></li>
  </ul></li>
  <li><a href="#course-policies-and-resources" id="toc-course-policies-and-resources">Course Policies and Resources</a>
  <ul>
  <li><a href="#late-work-policy" id="toc-late-work-policy">Late Work Policy</a></li>
  <li><a href="#regrade-policy" id="toc-regrade-policy">Regrade Policy</a></li>
  <li><a href="#attendance-policy" id="toc-attendance-policy">Attendance Policy</a></li>
  <li><a href="#plagiarism-and-attribution" id="toc-plagiarism-and-attribution">Plagiarism and Attribution</a></li>
  </ul></li>
  <li><a href="#course-expectations" id="toc-course-expectations">Course Expectations</a>
  <ul>
  <li><a href="#instructor-expectations" id="toc-instructor-expectations">Instructor Expectations</a></li>
  <li><a href="#student-expectations-and-resources" id="toc-student-expectations-and-resources">Student Expectations and Resources</a></li>
  </ul></li>
  <li><a href="#course-communications" id="toc-course-communications">Course Communications</a></li>
  <li><a href="#further-student-resources" id="toc-further-student-resources">Further Student Resources</a>
  <ul>
  <li><a href="#sph-writing-lab" id="toc-sph-writing-lab">SPH Writing Lab</a></li>
  <li><a href="#grammarly-subscription" id="toc-grammarly-subscription">Grammarly Subscription</a></li>
  <li><a href="#student-wellness" id="toc-student-wellness">Student Wellness</a></li>
  <li><a href="#support-for-food-insecurity" id="toc-support-for-food-insecurity">Support for Food Insecurity</a></li>
  <li><a href="#support-for-students-with-children" id="toc-support-for-students-with-children">Support for Students with Children</a></li>
  </ul></li>
  <li><a href="#school-policies-and-resources" id="toc-school-policies-and-resources">School Policies and Resources</a>
  <ul>
  <li><a href="#school-of-public-health-handbook" id="toc-school-of-public-health-handbook">School of Public Health Handbook</a></li>
  <li><a href="#student-access-accommodations" id="toc-student-access-accommodations">Student Access &amp; Accommodations</a></li>
  <li><a href="#title-ix" id="toc-title-ix">Title IX</a></li>
  <li><a href="#technical-support" id="toc-technical-support">Technical Support</a></li>
  </ul></li>
  <li><a href="#ohsu-competencies" id="toc-ohsu-competencies">OHSU Competencies</a></li>
  <li><a href="#institutional-policies-and-resources" id="toc-institutional-policies-and-resources">Institutional Policies and Resources</a>
  <ul>
  <li><a href="#statement-regarding-students-with-disabilities" id="toc-statement-regarding-students-with-disabilities">Statement Regarding Students with Disabilities</a></li>
  <li><a href="#student-evaluation-of-courses" id="toc-student-evaluation-of-courses">Student Evaluation of Courses</a></li>
  <li><a href="#copyright-information" id="toc-copyright-information">Copyright Information</a></li>
  <li><a href="#syllabi-changes-and-retention" id="toc-syllabi-changes-and-retention">Syllabi Changes and Retention</a></li>
  <li><a href="#commitment-to-diversity-inclusion" id="toc-commitment-to-diversity-inclusion">Commitment to Diversity &amp; Inclusion</a></li>
  <li><a href="#modified-operations-policy-01-40-010" id="toc-modified-operations-policy-01-40-010">Modified Operations, Policy 01-40-010</a></li>
  <li><a href="#ohsu-resources-available-to-students" id="toc-ohsu-resources-available-to-students">OHSU Resources Available to Students*:</a></li>
  <li><a href="#privacy-while-learning" id="toc-privacy-while-learning">Privacy While Learning</a></li>
  <li><a href="#student-central" id="toc-student-central">Student Central</a></li>
  </ul></li>
  </ul>
</nav>
<div class="cell">
<style type="text/css">
.title{
  font-size: 40px;
  color: #C2352F;
  background-color: #fff;
  padding: 0px;
}
</style>
</div>
<section id="description" class="level2">
<h2>Description</h2>
<p>Welcome to BSTA 513/613! In this course, we will continue to learn about regression analysis, but not with categorical outcomes. We will build some theoretical understanding in order to interpret and apply logistic regression models appropriately. We will learn how to build a logistic regression model, interpret the model and coefficients, and diagnose potential issues with our model.</p>
<section id="course-learning-objectives" class="level3">
<h3>Course Learning Objectives</h3>
<p>At the end of this course, students should be able to…</p>
<ol type="1">
<li><p>Apply and interpret a variety of hypothesis-testing procedures for two-way and three-way contingency tables</p></li>
<li><p>Compute and interpret measures of association for binary and ordinal data.</p></li>
<li><p>Calculate and correctly interpret odds ratios using logistic regression, make comparison across groups and examine relationship between binary outcome and predictor variables.</p></li>
<li><p>Apply appropriate model-building strategies for logistic regression. Effectively use statistical computing packages for contingency table and logistic regression procedures.</p></li>
<li><p>Perform Poisson regression analysis using count data and interpret model estimates, make comparison across groups and examine relationship between outcome and predictor variables.</p></li>
<li><p>Coherently summarize methods and results of data analyses, and discuss in context of original health-related research questions to audiences with varied statistical background.</p></li>
</ol>
</section>
</section>
<section id="instructors" class="level2">
<h2>Instructors</h2>
<p><a href="instructors.qmd">Here is the instructor page.</a> This also has office hours!</p>
</section>
<section id="meeting-times" class="level2">
<h2>Meeting Times</h2>
<p>Mondays          1:00 PM – 2:50 PM PST in RPV Room A/B</p>
<p>Wednesdays    1:00 PM – 2:50 PM PST in RPV Room A/B</p>
</section>
<section id="materials" class="level2">
<h2>Materials</h2>
<section id="textbooks" class="level3">
<h3>Textbooks</h3>
<ul>
<li><p><a href="https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S2024_BSTA_513_613/Student_files/Textbooks/Hosmer_Applied_Logistic_Regression.pdf?csf=1&amp;web=1&amp;e=Ur29qk">Applied Logistic Regression</a> by David Hosmer, Stanley Lemeshow, and Rodney Sturdivant</p></li>
<li><p><a href="https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S2024_BSTA_513_613/Student_files/Textbooks/Agresti_Introduction_to_Categorical_Data.pdf?csf=1&amp;web=1&amp;e=WBwuuW">An Introduction to Categorical Data Analysis</a> by Alan Agresti</p></li>
<li><p><a href="https://bookdown.org/rwnahhas/RMPH/">Introduction to Regression Methods for Public Health Using R</a> by Ramzi W. Nahhas</p>
<ul>
<li>Specifically Chapter 6</li>
</ul></li>
</ul>
<section id="supplemental-readings-optional" class="level4">
<h4>Supplemental Readings (Optional)</h4>
<ul>
<li><em>An Introduction to R</em> (<a href="http://cran.r-project.org/manuals.html">free pdf available</a>)</li>
</ul>
</section>
</section>
<section id="online-resources" class="level3">
<h3>Online Resources</h3>
<section id="slack" class="level4">
<h4>Slack</h4>
<p>We will use Slack as our main form of communication for the class. If you are unsure how to do a homework problem or have other questions, please ask me by posting your question(s) on Slack. Please know that Slack is not guarded by the OSHU firewall, so if you have a question about accommodations or any sensitive topics, you may wish to message me via email. You can still message me regarding sensitive information on Slack, but I will not initiate those conversations on Slack.</p>
<p><a href="https://join.slack.com/t/slack-kp94638/shared_invite/zt-2fwl1ziz7-K98XEP_8qLEMzagVlzJWbQ">**Please use this invitation link for our Slack workspace!**</a></p>
<p><strong>Tips on asking questions:</strong></p>
<ul>
<li>When reaching out for help for a homework problem, please include some context on what you have already tried.
<ul>
<li>For example, including a photo of your work thus far with an explanation of where you think you might be wrong is a quick way for me to look over your work and help you troubleshoot. This helps me see what parts you already understand and which you need help with. If your question involves code, please <strong>include the copied code (not a screenshot)</strong> and an attachment to your full file. This way I can see the exact line you need help with and the full code in case the problem starts earlier.</li>
<li>If you are unsure how to start a problem, look through your notes and the book for examples that you think might be similar. When reaching out, mention these examples and why you think they might be helpful, but also why you are still unsure on how to proceed.</li>
<li>If you only write something similar to “I don’t know how to do problem xxx,” then my response will be to ask you what you tried so far. Thus, it will be quicker for you to let me know this information right away.</li>
</ul></li>
<li>If asking for help about a specific example that you don’t understand, please also provide some detail beyond “I don’t understand example xxx.”
<ul>
<li>Which steps of the problem do you not understand? You can refer to a line number, for example.</li>
<li>If you don’t understand the first step, do you understand the ones following it?</li>
</ul></li>
<li>In general, when asking a question, please provide the homework number it is from along with the chapter and problem number. If it’s an example from the notes or book, an example number or slide number will help finding it.</li>
<li>Want more tips on asking questions? This list on <a href="https://www.weareteachers.com/8-ways-to-pose-better-questions-in-math-class/" class="uri">this site</a> will help!</li>
<li>Finally, if I don’t respond within a day and you need a response soon, <em>please remind me by emailing or messaging me again</em>.</li>
</ul>
</section>
<section id="sakai" class="level4">
<h4>Sakai</h4>
<p>While most course materials will be delivered online through this website, assignments will be turned in through <a href="https://sakai.ohsu.edu/">Sakai</a>, OHSU’s course management system. I will include a link on this website to the Sakai assignment page. </p>
</section>
<section id="webex" class="level4">
<h4>Webex</h4>
<p>Webex software will be used for virtual office hours. To give everyone the best possible experience with Webex, I recommend the following best practices:</p>
<ul>
<li>Please stay muted until you want to participate</li>
<li>During office hours, please send a message in chat with your question or with a statement like “I have a question.” This makes sure I or the TA can address everyone’s questions in order. </li>
<li>I encourage you to attend office hours with your video on. This helps me recognize you, and keep mental notes on what techniques/concepts I emphasize to facilitate your specific understanding. </li>
</ul>
</section>
<section id="poll-everywhere" class="level4">
<h4>Poll Everywhere</h4>
<p>We will use the Poll Everywhere tool as an interactive feature of the course. Poll Everywhere is a web-based application that allows students to participate by responding via text messages or by visiting a web page on an internet-enabled device (smartphone, tablet, laptop). Instructions will be displayed on-screen. The poll that is embedded within the presentation will update in real time. While there is no cost to use this software, standard text messaging rates will apply if you use your phone. Please make sure that you have a Poll Everywhere account before our first class. You are not required to use your OHSU/PSU email to make an account. </p>
<p>During lectures I will pose questions to the class. These questions are designed to provide real-time feedback to both students and the instructor on how well students are grasping the material. This is meant to be an interactive, learning activity with NO contribution to your grade. Your identity will never be connected to your answers, so I encourage you to answer honestly.</p>
</section>
<section id="pennstate-stat-504-website" class="level4">
<h4>PennState STAT 504 Website</h4>
<p>PennState has a class offered to online MS students that has some overlap with our class. They have all their <a href="https://online.stat.psu.edu/stat504/lesson/welcome-stat-504">course notes posted on this page</a>. This is a great source if you would like to see class notes with different phrasing.</p>
<p>Not all of our topics are covered in their notes, but the most important ones are. If you are having trouble finding our course’s concepts on their page, please make ask me at Office Hours, after class, or in a private meeting. I do not explicitly state corresponding sections under our schedule because I believe it is important for you to develop skills involving resources and learning key words that can help you find answers. </p>
</section>
<section id="r-statistical-computing-software" class="level4">
<h4>R: Statistical Computing Software</h4>
<p>Students will use statistical software to complete homework assignments. Students are required to use R/RStudio for this course. R can be freely downloaded. <a href="https://rstudio-education.github.io/hopr/starting.html">Helpful documentation</a> on installing R is available. <strong>I encourage you to install R prior to attending our first lecture.</strong> Please email me if you need help installing R or RStudio.</p>
<p>You will need to download the following three things:</p>
<ol type="1">
<li><p>R <a href="https://www.r-project.org/" class="uri">https://www.r-project.org/</a></p></li>
<li><p>Rstudio <a href="https://posit.co/download/rstudio-desktop/" class="uri">https://posit.co/download/rstudio-desktop/</a></p></li>
<li><p>Quarto <a href="https://quarto.org/docs/get-started/" class="uri">https://quarto.org/docs/get-started/</a></p></li>
</ol>
<section id="additional-r-resources" class="level5">
<h5>Additional R Resources</h5>
<p>Your learning and practicing of R will hopefully not be limited to this course. One of the best aspects of programming in R is that many resources are freely available online. Here are just a few additional resources you may explore beyond this class to continue your training in R.</p>
</section>
<section id="useful-online-r-resources" class="level5">
<h5>Useful online R resources</h5>
<ul>
<li><a href="https://rfortherestofus.com/">R for the rest of us</a></li>
<li>Statistical tools for high-throughput data analysis. <a href="http://www.sthda.com/english/wiki/ggplot2-essentials#google_vignette">ggplot2 essentials</a></li>
<li><a href="http://www.r-bloggers.com/">R-bloggers</a></li>
<li>Stack Overflow for troubleshooting</li>
<li><a href="https://www.imsbio.co.jp/RGM/R_image_list">R Graphical Manual</a></li>
<li><a href="http://www.statmethods.net/">Quick-R</a>. Accessing the power of R</li>
<li><a href="http://r4stats.com/">R for SAS, STATA, and SPSS Users</a></li>
<li><a href="https://ggplot2.tidyverse.org/">ggplot2</a></li>
<li><a href="https://www.learnr4free.com/en/index.html">Learn R 4 free</a></li>
<li><a href="https://www.r-consortium.org/blog/2019/09/09/r-community-explorer-r-user-groups">Join a local R user groups</a></li>
<li><a href="https://blog.ephorie.de/learning-r-the-ultimate-introduction-incl-machine-learning">Learning Machines</a></li>
</ul>
</section>
</section>
<section id="online-r-courses-to-complement-or-refresh-material-from-class" class="level4">
<h4>Online R courses to complement or refresh material from class</h4>
<ul>
<li><a href="https://rfortherestofus.com/">R for the rest of us</a></li>
<li>Coursera: <a href="https://www.coursera.org/learn/r-programming">R programming</a></li>
<li>edX: <a href="https://www.edx.org/course/data-science-r-basics">R basics</a></li>
<li>Data Carpentry: For Biologists</li>
<li>Data Carpentry: <a href="https://datacarpentry.org/lessons/#ecology-workshop">For Ecologists</a></li>
<li><a href="https://psyteachr.github.io/">Psychiatric R</a></li>
<li><a href="https://r-coder.com/">R coder</a></li>
</ul>
</section>
</section>
</section>
<section id="assessment" class="level2">
<h2>Assessment</h2>
<p>The course is structured around the following four components:</p>
<table style="width:100%;">
<colgroup>
<col style="width: 4%" />
<col style="width: 2%" />
<col style="width: 3%" />
<col style="width: 89%" />
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Component</strong></td>
<td style="text-align: center;"><strong>Modality</strong></td>
<td style="text-align: center;"><strong>Frequency</strong></td>
<td style="text-align: left;"><strong>Description</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">Lecture</td>
<td style="text-align: center;">In person</td>
<td style="text-align: center;">Twice, Weekly</td>
<td style="text-align: left;">Course content is provided through in-person lectures. Lectures will consist of didactic lessons, interactive examples, and PollEverywhere questions. Sessions will be recorded through Explain Everything and posted to Sakai. <strong>Attending or viewing the lecture within 7 days of the original lecture date is mandatory.</strong> Class attendance will be taken through an Exit Ticket. If viewing the lecture asynchronously, you must take the Exit Ticket to verify your attendance.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Homework</td>
<td style="text-align: center;">Online</td>
<td style="text-align: center;">Weekly</td>
<td style="text-align: left;">The course includes 7 homework assignments. They are an opportunity for you to engage with important concepts, practice coding, and apply calculating skills. Homework assignments should be submitted online, and will be graded by me. Students are encouraged to work in groups for homework assignments, but each person should do their own summary and hand in their work. <strong>Homework assignments will be due on Thursday at 11 PM.</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">Quizzes</td>
<td style="text-align: center;">In person</td>
<td style="text-align: center;">Every 3 weeks</td>
<td style="text-align: left;">The purpose of the quizzes is to assess how well you have achieved the learning objectives through questions covering important concepts, conducting statistical processes, and interpreting output. <strong>We will have our quizzes in-class, and it will be open book.</strong> Students must work on the quizzes independently.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Project (Labs and Report)</td>
<td style="text-align: center;">Online</td>
<td style="text-align: center;">4 labs, 1 final report</td>
<td style="text-align: left;">The project will be a combination of submitted labs that will span the quarter and one final report submitted at the end of the quarter. This is meant to translate the tools learned in the course to the work one may do in the workforce. This will help instill the procedure for shaping research goals, model selection, analyzing data, and interpreting meaningful results. Labs will guide you through the needed analysis and background for the project. The final report will summarize your work over the labs and more closely align with a journal article. Students will work independently on each lab.</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<section id="types-of-assessments" class="level4">
<h4>Types of assessments</h4>
<p>This class will use a combination of formative and summative assessments to build and test our knowledge. Below I define each of these types of assessments:</p>
<ul>
<li><p><strong>Formative assessment:</strong> Activity or work meant to help students learn and practice. Feedback on these assessments are meant to help the instructor and student identify gaps in knowledge and highlight accomplishments.</p></li>
<li><p><strong>Summative assessment:</strong> Work meant to test how well students have achieved learning objectives. Grading of these assessments are meant to gauge how well a student grasps the learning objectives and will be able to use their knowledge outside of the classroom.</p></li>
</ul>
</section>
</section>
<section id="assessment-breakdown" class="level2">
<h2>Assessment Breakdown</h2>
<section id="grading-requirements" class="level3">
<h3>Grading &amp; Requirements</h3>
<p>Letter grades will be assigned roughly according to the following scheme: A (&gt;=93%), A- (90-92%), B+ (88-89%), B(83-87%), B- (82-80%), C+(78-79%), C(73-77%), C- (70-72%), D (60 – 69%), F(&lt;60%).</p>
<p>Grades will be based on homework assignments, midterm exam, class “attendance”, and final exam, as follows:</p>
<table style="width:98%;">
<colgroup>
<col style="width: 16%" />
<col style="width: 14%" />
<col style="width: 15%" />
<col style="width: 25%" />
<col style="width: 25%" />
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Course activity</strong></td>
<td style="text-align: center;"><strong>Type of Assessment</strong></td>
<td style="text-align: center;"><strong>Due Date</strong></td>
<td style="text-align: center;"><strong>Percentage of final grade (BSTA 513)</strong></td>
<td style="text-align: center;"><strong>Percentage of final grade (BSTA 613)</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">Homework</td>
<td style="text-align: center;">Formative</td>
<td style="text-align: center;">Every 1-2 weeks</td>
<td style="text-align: center;">33%</td>
<td style="text-align: center;">28%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Quizzes</td>
<td style="text-align: center;">Summative</td>
<td style="text-align: center;">4/22, 5/13, 6/3</td>
<td style="text-align: center;">25%</td>
<td style="text-align: center;">25%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Project Labs</td>
<td style="text-align: center;">Formative</td>
<td style="text-align: center;">Every 2-3 weeks</td>
<td style="text-align: center;">25%</td>
<td style="text-align: center;">25%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Project Report</td>
<td style="text-align: center;">Summative</td>
<td style="text-align: center;">6/13</td>
<td style="text-align: center;">10%</td>
<td style="text-align: center;">10%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Exit tickets (Attendance)</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">Twice Weekly</td>
<td style="text-align: center;">5%</td>
<td style="text-align: center;">5%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Mid-Quarter Feedback</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">5/2</td>
<td style="text-align: center;">2%</td>
<td style="text-align: center;">2%</td>
</tr>
<tr class="even">
<td style="text-align: center;">613 Readings</td>
<td style="text-align: center;">Formative</td>
<td style="text-align: center;">Approx. every other week</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">5%</td>
</tr>
</tbody>
</table>
</section>
<section id="homework-grading" class="level3">
<h3>Homework grading</h3>
<p>No student has the same amount of time available to dedicate to homework. This class may not be a priority to you, you may be taking several other courses, or you may need to dedicate time to other activities. Homeworks are <strong>formative assessments</strong>, meaning its purpose is to help you learn and practice. To reduce the pressure on you to have perfect or complete homework, I have a very simple grading policy: <strong>Your homework will be given a check mark if you turn in 50% of the questions parts completed (whether the 50% is correct or wrong).</strong> I highly encourage you to stay up-to-date with the homeworks and put in as much effort as you can. This will be the most helpful work in this class!</p>
<p>If you turn in the homework on time, the TAs will give you feedback (on one or more complete problems). There is no penalty for turning in the homework late, but you will not get feedback on your work. Please make sure to check the solutions or go to office hours to assess your work.</p>
</section>
<section id="lab-grading" class="level3">
<h3>Lab grading</h3>
<p>While these are formative assignments, it is important to complete the whole lab and put in your best effort. Points will be deducted based on the rubric if it is clear that effort is not made or tasks are skipped.</p>
</section>
<section id="viewing-grades-in-sakai" class="level3">
<h3>Viewing Grades in Sakai</h3>
<p>Points you receive for graded activities will be posted to the Sakai Gradebook. Click on the Gradebook link on the left navigation to view your points.</p>
</section>
</section>
<section id="course-instructor-evaluations" class="level2">
<h2>Course &amp; Instructor Evaluations</h2>
<section id="ongoing-course-feedback" class="level3">
<h3>Ongoing Course Feedback</h3>
<p>Throughout the duration of the course, you are also welcome to informally and anonymously submit your feedback through this <a href="https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQlpLVUsyVUE3TU5ZNThJR0xCRDMyRjJOSC4u">Microsoft Form</a> or Class Exit Tickets. This form will be available on Sakai. Students can submit feedback at any time and this form will be reviewed regularly by me. Your responses will be anonymous unless you elect to leave your email address. If I have done anything to make you feel uncomfortable, please give me feedback so I can change my behavior. <strong>Ultimately, this class is for you, and my individual social identity/behavior should not inhibit your learning.</strong> Thank you for your help making BSTA 513/613 a more successful class! Examples of ongoing feedback are:</p>
<ul>
<li><p>Nicky talks a little fast during lecture time. May you speak slower?</p></li>
<li><p>During Office Hours, Dr. Wakim made a face when I asked a question. This face made me feel self-conscious about my question.</p></li>
<li><p>Dr. W asked me a question about my experience that made me feel like a monolith. Please do not assume I can speak on behalf of my social identity groups.</p></li>
<li><p>The in-class examples do not make me more interested in the material.</p></li>
</ul>
</section>
<section id="mid-quarter-feedback" class="level3">
<h3>Mid-quarter Feedback</h3>
<p>During the middle of the quarter, I will ask you to submit guided, anonymous feedback. Completion of feedback will be count towards your grade. To insure anonymity, I will ask you to sign a separate, written statement that you completed the feedback.</p>
</section>
<section id="final-course-feedback" class="level3">
<h3>Final Course Feedback</h3>
<p>At the conclusion of the course, you will be asked to complete a formal online review of the course and the instructor. Your feedback on this University evaluation is critical to improving future student learning in this course as well as providing metrics relevant to the instructor’s career advancement (or lack of). Since our class is on the smaller side, everyone’s participation is needed for feedback to be released.</p>
</section>
</section>
<section id="schedule" class="level2">
<h2>Schedule</h2>
<p><a href="/schedule1.qmd">Please refer to the Schedule page.</a> I will make changes to this schedule if we need more or less time on a concept. You do not need to read the corresponding chapters in the textbook for each class.</p>
</section>
<section id="how-to-succeed-in-this-course" class="level2">
<h2>How to succeed in this course</h2>
<p>Every professor has different expectations when assigning certain work or providing certain resources. I want to walk through each class resource and assignment so that you know what you can do to succeed in <em>this class</em>. For resources, I want you to optimize the opportunities to learn. For assignments, I want you to know the strategies that students can use to learn the most and prepare for future exams.</p>
<section id="resources" class="level3">
<h3>Resources</h3>
<table style="width:100%;">
<colgroup>
<col style="width: 4%" />
<col style="width: 38%" />
<col style="width: 57%" />
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Resource</strong></td>
<td style="text-align: left;"><strong>What is it?</strong></td>
<td style="text-align: left;"><strong>How do I use it?</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">Office Hours</td>
<td style="text-align: left;">Blocks of time a professor or TA dedicates for questions. The teaching staff will be located in a specific room. Several students may enter the space at a time and will ask specific or broad questions. If many students attend office hours, a queue will be created so that students can be served equally.</td>
<td style="text-align: left;">The main use of office hours is to ask questions about an assignment or lecture notes. You are welcome to sit and do homework in office hours. OH are also an informal way of meeting fellow students to collaborate with.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Lectures and lecture recordings</td>
<td style="text-align: left;">Time shared between the professor and students where the professor conveys important class material. Material discussed in lectures include concepts, calculations, code, and examples. Lectures are a mix of presentation of information, working through examples together, interactive activities, and in-class polls.</td>
<td style="text-align: left;">Students should attend lectures in person if possible. You should attempt to understand new material presented by following the presentation slides, taking notes on additional details that may conveyed verbally, and working through examples with the professor. Students are encouraged to ask questions when you don’t understand the material at any point in the lecture.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Textbooks</td>
<td style="text-align: left;">Written and published material that explains concepts, steps through calculations, provides examples, and provides practice problems. The listed textbooks is the basis for this course. While I am to cover all topics in class, the textbook provides alternative explanations and additional examples.</td>
<td style="text-align: left;">While coming to class having read the accompanying textbook chapters helps understanding during class, I do not expect students to have read it. I see the textbook as a good resource if you are struggling with a specific topic after class, in need of an example while working on homework, or want additional practice when studying for the exam.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Website</td>
<td style="text-align: left;">The course website is designed by me so that you have access to all the course materials in a more organized and flexible way. All resources delivered from me to you will be available on the website. Any assignments turned in will be through Sakai.</td>
<td style="text-align: left;">You can navigate through different course resources and information using the left-side tabs or top navigation bar. Course materials, like lecture notes, homework, data examples, and recordings, can be found under each week’s page under the schedule tab. You can also find the individual resources under the “Course Materials” tab on the left. Links to turn in assignments through Sakai will be given on the website. Please explore the tabs and get a sense of the organization.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Sakai</td>
<td style="text-align: left;">Sakai is a learning management system for higher ed. This is the university sanctioned LMS where we will submit assignments.</td>
<td style="text-align: left;">You will turn in assignments through Sakai under the “Submissions” tab. Generally, there will be a link to each assignment on the course website. You can also view your grades under “Gradebook” and links to Webex under “Webex.”</td>
</tr>
</tbody>
</table>
</section>
<section id="assignments" class="level3">
<h3>Assignments</h3>
<table style="width:99%;">
<colgroup>
<col style="width: 9%" />
<col style="width: 9%" />
<col style="width: 36%" />
<col style="width: 44%" />
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Assignment</strong></td>
<td style="text-align: center;"><strong>Type of assessment</strong></td>
<td style="text-align: left;"><strong>Before you submit/take it</strong></td>
<td style="text-align: left;"><strong>After it is graded</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">Homework</td>
<td style="text-align: center;">Formative</td>
<td style="text-align: left;"><ul>
<li><p>Work out each problem on your own as much as you can</p></li>
<li><p>Talk through problems with a peer</p></li>
<li><p>Go to Office Hours for help</p></li>
<li><p>Write down work that shows your thought process</p></li>
<li><p>Search your issue on Stack Exchange/Stack Overflow</p></li>
</ul></td>
<td style="text-align: left;"><ul>
<li><p>Review the solutions</p></li>
<li><p>Review your mistakes</p></li>
<li><p>For solutions that involve writing sentences, check with me or a TA if your answer fits the solution</p></li>
<li><p>Go to Office Hours to ask about your solutions</p></li>
</ul></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Quizzes</td>
<td style="text-align: center;">Summative</td>
<td style="text-align: left;"><ul>
<li><p>Identify and achieve learning objectives in each lecture</p></li>
<li><p>Understand why certain statistics tools are used for certain cases</p></li>
<li><p>Practice testing yourself and others on concepts</p></li>
<li><p>Come to Office Hours for help with specific problems or concepts</p></li>
</ul></td>
<td style="text-align: left;"><ul>
<li><p>Review the solutions</p></li>
<li><p>Review your mistakes</p></li>
<li><p>For solutions that involve writing sentences, check with me or a TA if your answer fits the solution</p></li>
<li><p>Go to Office Hours to ask about your solutions</p></li>
<li><p>Do not ask for a regrade unless you have viewed the solutions</p></li>
</ul></td>
</tr>
<tr class="even">
<td style="text-align: center;">Project Labs and Report</td>
<td style="text-align: center;">Formative and Summtive</td>
<td style="text-align: left;"><ul>
<li><p>Start the lab as early as possible</p></li>
<li><p>Work on R coding and check with classmates on work</p></li>
<li><p>Come to Office Hours for help with specific R work</p></li>
<li><p>For the report, compile your work from the labs, and decide what is important in the analysis.</p></li>
</ul></td>
<td style="text-align: left;"><ul>
<li><p>This will be graded at the end of the semester, so you will not have a chance to interact with my feedback as much</p></li>
<li><p>If you have questions about your grade, you may email me</p></li>
<li><p>Keep the project paper for future reference</p></li>
<li><p>You can add this project to your resume!</p></li>
</ul></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class Exit Tickets</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: left;"><ul>
<li><p>Bring appropriate electronic device to participate in polls</p></li>
<li><p>Complete the survey during the last 5 minutes of class or after class within 7 days</p></li>
</ul></td>
<td style="text-align: left;"><ul>
<li>Review muddiest and clearest points from the week</li>
</ul></td>
</tr>
</tbody>
</table>
<p>If you would like any other course resources explained in this format, please request it through the <a href="https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURDc2S1dGNTlTRVJVUFoyQUUzNFJMS0JXUi4u">Ongoing Course Feedback</a>. </p>
</section>
</section>
<section id="course-policies-and-resources" class="level2">
<h2>Course Policies and Resources</h2>
<section id="late-work-policy" class="level3">
<h3>Late Work Policy</h3>
<p>I encourage you to make your best effort to submit all assignments on time, but I understand circumstances arise that are beyond our control. Please see this <a href="https://myuni.swansea.ac.uk/academic-life/extenuating-circumstances/#how-can-the-university-support-me-and-what-should-i-do=is-expanded&amp;what-are-extenuating-circumstances=is-expanded&amp;what-isnt-an-extenuating-circumstance=is-expanded&amp;what-supporting-evidence-is-required=is-expanded&amp;who-should-i-contact-to-make-an-extenuating-circumstances-application=is-expanded&amp;who-will-make-a-decision-on-my-application=is-expanded">Swansea University’s page on extenuating circumstances</a> for some examples. Not all circumstances are covered here, so please reach out if you have questions. </p>
<ul>
<li><p>The class will end on March 22, 2024. <strong>All coursework is expected to be completed by then.</strong> If you have <em>extenuating circumstances</em>, and need additional time to complete class assignments, please contact me. Together, we will come up with a plan for completion and to sort out registrar logistics.</p></li>
<li><p>If you have extenuating circumstances that may jeopardize your ability to do work for several weeks, please contact me. We will come up with a plan to keep you on track in the course and prevent any delay in your education.</p></li>
<li><p>For homework, there is a due date posted, but you may turn in the assignment any time before the class ends. I will give you the check regardless of when you submit the assignment. <strong>However, if you would like feedback on the homework, you must turn it in on time OR email me asking for feedback for your late homework.</strong></p></li>
<li><p>For non-homework assignments, including labs, I ask you to email me directly. You can explain your circumstances and may ask me for an extension, but I won’t necessarily grant one.</p></li>
<li><p>For labs, you will have ONE no-questions-asked, 3-day extension. Please use this wisely! You just need to send me a quick email saying “I am using my no-questions-asked extension for Lab __.”</p></li>
<li><p>If you have a emergency involving your self, family, pet, friend, classmate, or anything/one deemed important to you, please do not worry about immediately contacting me. We can work something out after your emergency. If I contact you during an emergency, it is only because I am worried, and you do NOT need to respond until you are able. </p></li>
</ul>
</section>
<section id="regrade-policy" class="level3">
<h3>Regrade Policy</h3>
<p>If you think a question was incorrectly graded, first compare your answer to the answer key. If you believe a re-grade would be appropriate, write an email to me containing the question and a short explanation as to why the question(s) was/were incorrectly graded. Deadline: One week after assignments were returned to class (late requests will not be considered).</p>
</section>
<section id="attendance-policy" class="level3">
<h3>Attendance Policy</h3>
<p>You are expected to attend class, participate in-class polls, and complete the exit ticket. For students who miss class or need a review, I will make video and audio recordings of lectures available. There are no guarantees against technical or other challenges for the recording availability or quality. For students who are unable to attend the class in-person and synchronously, <strong>viewing the recording within 7 days</strong> is acceptable. This is meant to keep you on track within the course and prevent a pile up of material. Make sure to complete the exit ticket to demonstrate attendance.</p>
</section>
<section id="plagiarism-and-attribution" class="level3">
<h3>Plagiarism and Attribution</h3>
<p>Please note that this section has been motivated by <a href="https://dmice.ohsu.edu/bedricks/courses/bmi525/policies.html">Dr. Steven Bedrick’s Course Policies and Grading site</a> for BMI 525. (Note that this is a good example of informal attribution of someone else’s work.)</p>
<p>In this class, it is easy to use ChatGPT or other AI tools to solve your homework for you. Many problems follow a basic structure that is especially easy for ChatGPT to solve. In this class, you may use ChatGPT to help with your homework. You may even ask for direct answers. However, there are a few things I do not want you to do:</p>
<ul>
<li><p><strong>Do not copy ChatGPT’s answer directly into your homework.</strong> Your homework is graded for full credit if you turn it in, in any state, so turning in ChatGPT’s answers is unacceptable. I rather see half-written answers that show what you’re thinking than see a correct answer from ChatGPT.</p></li>
<li><p><strong>Do not stop once ChatGPT answered a question.</strong> If it gives an explanation, interact with it! Make sure you understand the thought process of ChatGPT. Try writing out the process to help cement it in your head. Check the answer with what we learn in class.</p></li>
<li><p><strong>Do not use ChatGPT on our quizzes!</strong> Hence, you need to really understand how to solve these problems even if you use ChatGPT on the homework.</p></li>
</ul>
<p>At the end of the day, ChatGPT is a resource that will be available to you in a job and outside of school. Thus, we should use it as a tool in school as well! Let me know if ChatGPT helped you understand something! I would love to incorporate it into future classes!</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can think of this class as assembling a toolbox. When a handyperson starts working for the first time, they need to buy their tools. For their first few jobs, they might need help finding their tools, or remembering which tool is best used for what action. Eventually, they get to know their tools well, and using them appropriately becomes second nature.</p>
<p><strong>For now, ChatGPT can help us find and use our tools, but we need to work towards using them as second nature!</strong></p>
</div>
</div>
</section>
</section>
<section id="course-expectations" class="level2">
<h2>Course Expectations</h2>
<section id="instructor-expectations" class="level3">
<h3>Instructor Expectations</h3>
<p><u><em>Commitment to your learning and your success<br />
</em></u>I believe that everyone has the ability to be successful in this course and I have put a lot of effort into designing the course in a way that maximizes your learning to ensure your success. Please talk to me before or after class or stop by my office if there is anything you want to discuss or about which you are unclear. I want to be supportive of your learning and growth.</p>
<p><u><em>Inclusive &amp; supportive learning community</em></u><br />
I believe that learning happens best when we all learn together, as a community. This means creating a space characterized by generous listening, civility, humility, patience, and hospitality. I will attempt to promote a safe climate where we examine content from multiple cultural perspectives, and I will strive to create and maintain a classroom atmosphere in which you feel free to both listen to others and express your views and ask questions to increase your learning.</p>
<p><u><em>Openness to feedback</em></u><br />
I appreciate straightforward feedback from you regarding how well the class is meeting your needs. Let me know if material is not clear or when its relevance to the student learning outcomes for the course is not apparent. In particular, let me know if you identify bias or stereotyping in my teaching materials as I will seek to continuously improve. Please also let me know if there’s an aspect of the class you find particularly interesting, helpful, or enjoyable!</p>
<p><u><em>Responsiveness<br />
</em></u>I will monitor email as well as the discussion board daily and try respond to all messages within 24 hours Monday-Friday.</p>
<p><u><em>Clear guidelines and prompt feedback on assignments</em></u><br />
I will provide clear instructions for all assignments, and a grading rubric when applicable. I will provide detailed feedback on your submissions and will update grades promptly in Sakai.</p>
</section>
<section id="student-expectations-and-resources" class="level3">
<h3>Student Expectations and Resources</h3>
<p><u><em>Attend class</em></u><strong><br />
</strong>You are expected to attend all scheduled class meetings synchronously or watch the recording within 7 days. Attendance is taken through exit tickets. If you have issues accessing the poll on a specific day, please let me know. </p>
<p><u><em>Participate<strong><br />
</strong></em></u>I encourage you to participate actively in class and online discussions. I will expect all students, and all instructors, to be respectful of each other’s contributions, whether I agree with them or not. Professional interactions are expected.</p>
<p><u><em>Build rapport</em></u><br />
If you find that you have any trouble keeping up with assignments or other aspects of the course, make sure you let me know as early as possible. As you will find, building rapport and effective relationships are key to becoming an effective professional. Make sure that you are proactive in informing me when difficulties arise during the quarter so that I can help you find a solution.</p>
<p><u><em>Complete assignments</em></u><br />
All assignments for this course will be submitted electronically through Sakai unless otherwise instructed.  I encourage you to make your best effort to submit all assignments on time, but I understand that sometimes circumstances arise that are beyond our control. If you need an extension, please contact me in congruence with the Late Policy.</p>
<p><u><em>Seek help if you need it</em></u><strong><br />
</strong>I believe it is important to support the physical and emotional well‐being of my students. If you are experiencing physical or mental health issues, I encourage you to use the resources on campus such as those listed below. If you have a health issue that is affecting your performance or participation in the course, and/or if you need help connecting with these resources, please contact me.</p>
<ul>
<li><p>Student Health and Wellness Center (SHW), <a href="https://www.ohsu.edu/education/student-health-and-wellness">Website</a>, 503-494-8665 (OHSU Students only)</p></li>
<li><p>Student Health and Counseling (SHAC), <a href="https://www.pdx.edu/health-counseling/">Website</a>, 503-725-2800</p></li>
</ul>
<p><u><em>Inform your instructor of any accommodations needed</em></u><br />
You should speak with or email me before or during the first week of classes regarding any special needs. Students seeking academic accommodations should register with the appropriate service under the School policies below.</p>
<p>Some religious holidays may occur on regularly scheduled class days. Because available class hours are so limited in number, we will have to hold class on all such days. Class video recordings will be available and you are encouraged to engage with the material outside of the regular class time. You are also encouraged to come to office hours with questions from the session.</p>
<p><u><em>Commit to integrity</em></u><strong><br />
</strong>As a student in this course (and at PSU or OHSU) you are expected to maintain high degrees of professionalism, commitment to active learning and participation in this class and also integrity in your behavior in and out of the classroom.</p>
<p>Cheating and other forms of academic misconduct will not be tolerated in this course and will be dealt with firmly. Student academic misconduct refers to behavior that includes plagiarism, cheating on assignments, fabrication of data, falsification of records or official documents, intentional misuse of equipment or materials (including library materials), or aiding and abetting the perpetration of such acts. Preparation of exams, assigned on an individual basis, must represent each student’s own individual effort. When used, resource materials should be cited in conventional reference format.</p>
</section>
</section>
<section id="course-communications" class="level2">
<h2>Course Communications</h2>
<p><strong>Sakai/Slack announcements<br />
</strong>For important/urgent matters, I will communicate with you using announcements via Sakai that will be delivered to your OHSU Email account as well as displayed in the Sakai course site Announcements section. I will copy these announcements in Slack if they do not involve changes to the schedule. Unfortunately, there are certain announcements that OHSU requires I initiate behind the firewall.</p>
<p><strong>General course questions<br />
</strong>It is normal to have many questions about things that relate to the course, such as clarification about assignments, course materials, or assessments. Please post these on our Slack Workspace. Please use the channels that I created for questions. You are encouraged to give answers and help each other. I will monitor these threads, so I will endorse or correct responses as needed. Please give me 24 hours to respond to questions within Monday-Friday. Work-life balance is important for me as well, so I will try to respond as quickly as I can within my healthy limits. </p>
<p><strong>E-mail</strong><br />
E-mail should be used only for messages that are private in nature. Please send private messages to my OHSU email address (wakim@ohsu.edu). <strong>Messages sent through Sakai Inbox will not be answered.</strong> Do not send messages asking general information about the class; please post those on Slack instead.</p>
</section>
<section id="further-student-resources" class="level2">
<h2>Further Student Resources</h2>
<section id="sph-writing-lab" class="level3">
<h3>SPH Writing Lab</h3>
<p>The School of Public Health Writing Support serves graduate students (master’s and PhD) in SPH, offering help on all professional writing tasks, including class papers, dissertations, job application documents, personal statements, and grant applications, to name a few. Leslie Bienen, MFA, DVM offers one-on-one writing support and other workshops. Appointments are virtual for the time being. You can make an appointment by contacting <a href="mailto:writingsupportsph@pdx.edu">writingsupportsph@pdx.edu</a> or making an appointment through <a href="https://calendly.com/writingsupportsph/writing-meeting">Calendly</a>.</p>
</section>
<section id="grammarly-subscription" class="level3">
<h3>Grammarly Subscription</h3>
<p>The School of Public Health students have access to a subscription version of Grammarly. While Grammarly cannot improve the argument and flow of your work, it can help with spelling, grammar, and sentence structure. If you are interested in this tool, please add your name to this email <a href="https://docs.google.com/forms/d/1IQWFsARrTJlasK2a5JTonR4ygr8MxqIzbh_bAxKmWWI/edit?ts=614ce07a">form</a> and they will get you added to the subscription. Be sure to use your PSU login credentials to access the form.</p>
</section>
<section id="student-wellness" class="level3">
<h3>Student Wellness</h3>
<p>I am committed to supporting the physical and emotional well-being of my students. Both PSU and OHSU have designated centers for student health. For OHSU, students can visit the <a href="https://www.ohsu.edu/education/behavioral-health">Behavioral Health site</a>, where you can find more information including the number to make an appointment. <strong>All student visits are free.</strong> OHSU students also have access to PSU’s <a href="https://www.pdx.edu/health-counseling/counseling">Counseling Services</a> through the school’s Student Health &amp; Counseling. Information on additional student resources for OHSU students are available on the OHSU <a href="https://ohsu-psu-sph.org/health_and_wellness/">Health and Wellness Resource page</a>. </p>
</section>
<section id="support-for-food-insecurity" class="level3">
<h3>Support for Food Insecurity</h3>
<p>Students across the country experience food insecurity at alarming rates. OHSU and PSU both provide a list of resources to help combat food insecurity. Of note, the Committee to Improve Student Food Security (CISFS) at PSU provides a <a href="https://www.pdx.edu/student-access-center/free-food-market">Free Food Market</a> on the second Monday of each month. OHSU also provides <a href="https://o2.ohsu.edu/student-central/health-wellness/student-food-resources/snap.cfm">SNAP Enrollment Assistance</a>. The <a href="https://oregonhunger.org/snap-for-students/">Supplemental Nutrition Assistance Program (SNAP)</a> allocates money towards food for individuals below a certain income level. If you make less than $2,430 monthly, you may wish to enroll.</p>
</section>
<section id="support-for-students-with-children" class="level3">
<h3>Support for Students with Children</h3>
<p>Students who have children can use the PSU resource: <a href="https://www.pdx.edu/students-with-children/">Resource Center for Students with Children</a>. Resources are mostly focused on students with younger children. There are several great resources available, including: family-friendly study spaces, new baby starter packs, free kids clothing, and further information on financial resources for childcare.</p>
</section>
</section>
<section id="school-policies-and-resources" class="level2">
<h2>School Policies and Resources</h2>
<section id="school-of-public-health-handbook" class="level3">
<h3>School of Public Health Handbook</h3>
<p>All students are responsible for following the policies and expectations outlined in the student handbook for their program of study. Students are responsible for their own academic work and are expected to have read and practice principles of academic honesty, <a href="https://ohsu-psu-sph.org/current-graduate-students/policies-procedures/">as presented in the handbook</a>.</p>
</section>
<section id="student-access-accommodations" class="level3">
<h3>Student Access &amp; Accommodations</h3>
<p>The School of Public Health values diversity and inclusion; we are committed to fostering mutual respect and full participation for all students. My goal is to create a learning environment that is equitable, usable, inclusive, and welcoming. If any aspects of instruction or course design result in barriers to your inclusion or learning, please notify me. </p>
<ul>
<li><p><strong>If you are already registered with disability services</strong> at either OHSU or PSU and you are taking a course at the opposite institution, you need to <strong>contact the office you’re registered with to transfer your accommodations</strong>.</p></li>
<li><p><strong>If you are not already registered with a disability services office</strong>, and you have, or think you may have, a disability that may affect your work in this class, and feel you need accommodations, use the following table for guidance about which office to contact to initiate accommodations.</p></li>
</ul>
<p><strong>Resource Table</strong></p>
<table>
<tbody>
<tr class="odd">
<td><strong><em>Enrollment University and Standing</em></strong></td>
<td><strong><em>Where to Seek Accommodations</em></strong></td>
</tr>
<tr class="even">
<td><em>Undergraduate School of Public Health major</em></td>
<td><p><a href="http://www.pdx.edu/drc" title="PSU’s Disability Resource Center"><em>PSU’s Disability Resource Center</em></a></p>
<ul>
<li><p><em>503-725-4150</em></p></li>
<li><p><em>Smith Memorial Student Union, Room 116</em></p></li>
<li><p><a href="mailto:drc@pdx.edu"><em>drc@pdx.edu</em></a></p></li>
</ul></td>
</tr>
<tr class="odd">
<td>All PSU-registering Dual Degree (MSW/MPH and MURP/MPH) Graduate School of Public Health Majors and all PSU-registering PhD students admitted prior to fall 2016.</td>
<td><p><em>PSU’s Disability Resource Center</em></p>
<ul>
<li><p><em>503-725-4150</em></p></li>
<li><p><em>Smith Memorial Student Union, Room 116</em></p></li>
<li><p><a href="mailto:drc@pdx.edu"><em>drc@pdx.edu</em></a></p></li>
<li><p><a href="http://www.pdx.edu/drc"><em>www.pdx.edu/drc</em></a></p></li>
</ul></td>
</tr>
<tr class="even">
<td><em>Graduate School of Public Health major (irrespective of institution at which you register)</em></td>
<td><p><em>OHSU’s Office for Student Access</em></p>
<p><em>(503) 494-0082</em></p>
<p><a href="mailto:StudentAccess@OHSU.edu"><em>StudentAccess@OHSU.edu</em></a></p>
<p><em>OHSU Auditorium Building 330</em></p></td>
</tr>
<tr class="odd">
<td><em>Non-SPH major, PSU-enrolled student</em></td>
<td><p><em>PSU’s Disability Resource Center</em></p>
<p><em>503-725-4150</em></p>
<p><em>Smith Memorial Student Union, Room 116</em></p>
<p><a href="mailto:drc@pdx.edu"><em>drc@pdx.edu</em></a></p>
<p><a href="http://www.pdx.edu/drc"><em>www.pdx.edu/drc</em></a></p></td>
</tr>
<tr class="even">
<td><em>Non-SPH major, OHSU-enrolled student</em></td>
<td><p><em>OHSU’s Office for Student Access</em></p>
<p><em>(503) 494-0082</em></p>
<p><a href="mailto:StudentAccess@OHSU.edu"><em>StudentAccess@OHSU.edu</em></a></p>
<p><em>OHSU Auditorium Building 330</em></p></td>
</tr>
</tbody>
</table>
<p> </p>
<p>For more information related accessibility and accommodations, please see the “Statement Regarding Students with Disabilities” within the Institutional Policies section of this syllabus.</p>
</section>
<section id="title-ix" class="level3">
<h3>Title IX</h3>
<p><em>The School of Public Health is committed to providing an environment free of all forms of prohibited discrimination and discriminatory harassment. The School of Public Health students who have questions about an incident related to Title IX are welcome to contact either the OHSU or PSU’s Title IX Coordinator and they will direct you to the appropriate resource or office. Title IX pertains to any form of sex/gender discrimination, discriminatory harassment, sexual harassment or sexual violence.</em></p>
<ul>
<li><p><em>PSU’s Title IX Coordinator is Julie Caron, she may be reached at <a href="mailto:titleixccordinator@pdx.edu">titleixccordinator@pdx.edu</a> or 503-725-4410. Julie’s office is located at <a href="https://www.google.com/maps/search/1600+SW+4th+Ave?entry=gmail&amp;source=g">1600 SW 4th Ave</a>, In the Richard and Maureen Neuberger Center RMNC - Suite 830.</em></p></li>
<li><p>The OHSU Title IX Coordinator’s may be reachedat 503-494-0258 or <a href="mailto:titleix@ohsu.edu">titleix@ohsu.edu</a> and is located at 2525 SW 3rd St.</p></li>
</ul>
<p><em>Please note that faculty and the Title IX Coordinators will keep the information you disclose private but are not confidential. If you would like to speak with a confidential advocate, who will not disclose the information to a university official without your written consent, you may contact an advocate at PSU or OHSU.</em></p>
<ul>
<li><a href="https://www.pdx.edu/womens-resource-center/schedule-confidential-advocacy-appointment"><em>PSU’s confidential advocates</em></a> <em>are available in Women’s Resource Center (serving all genders) in Smith Student Memorial Union 479. You may schedule an appointment by (503-725-5672) or schedule on line at <a href="https://psuwrc.youcanbook.me/">https://psuwrc.youcanbook.me</a><u>.</u> For more information about resources at PSU, please see PSU’s <a href="https://www.pdx.edu/sexual-assault/">Response to Sexual Misconduct website.</a></em></li>
<li>OHSU’s advocates are available through the Confidential Advocacy Program (CAP) at 833-495-CAPS (2277) or by email <a href="mailto:CAPsupport@ohsu.edu">CAPsupport@ohsu.edu</a>, but please note, email is not a secure form of communication. Also visit <a href="http://www.ohsu.edu/CAP">www.ohsu.edu/CAP</a>.</li>
</ul>
<p><em>At OHSU, if you encounter any harassment, or discrimination based on race, color, religion, age, national origin or ancestry, veteran or military status, sex, marital status, pregnancy or parenting status, sexual orientation, gender identity or expression, disability or any other protected status, please contact the Affirmative Action and Equal Opportunity (AAEO) Department at 503-494-5148 or <a href="mailto:aaeo@ohsu.edu">aaeo@ohsu.edu</a>.</em></p>
<p><em>At PSU, you may contact the Office of Equity and Compliance if you experience any form of discrimination or discriminatory harassment as listed above at <a href="mailto:equityandcompliance@pdx.edu">equityandcompliance@pdx.edu</a> or by calling 503-725-5919.</em></p>
</section>
<section id="technical-support" class="level3">
<h3>Technical Support</h3>
<p>The <a href="http://www.ohsu.edu/xd/about/services/information-technology/contact-us/index.cfm" title="OHSU ITG Help Desk">OHSU ITG Help Desk</a> is available to assist students with email account or network account access issues between 6 a.m. and 6 p.m., Monday through Friday at 503-494-2222. For technical support in using the Sakai Course Management System, please contact the <a href="https://www.ohsu.edu/xd/education/teaching-and-learning-center/tools-and-services/sakai.cfm" title="Sakai Help Desk">Sakai Help Desk </a>at 877-972-5249 or email us at <a href="mailto:sakai@ohsu.edu">sakai@ohsu.edu</a></p>
</section>
</section>
<section id="ohsu-competencies" class="level2">
<h2>OHSU Competencies</h2>
<section id="list-of-ohsu-graduation-core-competencies" class="level4">
<h4>List of OHSU Graduation Core Competencies</h4>
<ul>
<li><p>Professional Knowledge and Skills</p></li>
<li><p>Professionalism</p></li>
<li><p>Information Literacy</p></li>
<li><p>Communication</p></li>
<li><p>Teamwork</p></li>
<li><p>Community Engagement, Social Justice and Equity</p></li>
<li><p>Patient Centered Care</p></li>
</ul>
<p><strong>To access a descriptive list of OHSU Graducation Core Competencies:</strong> <a href="https://www.ohsu.edu/sites/default/files/2020-11/OHSU%20Graduation%20Core%20Competencies%202020.pdf" title="OHSU Graduation Core Competencies">OHSU Graduation Core Competencies</a></p>
</section>
</section>
<section id="institutional-policies-and-resources" class="level2">
<h2>Institutional Policies and Resources</h2>
<section id="statement-regarding-students-with-disabilities" class="level3">
<h3>Statement Regarding Students with Disabilities</h3>
<p>OHSU is committed to inclusive and accessible learning environments in compliance with federal and state law. If you have a disability or think you may have a disability (mental health, attention-related, learning, vision, hearing, physical or health impacts) contact the Office for Student Access at (503) 494-0082 or <a href="mailto:studentaccess@ohsu.edu">OHSU Student Access</a> to have a confidential conversation about academic accommodations. Information is also available at <a href="http://www.ohsu.edu/student-access" title="Student Access Website">Student Access Website</a>. Because accommodations may take time to implement and cannot be applied retroactively, it is important to have this discussion as soon as possible.</p>
<p>Portland State students also have similar resources available via the PSU Disability Resource Center (website <a href="http://www.pdx.edu/drc" class="uri">http://www.pdx.edu/drc</a> ). Please contact the DRC at tel. (503) 725-4150 or email at <a href="mailto:drc@pdx.edu">drc@pdx.edu</a></p>
</section>
<section id="student-evaluation-of-courses" class="level3">
<h3>Student Evaluation of Courses</h3>
<p>Course evaluation results are extremely important and used to help improve courses and the learning experience of future students. Responses will always remain anonymous and will only be available to instructors after grades have been posted. The results of scaled questions and comments go to both the instructor and their unit head/supervisor. Refer to Student Evaluation of Courses and Instructional Effectiveness, *<a href="https://o2.ohsu.edu/policies-and-compliance/ohsu-policy-manual/chapter-2-student-affairs/ohsu-policy-02-50-035.cfm" title="Student Evaluationvof Courses Policy">Policy No. 02-50-035</a>.</p>
<p>*To access the OHSU Student Evaluation of Courses and Instructional Effectiveness Policy, you must log into the <a href="https://o2.ohsu.edu/" title="OHSU O2 website">OHSU O2 website</a>.</p>
</section>
<section id="copyright-information" class="level3">
<h3>Copyright Information</h3>
<p>Copyright laws and fair use policies protect the rights of those who have produced the material. The copy in this course has been provided for private study, scholarship, or research. Other uses may require permission from the copyright holder. The user of this work is responsible for adhering to copyright law of the U.S. (Title 17, U.S. Code). To help you familiarize yourself with copyright and fair use policies, the University encourages you to visit its <a href="https://www.ohsu.edu/xd/education/library/services/copyright/" title="Copyright Web Page">Copyright Web Page</a></p>
<p>Sakai course web sites contain material protected by copyrights held by the instructor, other individuals or institutions. Such material is used for educational purposes in accord with copyright law and/or with permission given by the owners of the original material. You may download one copy of the materials on any single computer for non-commercial, personal, or educational purposes only, provided that you (1) do not modify it, (2) use it only for the duration of this course, and (3) include both this notice and any copyright notice originally included with the material. Beyond this use, no material from the course web site may be copied, reproduced, re-published, uploaded, posted, transmitted, or distributed in any way without the permission of the original copyright holder. The instructor assumes no responsibility for individuals who improperly use copyrighted material placed on the web site.</p>
</section>
<section id="syllabi-changes-and-retention" class="level3">
<h3>Syllabi Changes and Retention</h3>
<p>Syllabi are considered to be a learning agreement between students and the faculty of record. Information contained in syllabi, other than the minimum requirements, may be subject to change as deemed appropriate by the faculty of record in concurrence with the academic program and the Office of the Provost. Refer to the *<a href="https://o2.ohsu.edu/policies-and-compliance/ohsu-policy-manual/chapter-2-student-affairs/ohsu-policy-02-50-050.cfm" title="Course Syllabi Policy, 02-50-050.">Course Syllabi Policy, 02-50-050.</a></p>
<p>*To access the OHSU Course Syllabus Policy, you must log into the <a href="#0" title="OHSU O2 website">OHSU O2 website</a>.</p>
</section>
<section id="commitment-to-diversity-inclusion" class="level3">
<h3>Commitment to Diversity &amp; Inclusion</h3>
<p>OHSU is committed to creating and fostering a learning and working environment based on open communication and mutual respect. If you encounter sexual harassment, sexual misconduct, sexual assault, or discrimination based on race, color, religion, age, national origin, veteran’s status, ancestry, sex, marital status, pregnancy or parenting status, sexual orientation, gender identity, disability or any other protected status please contact the Affirmative Action and Equal Opportunity Department at 503-494-5148 or <a href="mailto:aaeo@ohsu.edu">aaeo@ohsu.edu</a>. Inquiries about Title IX compliance or sex/gender discrimination and harassment may be directed to the OHSU Title IX Coordinator at 503-494-0258 or <a href="mailto:titleix@ohsu.edu.">titleix@ohsu.edu.</a></p>
</section>
<section id="modified-operations-policy-01-40-010" class="level3">
<h3>Modified Operations, Policy 01-40-010</h3>
<p><strong>Portland Campus:  Marquam Hill and South Waterfront</strong></p>
<p>Students should review O2 or call <a href="https://www.ohsu.edu/xd/about/visiting/weather/" title="OHSU’s weather alert">OHSU’s weather alert</a> line at 503-494-9021 for the most up-to-date information on OHSU-wide modified operations which include but are not limited to delays or closures for inclement weather.</p>
<p><strong><em>If your home institution is not on the Portland campus (Marquam Hill or South Waterfront, contact your home institution for more information.</em></strong></p>
</section>
<section id="ohsu-resources-available-to-students" class="level3">
<h3>OHSU Resources Available to Students*:</h3>
<p><strong>Remote Learning Resources<br />
</strong>The <a href="https://o2.ohsu.edu/student-central/transforming-learning.cfm" title="Remote Learning webpage on O2">Remote Learning webpage on O2</a> contains concise, practical resources, and strategies for students that need to quickly transition to a fully remote instructional format.</p>
<p><strong>Registrar’s Office</strong><br />
Mackenzie Hall, Rm. 1120<br />
503-494-7800; <a href="mailto:regohsu@ohsu.edu">Email the Registrar</a></p>
<p><strong>Student Registration Information:</strong> <br />
<a href="http://www.ohsu.edu/xd/education/student-services/registrar/registration-information/index.cfm" title="Student Registration">To Register for Classes</a></p>
<p><strong>OHSU ITG Help Desk</strong><br />
Regular staff hours are 6 a.m. to 6 p.m., Monday through Friday, but phones are answered seven days a week, 24 hours a day. Call 503 494-2222.</p>
<p><strong>Teaching and Learning Center</strong><br />
Academic Support Counseling and Sakai Course Management System, please contact the TLC Help Desk at 877-972-5249 or email <a href="mailto:sakai@ohsu.edu">TLC Help Desk</a></p>
<p><strong>Student Academic Support Services<br />
</strong>For resources on improving student’s study strategies, time management, motivation, test-taking skills and more, Please access the <a href="https://sakai.ohsu.edu/portal/site/Student_Support" title="Student Academic Support">Student Academic Support Services Sakai page</a>. For one-on-one appointments or to arrange a workshop for students, please contact <a href="mailto:learningsupport@ohsu.edu">Emily Hillhouse</a>.</p>
<p><strong>Confidential Advocacy Program<br />
</strong>Support for OHSU employees, students, and volunteers who have experienced any form of sexual misconduct, including sexual harassment, sexual assault, intimate-partner violence, stalking, relationship/dating violence, and other forms — regardless of when or where it took place. <a href="https://www.ohsu.edu/confidential-advocacy-program" title="CAP">Contact Us.</a></p>
<p><strong>Concourse Syllabus Management<br />
</strong>For help with accessing your Concourse Syllabus:  Please contact the Sakai help Desk for all other Concourse inquiries please visit the <a href="https://sakai.ohsu.edu/portal/site/concourse-syllabus-support" title="Concourse Support - Sakai">Concourse Support - Sakai</a> or please contact the Mark Rivera at <a href="mailto:rivermar@ohsu.edu">rivermar@ohsu.edu </a>or call 503-494-0934</p>
<p><strong>Public Safety<br />
<a href="https://www.ohsu.edu/xd/about/services/public-safety/" title="https://www.ohsu.edu/xd/about/services/public-safety/">OHSU Public Safety-Portland Campus (Marquam Hill and South Waterfront)</a></strong></p>
<ul>
<li><p>Emergency on Campus: 503-494-4444 (Portland)</p></li>
<li><p>Non-emergency: 503-494-7744; <a href="mailto:pubsafe@ohsu.edu">Contact Public Safety</a></p></li>
</ul>
<p><strong>Student Health &amp; Wellness Center</strong> <br />
Baird Hall, Rm. 18 (Primary Care) and Rm. 6 (Behavioral Health)<br />
503-494-8665; For urgent care after hours, 503-494-8311 and ask for the Nurse on call.<br />
<a href="mailto:SHW@ohsu.edu">Wellness Center Information</a>  <br />
<a href="http://www.ohsu.edu/xd/education/student-services/joseph-trainer-health-wellness-center/" title="Wellness Center Website">Wellness Center Website</a></p>
<p><strong><em>If your home institution is not on the Portland campus, contact your home institution student support services for more information.</em></strong></p>
<p><strong>Ombudsman Office</strong><br />
Gaines Hall, Rm. 117<br />
707 SW Gaines Street, Portland, OR 97239<br />
503-494-5397; <a href="mailto:graybill@ohsu.edu">Contact Ombudsman</a>; <a href="https://www.ohsu.edu/xd/about/services/ombudsman/" title="Ombudsman Website">Ombudsman Website</a></p>
<p><strong>Library: Biomedical Information Communication Center</strong><br />
<a href="http://www.ohsu.edu/xd/education/library/about/hours.cfm" title="BICC Library Hours of Operation">BICC Library Hours of Operation</a></p>
</section>
<section id="privacy-while-learning" class="level3">
<h3>Privacy While Learning</h3>
<p>Students may be asked to take classes remotely through videoconferencing software like WebEx. Some of these remote classes will be recorded. Any recording will capture the presenter’s audio, video, and computer screen. Student video and audio will be recorded if and when you unmute your audio and share your video during the recorded sessions. These recordings will not be shared with or accessible to the public without prior written consent. </p>
</section>
<section id="student-central" class="level3">
<h3>Student Central</h3>
<p>Key information for students across OHSU’s Schools of Dentistry, Medicine, Nursing, the OHSU-PSU School of Public Health and the College of Pharmacy. <a href="https://o2.ohsu.edu/student-central/index.cfm" title="Student Central">Student Central</a> helps you find out more about student services, resources, policies and technology.</p>
<div id="quarto-navigation-envelope" class="hidden">
<p><span class="hidden" data-render-id="quarto-int-sidebar-title">Categorical Data Analysis</span> <span class="hidden" data-render-id="quarto-int-navbar-title">Categorical Data Analysis</span> <span class="hidden" data-render-id="quarto-int-next">Schedule</span> <span class="hidden" data-render-id="quarto-int-prev">Instructors</span> <span class="hidden" data-render-id="quarto-int-sidebar:/index.html">Home</span> <span class="hidden" data-render-id="quarto-int-sidebar:quarto-sidebar-section-1">Course Info</span> <span class="hidden" data-render-id="quarto-int-sidebar:/instructors.html">Instructors</span> <span class="hidden" data-render-id="quarto-int-sidebar:/syllabus.html">Syllabus</span> <span class="hidden" data-render-id="quarto-int-sidebar:/schedule.html">Schedule</span> <span class="hidden" data-render-id="quarto-int-sidebar:/resources.html">Resources</span> <span class="hidden" data-render-id="quarto-int-sidebar:/quizzes.html">Quizzes</span> <span class="hidden" data-render-id="quarto-int-sidebar:quarto-sidebar-section-2">Course Materials</span> <span class="hidden" data-render-id="quarto-int-sidebar:/weeks.html">Weekly Pages</span> <span class="hidden" data-render-id="quarto-int-sidebar:/lessons.html">Lessons</span> <span class="hidden" data-render-id="quarto-int-sidebar:/homeworks.html">Homework</span> <span class="hidden" data-render-id="quarto-int-sidebar:/project.html">Project</span> <span class="hidden" data-render-id="quarto-int-sidebar:/readings.html">613 Readings</span> <span class="hidden" data-render-id="quarto-int-navbar:Syllabus">Syllabus</span> <span class="hidden" data-render-id="quarto-int-navbar:/syllabus.html">/syllabus.html</span> <span class="hidden" data-render-id="quarto-int-navbar:Schedule">Schedule</span> <span class="hidden" data-render-id="quarto-int-navbar:/schedule.html">/schedule.html</span> <span class="hidden" data-render-id="quarto-int-navbar:Homework">Homework</span> <span class="hidden" data-render-id="quarto-int-navbar:/homeworks.html">/homeworks.html</span> <span class="hidden" data-render-id="quarto-int-navbar:Projects">Projects</span> <span class="hidden" data-render-id="quarto-int-navbar:/project.html">/project.html</span> <span class="hidden" data-render-id="quarto-breadcrumbs-33fac1d65895b1255332325e7b1cf507">Course Info</span> <span class="hidden" data-render-id="quarto-breadcrumbs-2edb33b3dac532a435b29ee9eabacaa5">Syllabus</span></p>
</div>
<div id="quarto-meta-markdown" class="hidden">
<p><span class="hidden" data-render-id="quarto-metatitle">Categorical Data Analysis - BSTA 513/613 Syllabus</span> <span class="hidden" data-render-id="quarto-twittercardtitle">Categorical Data Analysis - BSTA 513/613 Syllabus</span> <span class="hidden" data-render-id="quarto-ogcardtitle">Categorical Data Analysis - BSTA 513/613 Syllabus</span> <span class="hidden" data-render-id="quarto-metasitename">Categorical Data Analysis</span> <span class="hidden" data-render-id="quarto-twittercarddesc"></span> <span class="hidden" data-render-id="quarto-ogcardddesc"></span></p>
</div>
</section>
</section>

</main> <!-- /main -->
<script id = "quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
</div> <!-- /content -->

</body>

</html>