---
title: "Homework 1"
subtitle: "BSTA 512/612"
author: "Your name here - update this!!!!"
description: "Due: Thursday January 25, 2023"
date-modified: "1/16/2024"
date: "1/25/2024"
format: 
  html: 
    link-external-newwindow: true
    toc: true
    embed-resources: true
    self-contained: true
  pdf: default 
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 2, fig.width = 4)

library(tidyverse)
library(rstatix)
library(broom)
library(gt)
library(janitor)
library(here)

```

::: callout-important
**This page is no longer under construction. You may start this homework! (1/16/24)**
:::

## Directions

-   [Download the `.qmd` file here.](https://github.com/nwakim/W2024_BSTA_512/blob/main/homework/HW1.qmd)

-   You will need to download the datasets. Use [this link to download](https://ohsuitg-my.sharepoint.com/:f:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/W2024_BSTA_512_612/Student_files/Data/Homework/HW1?csf=1&web=1&e=fPDqYu) the HW1 datasets needed in this assignment. If you do not want to make changes to the paths set in this document, then make sure the files are stored in a folder named "data" that is housed in the same location as your HW1 `.qmd` file.

-   Please upload your homework to Sakai. **Upload both your `.qmd` code file and the rendered `.html` file**

-   For each question, make sure to include all code and resulting output in the html file to support your answers

-   Show the work of your calculations using R code within a code chunk. Make sure that both your code and output are visible in the rendered html file. This is the default setting.

-   Write all answers in complete sentences as if communicating the results to a collaborator.

::: callout-tip
It is a good idea to try rendering your document from time to time as you go along! Note that rendering automatically saves your `.qmd` file and rendering frequently helps you catch your errors more quickly.
:::

## Questions

