---
title: "Week 1"
description: "Introduction; File Organization"
date: "4/1/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
    highlight-style: ayu
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #C2352F;
  background-color: #fff;
  padding: 0px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #C2352F;
  padding: 10px;
}
```

## Resources

Below is a table with links to resources. Icons in [orange]{style="color:#E89543;"} mean there is an available file link.

| Lesson | Topic                                |                                                                Slides                                                                |                                  Annotated Slides                                  |                         Recording(s)                          |
|--------------|----------------|:------------:|:------------:|:------------:|
|        | Intro to Course                      |               [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/00_Intro/00_Intro.qmd)]{style="color:#f8f5f0;"}               | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |
| 1      | File Organization within R           | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/01_File_Organization_R/01_File_Organization_R.qmd)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |
| 2      | Introduction to Categorical Analysis |                                [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                 | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |

For the slides, once they are opened, if you would like to print or save them as a PDF, the best way to do this is:

1.  Click on the icon with three horizontal bars on the bottom left of the browser.
2.  Click on "Tools" with the gear icon at the top of the sidebar.
3.  Click on "PDF Export Mode."
4.  From there, you can print or save the PDF as you would normally from your internet browser.
    1.  For example, in Chrome: I would click on the 3 vertical dots in the top right corner, then click Print, then change the Destination to "Save as PDF."
    2.  It doesn't seem to work well in Safari... Let me know if you're having trouble.

[Here is the link to my Poll Everywhere!!](https://pollev.com/nickywakim275)

## Announcements

## On the Horizon

## Class Exit Tickets

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUM0hUSUlOUEk4UTJWMDdSV00zMDVWNkM4Wi4u)]{style="color:#f8f5f0;"} Monday (4/1)

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMFNKNlhJUjU3UVU0R1MyVVczUlQ3NlVSUS4u)]{style="color:#f8f5f0;"} Wednesday (4/3)

## Muddiest Points

```{r}
#| echo: false

g=3
```
