---
title: "Week 2"
description: "Relative Risks and Odds Ratios"
date: "4/8/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #C2352F;
  background-color: #fff;
  padding: 10px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #C2352F;
  padding: 10px;
}
```

## Resources

+--------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lesson | Topic                                             | Slides                                                                                                                         | Annotated Slides                                                                                                                                  | Recording                                                                                                                                                                                                                                            |
+========+===================================================+:==============================================================================================================================:+:=================================================================================================================================================:+:====================================================================================================================================================================================================================================================:+
| 3      | Measurement of Association for Contingency Tables | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/03_Meas_Assoc_CT/03_Meas_Assoc_CT.qmd)]{style="color:#f8f5f0;"}       | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/03_Meas_Assoc_CT/03_Meas_Assoc_CT_notes.pdf)]{style="color:#f8f5f0;"}       | [[{{< iconify mdi video size=34px >}}](https://echo360.org/section/1124906b-db5a-43c1-809d-5eadfbba4aad/public)]{style="color:#f8f5f0;"}                                                                                                             |
+--------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4      | Measurements of Association and Agreement         | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/2efcec30-2c02-454a-b2d8-e64057b6846a/classroom#sortDirection=desc)]{style="color:#f8f5f0;"}                                                                                        |
|        |                                                   |                                                                                                                                |                                                                                                                                                   |                                                                                                                                                                                                                                                      |
|        |                                                   |                                                                                                                                |                                                                                                                                                   | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_a2cd2099-5666-4143-b05a-a1e020f96c16_dffa6d24-1dbf-45aa-8ff9-abe9b32c4e9e_2024-04-10T13:00:00.000_2024-04-10T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} |
+--------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

If you ever have trouble with the above links to the videos, [this Echo360 link](https://echo360.org/section/1124906b-db5a-43c1-809d-5eadfbba4aad/public) should take you to our class page.

For the slides, once they are opened, if you would like to print or save them as a PDF, the best way to do this is **from a computer internet browser**:

1.  Click on the icon with three horizontal bars on the bottom left of the browser.
2.  Click on "Tools" with the gear icon at the top of the sidebar.
3.  Click on "PDF Export Mode."
4.  From there, you can print or save the PDF as you would normally from your internet browser.

**Note: this process does not work very well on an iPad.**

## On the Horizon

-   Homework 1 due this Thursday!

## Announcements

### Monday 4/8

-   Office hours!!

    -   Tuesdays 5:30-7pm with Antara

    -   Thursdays 3:30 - 5pm with Ariel

    -   Fridays 2 - 3:30pm with Nicky

### Wednesday 4/10

-   Echo360: Let's all double check that we can see the recordings

    -   [Link to class site](https://echo360.org/section/1124906b-db5a-43c1-809d-5eadfbba4aad/public)

-   Homework question 5: no need to do LRT in the table

-   Lab 1 is up!!

-   Quiz 1 decision

    -   Online in Sakai

    -   Will open up on Monday at 2pm. You can chose to take it in the classroom or wait

    -   Quiz will close before class on Wednesday

    -   Open book still

    -   Please do not cheat

        -   If I notice any unusual changes to quiz performance compared to last quarter then we will go back to the old way of giving quizzes

    -   Multiple choice with potentially some free response

        -   For example: interpreting an OR would be divided into a multiple choice for the estimate, CI, and then writing a sentence to interpret the estimate

## Class Exit Tickets

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNUpBNjJJSTA0N0s1Q0hXMlkySTREREdRRC4u)]{style="color:#f8f5f0;"} Monday (4/8)

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUN1lDRVlJN0pNNVRMVDJFWUg0Nk9QUDk1Si4u)]{style="color:#f8f5f0;"} Wednesday (4/10)

## Muddiest Points

### 1. "times greater than" vs just "times" in interpretation

I've seen it both ways. It comes down to more of an English language nuance, with [what seems to be a long battle between viewpoints](https://english.stackexchange.com/questions/7894/x-times-as-many-as-or-x-times-more-than). Or maybe more accurately, I grammatically correct way to contruct the sentence, but with people understanding the meaning the "incorrect" way. I tend to be more lenient when it comes to grammar in this way, but maybe that's because I have a general distaste when languages are rigid and don't accommodate how people currently speak and write.

### 2. For the relative risks poll everywhere question #2, how were they derived?

-   For #1 with Trt A's risk as 0.01 (aka $risk_A=0.01$) and Trt B's risk as 0.001 (aka $risk_B=0.01$)

    -   The risk ratio is: $\widehat{RR} = \dfrac{\widehat{p}_1}{\widehat{p}_2} = \dfrac{risk_A}{risk_B} = \dfrac{0.01}{0.001} = 10$

-   For #2 with Trt A's risk as 0.41 (aka $risk_A=0.41$) and Trt B's risk as 0.401 (aka $risk_B=0.401$)

    -   The risk ratio is: $\widehat{RR} = \dfrac{\widehat{p}_1}{\widehat{p}_2} = \dfrac{risk_A}{risk_B} = \dfrac{0.41}{0.401} = 1.02$

### 3. Ranges that odds ratios can take (0, infinity) vs the ranges that risk ratios can take.

Yeah, so both can theoretically take on the range $[0, \infty)$. Both are ratios, so we also have to think about the range of the denominator and numerator For relative risk, the numerator and denominator are probabilities that can only take values from 0 to 1. While for ORs, the denominator and numerator are odds that can be a range of values $[0, \infty)$.

The main point I was trying to make was that once we observe one group's proportion/probability, then RRs and ORs will differ in their potential range. Let's say I observe the proportion fro group 1 and now know the numerator for RR and the odds in the numerator for OR. Because the RR has numerator and denominator that has ranges $[0, 1]$, if we know the proportion of group 1 (aka numerator value), then the ratio itself has a smaller range of values because the denominator can only be between 0 and 1. Because the OR has numerator and denominator that has ranges $[0, \infty)$, if we know the proportion of group 1, then we do have a fixed numerator. However, the denominator can still be in $[0, \infty)$.

### 4. For the odds ratio equation that we reviewed today, is it different from ad/bc ? If they are different, when is it appropriate to use the equation we just reviewed over the other? p1/(1-p1) / p2/(1-p2)

Nope! These are the same! If you learned it that way, you can definitely use it when we are working with contingency tables. However, once we move into ORs from regression with multiple covariates, I think it's better to understand the ORs and odds in terms of the probability/proportion.

### 5. Not directly related to this class, but did we cover LRTs already? They're mentioned in HW1 but aren't in my notes.

Oops! Fixed it in the HW. No need to do anything with LRTs!

### 6. In Epi, we were very strictly told that Odds Ratios were only to be used in one type of study. (I.e. we CAN NOT use them in cross-sectional and cohort studies) only case-control. So what is the application of attempting to utilize them, if each respective type of study already has a "pre-assigned" statistical method that suits it best?

Odds ratios CAN be used in cross-sectional AND cohort studies. It is often an over-estimate of the relative risk in those situations, so it is important to interpret it ONLY as the odds ratio.

Each respective study does not have a pre-assigned method. The only restriction is that relative risk cannot be used in case-control studies.

```{r}
#| echo: false

g=3
```
