---
title: "Week 7"
description: "Assessing Model Fit"
date: "5/13/24"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #C2352F;
  background-color: #fff;
  padding: 10px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #C2352F;
  padding: 10px;
}
```

## Resources

| Lesson | Topic               |                                                          Slides                                                          |                                                              Annotated Slides                                                               |                                                               Recording                                                                |
|-------------|-------------|:-------------:|:-----------------:|:-----------:|
| 12     | Assessing Model Fit | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/12_Assessing_fit/12_Assessing_fit.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lectures/12_Assessing_fit/12_Assessing_fit_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/media/f3988298-163b-41da-a14f-b13b19714ad5/public)]{style="color:#f8f5f0;"} |
| 13     | Numerical Problems  |                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                           |                             [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                              |                                     [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"}                                      |

## On the Horizon

## Class Exit Tickets

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURUVVUEVGR1lSUVVYVUpTRlExS1I1UllGMy4u)]{style="color:#f8f5f0;"} Monday (5/13)

Quiz starts on Wednesday (5/15)

## Announcements

### Monday 5/13

-   I will review our interaction notes from last time
-   **Quiz 2 opens on Wednesday at 2pm!!**
    -   Will cover Lessons 5-9!!
    -   Mostly on Lessons 5-8, with one question about concepts covered in Lesson 9 (like types of missing data...)
        -   Think about how we fit logistic regression and GLMs
        -   Think about link functions!
        -   Think about our tests (Wald, Score, LRT)
        -   Think about the different transformations between Y, probability, and logit!
        -   Think about what our predictions mean
        -   Think about interpretations within logistic regression.
-   Lab 2
    -   I noticed that a lot of you did not comment on the trends from the bivariate analysis
        -   This is why I didn't have us use `ggpairs()` last quarter. It's too easy to just blow past this.
        -   Getting to know your data and the trends you see in the sample is **incredibly important!!**
        -   The best way to identify issues with your model is to have a good understanding of your data and their trends
    -   Many people noticed small cell counts for income levels
        -   We will address this issues in lecture this week!
    -   Unless you are removing food insecurity from any hardship or multiple hardships, do NOT use these variables!

## Muddiest Points

```{r}
#| echo: false

g=3
```
