{
  "hash": "f357d33d7b12bda5df3b0cadc244f786",
  "result": {
    "markdown": "---\ntitle: \"Lesson 10: Multiple Logistic Regression\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#C2352F\"\ndate: \"05/06/2024\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"Lesson 10: Multiple Logistic Regression\"\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n:::\n\n\n\n# Learning Objectives\n\n1.  Construct and fit a multiple logistic regression model\n\n2.  Test for significance of individual coefficients or sets of coefficients in multiple logistic regression\n\n3.  Estimate the predicted probability of our outcome using multiple logistic regression\n\n4.  Present the odds ratios for multiple variables at once\n\n5.  Interpret odds ratios for coefficients while adjusting for other variables\n\n\n\n::: {.cell}\n<style type=\"text/css\">\n.reveal code {\n  max-height: 80% !important;\n}\n</style>\n:::\n\n\n\n## Last class\n\n-   Looked at **simple logistic regression** for binary outcome with\n\n    -   One continuous predictor $$\\text{logit}(\\pi(X)) = \\beta_0 + \\beta_1 \\cdot X$$\n    -   One binary predictor $$\\text{logit}\\left(\\pi(X) \\right) = \\beta_0 + \\beta_1 \\cdot I(X=1)$$\n    -   One multi-level predictor $$\\text{logit}\\left(\\pi(X) \\right) = \\beta_0 + \\beta_1 \\cdot I(X=b) + \\beta_2 \\cdot I(X=c) + \\beta_3 \\cdot I(X=d)$$\n\n## Breast Cancer example\n\n-   For breast cancer diagnosis example, recall:\n\n    -   **Outcome:** early or late stage breast cancer diagnosis (binary, categorical)\n    \n \n\n-   **Primary covariate:** Race/ethnicity\n\n    -   Non-Hispanic white individuals are more likely to be diagnosed with breast cancer\n    \n        -   But POC are more likely to be diagnosed at a later stage\n\n \n\n-   **Additional covariate:** Age\n\n    -   Risk factor for cancer diagnosis\n    \n \n\n-   We want to fit a multiple logistic regression model with both risk factors included as independent variables\n\n# Learning Objectives\n\n::: lob\n1.  Construct and fit a multiple logistic regression model\n:::\n\n2.  Test for significance of individual coefficients or sets of coefficients in multiple logistic regression\n\n3.  Estimate the predicted probability of our outcome using multiple logistic regression\n\n4.  Present the odds ratios for multiple variables at once\n\n5.  Interpret odds ratios for coefficients while adjusting for other variables\n\n## Introduction to Multiple Logistic Regression\n\n-   In multiple logistic regression model, we have > 1 independent variable\n\n    -   Sometimes referred to as the “multi**variable** regression”\n    -   The independent variable can be any type: \n\n        -   Continuous\n        -   Categorical (ordinal or nominal)\n\n \n\n-   We will follow similar procedures as we did for simple logistic regression\n\n    -   But we need to **change our interpretation of estimates** because we are adjusting for other variables\n\n\n## Multiple Logistic Regression Model\n\n::: columns\n::: {.column width=\"60%\"}\n-   Assume we have a collection of $k$ independent variables, denoted by $\\mathbf{X}=\\left( X_1, X_2, ..., X_k \\right)$\n\n \n\n-   The conditional probability is $P(Y=1 | \\mathbf{X}) = \\pi(\\mathbf{X})$\n\n\n \n\n-   We then model the probability with logistic regression: $$\\text{logit}\\left(\\pi(\\mathbf{X})\\right) = \\beta_0\n+\\beta_1 \\cdot X_1 +\\beta_2 \\cdot X_2  +\\beta_3 \\cdot X_3 + ... + \\beta_k \\cdot X_k$$\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"36%\"}\n::: theorem\n::: thm-title\nWhy the bold $X$?\n:::\n::: thm-cont\n$\\mathbf{X}$ represents the vector of all the $X$'s. This is how we represent our group of covariates in our model.\n:::\n:::\n:::\n\n:::\n\n## Fitting the Multiple Logistic Regression Model\n-   For a multiple logistic regression model with $k$ independent variables, the **vector of coefficients** can be denoted by $$\\boldsymbol{\\beta}^{T} = \\left(\\beta_0, \\beta_1, \\beta_2, ..., \\beta_k \\right)$$\n\n \n\n-   As with the simple logistic regression, we use **maximum likelihood method** for estimating coefficients\n\n    -   Vector of estimated coefficients: $$\\widehat{\\boldsymbol{\\beta}}^{T} = \\left(\\widehat{\\beta}_0, \\widehat{\\beta}_1, \\widehat{\\beta}_2, ..., \\widehat{\\beta}_k \\right)$$\n\n \n\n-   For a model with $k$ independent variables, there is $k+1$ coefficients to estimate\n\n    -   Unless one of those independent variables is a multi-level categorical variables, then we need more than $k+1$ coefficients\n\n\n## Breast Cancer Example: Population Model\n\n-   We can fit a logistic regression model with both race and ethnicity and age:\n\n$$ \\begin{aligned}\n\\text{logit}\\left(\\pi(\\mathbf{X})\\right) = & \\beta_0\n+\\beta_1 \\cdot I \\left( R/E = H/L \\right)\n+\\beta_2 \\cdot I \\left( R/E = NH AIAN \\right) \\\\\n& +\\beta_3 \\cdot I \\left( R/E = NH API \\right)\n+\\beta_4 \\cdot I \\left( R/E = NH B \\right)\n+\\beta_5 \\cdot Age \n\\end{aligned}$$\n\n \n\n \n\n-   Note that race and ethnicity requires 4 coefficients to include the indicator for each category\n\n \n\n-   Can replace $\\pi(\\mathbf{X})$ with $\\pi({\\text{Race/ethnicity, Age}})$\n\n \n\n-   6 total coefficients ($\\beta_0$ to $\\beta_5$)\n\n## Fitting Multiple Logistic Regression Model {.smaller}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_bc = glm(Late_stage_diag ~ Race_Ethnicity + Age_c, data = bc, family = binomial)\nsummary(multi_bc)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = Late_stage_diag ~ Race_Ethnicity + Age_c, family = binomial, \n    data = bc)\n\nCoefficients:\n                                                 Estimate Std. Error z value\n(Intercept)                                     -1.038389   0.027292 -38.048\nRace_EthnicityHispanic-Latino                   -0.015424   0.083653  -0.184\nRace_EthnicityNH American Indian/Alaskan Native -0.085704   0.484110  -0.177\nRace_EthnicityNH Asian/Pacific Islander          0.133965   0.083797   1.599\nRace_EthnicityNH Black                           0.357692   0.071789   4.983\nAge_c                                            0.057151   0.003209  17.811\n                                                Pr(>|z|)    \n(Intercept)                                      < 2e-16 ***\nRace_EthnicityHispanic-Latino                      0.854    \nRace_EthnicityNH American Indian/Alaskan Native    0.859    \nRace_EthnicityNH Asian/Pacific Islander            0.110    \nRace_EthnicityNH Black                          6.27e-07 ***\nAge_c                                            < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 11861  on 9999  degrees of freedom\nResidual deviance: 11484  on 9994  degrees of freedom\nAIC: 11496\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\n\n## Breast Cancer Example: Fitted Model\n\n-   We now have the **fitted logistic regression model** with both race and ethnicity and age:\n\n$$ \\begin{aligned}\n\\text{logit}\\left(\\widehat{\\pi}(\\mathbf{X})\\right) = & \\widehat{\\beta}_0\n+ \\widehat{\\beta}_1 \\cdot I \\left( R/E = H/L \\right)\n+ \\widehat{\\beta}_2 \\cdot I \\left( R/E = NH AIAN \\right) \\\\\n& + \\widehat{\\beta}_3 \\cdot I \\left( R/E = NH API \\right)\n+ \\widehat{\\beta}_4 \\cdot I \\left( R/E = NH B \\right)\n+ \\widehat{\\beta}_5 \\cdot Age \\\\\n\\\\\n\\text{logit}\\left(\\widehat{\\pi}(\\mathbf{X})\\right) = &-4.56\n-0.02 \\cdot I \\left( R/E = H/L \\right)\n-0.09 \\cdot I \\left( R/E = NH AIAN \\right) \\\\\n& +0.13 \\cdot I \\left( R/E = NH API \\right)\n+0.36 \\cdot I \\left( R/E = NH B \\right)\n+0.06 \\cdot Age \n\\end{aligned}$$\n\n-   6 total coefficients ($\\widehat{\\beta}_0$ to $\\widehat{\\beta}_5$)\n\n# Learning Objectives\n\n1.  Construct and fit a multiple logistic regression model\n\n::: lob\n2.  Test for significance of individual coefficients or sets of coefficients in multiple logistic regression\n:::\n\n3.  Estimate the predicted probability of our outcome using multiple logistic regression\n\n4.  Present the odds ratios for multiple variables at once\n\n5.  Interpret odds ratios for coefficients while adjusting for other variables\n\n## Testing Significance of the Coefficients\n\n-   Refer to Lesson 6 for more information on each test!!\n\n \n\n-   We use the same three tests that we discussed in Simple Logistic Regression to test individual coefficients\n\n    -   [Wald test]{style=\"background-color:#D5E2F1;\"}\n    \n        -   Can be used to test a single coefficient\n        \n    -   [~~Score test~~]{style=\"background-color:#F9E7B8;\"}\n    -   [Likelihood ratio test (LRT)]{style=\"background-color:#CADFB8;\"}\n    \n        -   Can be used to test a single coefficient or multiple coefficients\n        \n \n\n-   Textbook and our class focuses on Wald and LRT only\n\n## A note on wording\n\n-   When I say \"test a single coefficient\" or \"test multiple coefficients\" I am referring to the $\\beta$'s\n\n    -   A single variable can have a single coefficient\n        -   Example: testing age \n        \n        \n    -   A single variable can have multiple coefficients\n        -   Example: testing race and ethnicity\n        \n\n    -   Muliple variables will have multiple coefficients\n        -   Example: testing age and race and ethnicity together\n    \n     \n       \n-   When I say \"test a variable\" I mean \"determine if the model with the variable is more likely than the model without that variable\"\n\n    -   We can use the Wald test to do this is some scenarios (single, continuous covariate)\n    -   BUT I advise you practice using the LRT whenever comparing models (aka testing variables)\n\n## All three tests together\n\n![](./images/three_tests.png){fig-align=\"center\"}\n\n## From Lesson 6: Wald test{background-image=\"./images/title_blue.png\" background-size=\"2500px 150px\" background-position=\"top\"}\n\n-   Assumes test statistic W follows a standard normal distribution under the null hypothesis\n\n-   Test statistic: $$W=\\frac{{\\hat{\\beta}}_j}{SE_{\\hat{\\beta}_j}}\\sim N(0,1)$$\n\n    -   where $\\widehat{\\beta}_j$ is a MLE of coefficient $j$\n\n-   95% Wald confidence interval: $${\\hat{\\beta}}_1\\pm1.96 \\cdot SE_{{\\hat{\\beta}}_j}$$\n\n-   The Wald test is a routine output in R (`summary()` of `glm()` output)\n\n    -   Includes $SE_{{\\hat{\\beta}}_j}$ and can easily find confidence interval with `tidy()`\n    \n-   **Important note:** Wald test is best for confidence intervals of our coefficient estimates or estimated odds ratios. \n\n    \n## Wald test procedure with confidence intervals {background-image=\"./images/title_blue.png\" background-size=\"2500px 150px\" background-position=\"top\"}\n\n1.  Set the [**level of significance**]{style=\"color:#5B9BD5\"} $\\alpha$\n\n2.  Specify the [**null**]{style=\"color:#5B9BD5\"} ( $H_0$ ) and [**alternative**]{style=\"color:#5B9BD5\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#5B9BD5\"}\n\n    -   In symbols\n    -   In words\n    -   Alternative: one- or two-sided?\n\n3.  Calculate the [**confidence interval**]{style=\"color:#5B9BD5\"} and [**determine if it overlaps with null**]{style=\"color:#5B9BD5\"}\n\n    -   Overlap with null (usually 0 for coefficient) = fail to reject null\n    -   No overlap with null (usually 0 for coefficient) = reject null\n\n4.  Write a [**conclusion**]{style=\"color:#5B9BD5\"} to the hypothesis test\n\n    -   What is the estimate and its confidence interval?\n    -   Do we reject or fail to reject $H_0$?\n    -   Write a conclusion in the context of the problem\n    \n## Wald test in our example {background-image=\"./images/title_blue.png\" background-size=\"2500px 150px\" background-position=\"top\"}\n\n-   From our multiple logistic regression model:\n\n$$ \\begin{aligned}\n\\text{logit}\\left(\\pi(x_i)\\right) = & \\beta_0\n+\\beta_1 \\cdot I \\left( R/E = H/L \\right)\n+\\beta_2 \\cdot I \\left( R/E = NH AIAN \\right) \\\\\n& +\\beta_3 \\cdot I \\left( R/E = NH API \\right)\n+\\beta_4 \\cdot I \\left( R/E = NH B \\right)\n+\\beta_5 \\cdot Age \n\\end{aligned}$$\n\n \n\n-   Wald test can help us **construct the confidence interval for ALL coefficient estimates**\n\n \n\n-   If we want to use the Wald test to determine if a covariate is significant in our model\n\n    -   Can only do so for **age**\n\n## Example 1: Single, continuous variable: Age\n\n::: example\n::: ex-title\nSingle, continuous variable: Age\n:::\n::: ex_cont\nGiven race and ethnicity is already in the model, is the regression model with age more likely than the model without age?\n:::\n:::\n\n**Needed steps:**\n\n1.  Set the **level of significance** $\\alpha$\n2.  Specify the **null** ( $H_0$ ) and **alternative** ( $H_A$ ) **hypotheses**\n3.  Calculate the **confidence interval** and **determine if it overlaps with null**\n4.  Write a **conclusion** to the hypothesis test\n\n## Example 1: Single, continuous variable: Age\n\n::: example\n::: ex-title\nSingle, continuous variable: Age\n:::\n::: ex_cont\nGiven race and ethnicity is already in the model, is the regression model with age more likely than the model without age?\n:::\n:::\n\n1.  Set the **level of significance** $\\alpha$\n\n    -   $\\alpha = 0.05$\n\n2.  Specify the **null** ( $H_0$ ) and **alternative** ( $H_A$ ) **hypotheses**\n\n    -   $H_0: \\beta_5 = 0$\n    -   $H_1: \\beta_5 \\neq 0$\n\n## Example 1: Single, continuous variable: Age\n\n::: example\n::: ex-title\nSingle, continuous variable: Age\n:::\n::: ex_cont\nGiven race and ethnicity is already in the model, is the regression model with age more likely than the model without age?\n:::\n:::\n\n3.  Calculate the **confidence interval** and **determine if it overlaps with null**\n\n-   Look at *coefficient estimates* (CI should not contain 0) OR *estimated odds ratio* (CI should not contain 1)\n\n::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(multi_bc, conf.int=T) %>% \n  gt() %>% \n  tab_options(table.font.size = 28) %>%\n  fmt_number(decimals = 2)\n```\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"ypueffhcwb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ypueffhcwb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ypueffhcwb thead, #ypueffhcwb tbody, #ypueffhcwb tfoot, #ypueffhcwb tr, #ypueffhcwb td, #ypueffhcwb th {\n  border-style: none;\n}\n\n#ypueffhcwb p {\n  margin: 0;\n  padding: 0;\n}\n\n#ypueffhcwb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 28px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ypueffhcwb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ypueffhcwb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ypueffhcwb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ypueffhcwb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ypueffhcwb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ypueffhcwb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ypueffhcwb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ypueffhcwb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ypueffhcwb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ypueffhcwb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ypueffhcwb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ypueffhcwb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ypueffhcwb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ypueffhcwb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ypueffhcwb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ypueffhcwb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ypueffhcwb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ypueffhcwb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ypueffhcwb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ypueffhcwb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ypueffhcwb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ypueffhcwb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ypueffhcwb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ypueffhcwb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ypueffhcwb .gt_left {\n  text-align: left;\n}\n\n#ypueffhcwb .gt_center {\n  text-align: center;\n}\n\n#ypueffhcwb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ypueffhcwb .gt_font_normal {\n  font-weight: normal;\n}\n\n#ypueffhcwb .gt_font_bold {\n  font-weight: bold;\n}\n\n#ypueffhcwb .gt_font_italic {\n  font-style: italic;\n}\n\n#ypueffhcwb .gt_super {\n  font-size: 65%;\n}\n\n#ypueffhcwb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ypueffhcwb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ypueffhcwb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ypueffhcwb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ypueffhcwb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ypueffhcwb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ypueffhcwb .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.04</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−38.05</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.09</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−0.99</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">Race_EthnicityHispanic-Latino</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−0.02</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.08</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−0.18</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.85</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−0.18</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.15</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">Race_EthnicityNH American Indian/Alaskan Native</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−0.09</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.48</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−0.18</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.86</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.12</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.81</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">Race_EthnicityNH Asian/Pacific Islander</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.13</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.08</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">1.60</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.11</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−0.03</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.30</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">Race_EthnicityNH Black</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.36</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.07</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.98</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.22</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.50</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">Age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.06</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">17.81</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.05</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.06</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n:::\n\n## Example 1: Single, continuous variable: Age\n\n::: example\n::: ex-title\nSingle, continuous variable: Age\n:::\n::: ex_cont\nGiven race and ethnicity is already in the model, is the regression model with age more likely than the model without age?\n:::\n:::\n\n3.  Calculate the **confidence interval** and **determine if it overlaps with null**\n\n-   Look at *coefficient estimates* (CI should not contain 0) OR *estimated odds ratio* (CI should not contain 1)\n\n::: columns\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(multi_bc, \n               exponentiate = TRUE) %>%\n  as_gt() %>% \n  tab_options(table.font.size = 30)\n```\n:::\n\n\n:::\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"vxuvlqszjn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vxuvlqszjn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vxuvlqszjn thead, #vxuvlqszjn tbody, #vxuvlqszjn tfoot, #vxuvlqszjn tr, #vxuvlqszjn td, #vxuvlqszjn th {\n  border-style: none;\n}\n\n#vxuvlqszjn p {\n  margin: 0;\n  padding: 0;\n}\n\n#vxuvlqszjn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vxuvlqszjn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vxuvlqszjn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vxuvlqszjn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vxuvlqszjn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vxuvlqszjn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vxuvlqszjn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vxuvlqszjn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vxuvlqszjn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vxuvlqszjn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vxuvlqszjn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vxuvlqszjn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vxuvlqszjn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vxuvlqszjn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vxuvlqszjn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vxuvlqszjn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vxuvlqszjn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vxuvlqszjn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vxuvlqszjn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vxuvlqszjn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vxuvlqszjn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vxuvlqszjn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vxuvlqszjn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vxuvlqszjn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vxuvlqszjn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vxuvlqszjn .gt_left {\n  text-align: left;\n}\n\n#vxuvlqszjn .gt_center {\n  text-align: center;\n}\n\n#vxuvlqszjn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vxuvlqszjn .gt_font_normal {\n  font-weight: normal;\n}\n\n#vxuvlqszjn .gt_font_bold {\n  font-weight: bold;\n}\n\n#vxuvlqszjn .gt_font_italic {\n  font-style: italic;\n}\n\n#vxuvlqszjn .gt_super {\n  font-size: 65%;\n}\n\n#vxuvlqszjn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vxuvlqszjn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vxuvlqszjn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vxuvlqszjn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vxuvlqszjn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vxuvlqszjn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vxuvlqszjn .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;OR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>OR</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Race_Ethnicity</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH White</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Hispanic-Latino</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.98</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.83, 1.16</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH American Indian/Alaskan Native</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.92</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.33, 2.25</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH Asian/Pacific Islander</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.14</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.97, 1.35</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.11</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH Black</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.43</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.24, 1.65</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.06</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.05, 1.07</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n:::\n\n## Example 1: Single, continuous variable: Age\n\n::: example\n::: ex-title\nSingle, continuous variable: Age\n:::\n::: ex_cont\nGiven race and ethnicity is already in the model, is the regression model with age more likely than the model without age?\n:::\n:::\n\n4.  Write a **conclusion** to the hypothesis test\n\nGiven race and ethnicity is already in the model, the regression model with age is more likely than the model without age (p-val < 0.001).\n\n# Break here?\n\n## Likelihood ratio test {background-image=\"./images/title_green.png\" background-size=\"2500px 150px\" background-position=\"top\"}\n\n-   Likelihood ratio test answers the question:\n\n    -   For a specific covariate, **which model tell us more about the outcome variable**: the model including the covariate (or set of covariates) or the model omitting the covariate (or set of covariates)?\n    -   Aka: Which model is more likely given our data: model including the covariate or the model omitting the covariate?\n\n \n\n-   Test a single coefficient by comparing different models\n\n    -   **Very similar to the F-test**\n\n \n\n-   Important: LRT can be used conduct hypothesis tests for **multiple coefficients**\n\n    -   Just like F-test, we can test a single coefficient, continuous/binary covariate, multi-level covariate, or multiple covariates\n\n## Likelihood ratio test (3/3) {background-image=\"./images/title_green.png\" background-size=\"2500px 150px\" background-position=\"top\"}\n\n-   If testing **single variable** and it’s **continuous or binary**, still use this hypothesis test:\n\t\n    -   $H_0$: $\\beta_j = 0$\n    -   $H_1$: $\\beta_j \\neq 0$\n\n \n\n-   If testing **single variable** and it’s **categorical with mroe than 2 groups**, use this hypothesis test:\n    \n    -   $H_0$: $\\beta_j=\\beta_{j+1}=\\ldots=\\beta_{j+i-1}=0$\n    -   $H_1$: at least one of the above $\\beta$’s is not equal to 0\n\n\n \n\n-   If testing a **set of variables**, use this hypothesis test:\n\n    -   $H_0$: $\\beta_1=\\beta_{2}=\\ldots=\\beta_{k}=0$\n    -   $H_1$: at least one of the above $\\beta$’s is not equal to 0\n\n## LRT procedure {background-image=\"./images/title_green.png\" background-size=\"2500px 150px\" background-position=\"top\"}\n\n1.  Set the [**level of significance**]{style=\"color:#70AD47\"} $\\alpha$\n\n2.  Specify the [**null**]{style=\"color:#70AD47\"} ( $H_0$ ) and [**alternative**]{style=\"color:#70AD47\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#70AD47\"}\n\n    -   In symbols\n    -   In words\n    -   Alternative: one- or two-sided?\n\n3.  Calculate the [**test statistic**]{style=\"color:#70AD47\"} and [**p-value**]{style=\"color:#70AD47\"}\n\n4.  Write a [**conclusion**]{style=\"color:#70AD47\"} to the hypothesis test\n\n    -   Do we reject or fail to reject $H_0$?\n    -   Write a conclusion in the context of the problem\n\n## Likelihood ratio test (3/3) {background-image=\"./images/title_green.png\" background-size=\"2500px 150px\" background-position=\"top\"}\n\n-   From our multiple logistic regression model:\n\n$$ \\begin{aligned}\n\\text{logit}\\left(\\pi(\\mathbf{X})\\right) = & \\beta_0\n+\\beta_1 \\cdot I \\left( R/E = H/L \\right)\n+\\beta_2 \\cdot I \\left( R/E = NH AIAN \\right) \\\\\n& +\\beta_3 \\cdot I \\left( R/E = NH API \\right)\n+\\beta_4 \\cdot I \\left( R/E = NH B \\right)\n+\\beta_5 \\cdot Age \n\\end{aligned}$$\n\n-   We can test a single coefficient or multiple coefficients\n\n     \n\n    -   **Example 1:** Single, continuous variable: Age\n    \n     \n    \n    -   **Example 2:** Single, >2 categorical variable: Race and Ethnicity\n    \n     \n\n    -   **Example 3:** Set of variables: Race and Ethnicity, and Age\n\n## Reminder on nested models\n\n-   Likelihood ratio test is only suitable to test “nested” models\n\n-   “Nested” models means the bigger model (full model) contains all the independent variables of the smaller model (reduced model)\n\n-   We cannot compare the following two models using LRT:\n\n    -   Model 1: $$ \\begin{aligned} \\text{logit}\\left(\\pi(\\mathbf{X})\\right) = & \\beta_0 +\\beta_1 \\cdot I \\left( R/E = H/L \\right) +\\beta_2 \\cdot I \\left( R/E = NH AIAN \\right) \\\\ & +\\beta_3 \\cdot I \\left( R/E = NH API \\right) +\\beta_4 \\cdot I \\left( R/E = NH B \\right) \\end{aligned}$$\n\n    -   Model 2: $$\\begin{aligned} \\text{logit}\\left(\\pi(Age)\\right) = & \\beta_0+\\beta_1 \\cdot Age  \\end{aligned}$$\n\n-   If the two models to be compared are not nested, likelihood ratio test should not be used\n\n## Example 1: Single, continuous variable: Age\n\n::: example\n::: ex-title\nSingle, continuous variable: Age\n:::\n::: ex_cont\nGiven race and ethnicity is already in the model, is the regression model with age more likely than the model without age?\n:::\n:::\n\n**Needed steps:**\n\n1.  Set the **level of significance** $\\alpha$\n2.  Specify the **null** ( $H_0$ ) and **alternative** ( $H_A$ ) **hypotheses**\n3.  Calculate the **test statistic** and **p-value**\n4.  Write a **conclusion** to the hypothesis test\n\n## Example 1: Single, continuous variable: Age\n\n::: example\n::: ex-title\nSingle, continuous variable: Age\n:::\n::: ex_cont\nGiven race and ethnicity is already in the model, is the regression model with age more likely than the model without age?\n:::\n:::\n\n1.  Set the **level of significance** $\\alpha$\n\n    -   $\\alpha = 0.05$\n\n2.  Specify the **null** ( $H_0$ ) and **alternative** ( $H_A$ ) **hypotheses**\n\n    -   $H_0: \\beta_5 = 0$ or model without age is more likely\n    -   $H_1: \\beta_5 \\neq 0$ or model with age is more likely\n\n\n## Example 1: Single, continuous variable: Age\n\n::: example\n::: ex-title\nSingle, continuous variable: Age\n:::\n::: ex_cont\nGiven race and ethnicity is already in the model, is the regression model with age more likely than the model without age?\n:::\n:::\n\n3.  Calculate the **test statistic** and **p-value**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_bc = glm(Late_stage_diag ~ Race_Ethnicity + Age_c, data = bc, family = binomial)\nre_bc = glm(Late_stage_diag ~ Race_Ethnicity, data = bc, family = binomial)\n\nlmtest::lrtest(multi_bc, re_bc)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: Late_stage_diag ~ Race_Ethnicity + Age_c\nModel 2: Late_stage_diag ~ Race_Ethnicity\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   6 -5741.8                         \n2   5 -5918.1 -1 352.63  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n\n## Example 1: Single, continuous variable: Age\n\n::: example\n::: ex-title\nSingle, continuous variable: Age\n:::\n::: ex_cont\nGiven race and ethnicity is already in the model, is the regression model with age more likely than the model without age?\n:::\n:::\n\n4.  Write a **conclusion** to the hypothesis test\n\nGiven race and ethnicity is already in the model, the regression model with age is more likely than the model without age (p-val < $2.2\\cdot10^{-16}$).\n\n## Example 2: Single, >2 categorical variable: Race and Ethnicity\n\n::: example\n::: ex-title\nSingle, >2 categorical variable: Race and Ethnicity\n:::\n::: ex_cont\nGiven age is already in the model, is the regression model with race and ethnicity more likely than the model without race and ethnicity?\n:::\n:::\n\n**Needed steps:**\n\n1.  Set the **level of significance** $\\alpha$\n2.  Specify the **null** ( $H_0$ ) and **alternative** ( $H_A$ ) **hypotheses**\n3.  Calculate the **test statistic** and **p-value**\n4.  Write a **conclusion** to the hypothesis test\n\n## Example 2: Single, >2 categorical variable: Race and Ethnicity\n\n::: example\n::: ex-title\nSingle, >2 categorical variable: Race and Ethnicity\n:::\n::: ex_cont\nGiven age is already in the model, is the regression model with race and ethnicity more likely than the model without race and ethnicity?\n:::\n:::\n\n1.  Set the **level of significance** $\\alpha$\n\n    -   $\\alpha = 0.05$\n\n2.  Specify the **null** ( $H_0$ ) and **alternative** ( $H_A$ ) **hypotheses**\n\n    -   $H_0: \\beta_1 = \\beta_2 = \\beta_3 = \\beta_4 = 0$ or model without race and ethnicity is more likely\n    -   $H_1: at least one $\\beta$ is not 0 or model with race and ethnicity is more likely\n\n## Example 2: Single, >2 categorical variable: Race and Ethnicity\n\n::: example\n::: ex-title\nSingle, >2 categorical variable: Race and Ethnicity\n:::\n::: ex_cont\nGiven age is already in the model, is the regression model with race and ethnicity more likely than the model without race and ethnicity?\n:::\n:::\n\n3.  Calculate the **test statistic** and **p-value**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_bc = glm(Late_stage_diag ~ Race_Ethnicity + Age_c, data = bc, family = binomial)\nage_bc = glm(Late_stage_diag ~ Age_c, data = bc, family = binomial)\n\nlmtest::lrtest(multi_bc, age_bc)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: Late_stage_diag ~ Race_Ethnicity + Age_c\nModel 2: Late_stage_diag ~ Age_c\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   6 -5741.8                         \n2   2 -5754.8 -4 26.053  3.087e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n\n## Example 2: Single, >2 categorical variable: Race and Ethnicity\n\n::: example\n::: ex-title\nSingle, >2 categorical variable: Race and Ethnicity\n:::\n::: ex_cont\nGiven age is already in the model, is the regression model with race and ethnicity more likely than the model without race and ethnicity?\n:::\n:::\n\n4.  Write a **conclusion** to the hypothesis test\n\nGiven age is already in the model, the regression model with race and ethnicity is more likely than the model without race and ethnicity (p-val = $3.1\\cdot10^{-5}$ < 0.05).\n\n## Example 3: Set of variables: Race and Ethnicity, and Age\n\n::: example\n::: ex-title\nSet of variables: Race and Ethnicity, and Age\n:::\n::: ex_cont\nIs the regression model with race and ethnicity and age more likely than the model without race and ethnicity nor age?\n:::\n:::\n\n**Needed steps:**\n\n1.  Set the **level of significance** $\\alpha$\n2.  Specify the **null** ( $H_0$ ) and **alternative** ( $H_A$ ) **hypotheses**\n3.  Calculate the **test statistic** and **p-value**\n4.  Write a **conclusion** to the hypothesis test\n\n## Example 3: Set of variables: Race and Ethnicity, and Age\n\n::: example\n::: ex-title\nSet of variables: Race and Ethnicity, and Age\n:::\n::: ex_cont\nIs the regression model with race and ethnicity and age more likely than the model without race and ethnicity nor age?\n:::\n:::\n\n1.  Set the **level of significance** $\\alpha$\n\n    -   $\\alpha = 0.05$\n\n2.  Specify the **null** ( $H_0$ ) and **alternative** ( $H_A$ ) **hypotheses**\n\n    -   $H_0: \\beta_1 = \\beta_2 = \\beta_3 = \\beta_4 = \\beta_5 = 0$ or model without race and ethnicity and age is more likely\n    -   $H_1: at least one $\\beta$ is not 0 or model with race and ethnicity and age is more likely\n\n## Example 3: Set of variables: Race and Ethnicity, and Age\n\n::: example\n::: ex-title\nSet of variables: Race and Ethnicity, and Age\n:::\n::: ex_cont\nIs the regression model with race and ethnicity and age more likely than the model without race and ethnicity nor age?\n:::\n:::\n\n3.  Calculate the **test statistic** and **p-value**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_bc = glm(Late_stage_diag ~ Race_Ethnicity + Age_c, data = bc, family = binomial)\nintercept_bc = glm(Late_stage_diag ~ 1, data = bc, family = binomial)\n\nlmtest::lrtest(multi_bc, intercept_bc)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: Late_stage_diag ~ Race_Ethnicity + Age_c\nModel 2: Late_stage_diag ~ 1\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   6 -5741.8                         \n2   1 -5930.5 -5 377.32  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n\n## Example 3: Set of variables: Race and Ethnicity, and Age\n\n::: example\n::: ex-title\nSet of variables: Race and Ethnicity, and Age\n:::\n::: ex_cont\nIs the regression model with race and ethnicity and age more likely than the model without race and ethnicity nor age?\n:::\n:::\n\n4.  Write a **conclusion** to the hypothesis test\n\nThe regression model with race and ethnicity and age is more likely than the model omitting race and ethnicity and age (p-val < $2.2\\cdot10^{-16}$).\n\n# Learning Objectives\n\n1.  Construct and fit a multiple logistic regression model\n\n2.  Test for significance of individual coefficients or sets of coefficients in multiple logistic regression\n\n::: lob\n3.  Estimate the predicted probability of our outcome using multiple logistic regression\n:::\n\n4.  Present the odds ratios for multiple variables at once\n\n5.  Interpret odds ratios for coefficients while adjusting for other variables\n\n## Estimated/Predicted Probability for MLR\n\n-   Basic idea for predicting/estimating probability stays the same\n\n \n\n-   Calculations will be slightly different\n\n    -   Especially for the confidence interval\n    \n \n\n-   Recall our fitted model for late stage breast cancer diagnosis: $$ \\begin{aligned}\n\\text{logit}\\left(\\widehat{\\pi}(\\mathbf{X})\\right) = &-4.56\n-0.02 \\cdot I \\left( R/E = H/L \\right)\n-0.09 \\cdot I \\left( R/E = NH AIAN \\right) \\\\\n& +0.13 \\cdot I \\left( R/E = NH API \\right)\n+0.36 \\cdot I \\left( R/E = NH B \\right)\n+0.06 \\cdot Age \n\\end{aligned}$$\n\n## Predicted Probability\n\n-   We may be interested in predicting probability of having a late stage breast cancer diagnosis for a specific age.\n-   The predicted probability is the estimated probability of having the event for given values of covariate(s)\n-   Recall our fitted model for late stage breast cancer diagnosis: $$ \\begin{aligned}\n\\text{logit}\\left(\\widehat{\\pi}(\\mathbf{X})\\right) = &-4.56\n-0.02 \\cdot I \\left( R/E = H/L \\right)\n-0.09 \\cdot I \\left( R/E = NH AIAN \\right) \\\\\n& +0.13 \\cdot I \\left( R/E = NH API \\right)\n+0.36 \\cdot I \\left( R/E = NH B \\right)\n+0.06 \\cdot Age \n\\end{aligned}$$\n\n-   We can convert it to the predicted probability: $$\\hat{\\pi}(\\mathbf{X})=\\dfrac{\\exp \\left( \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot I \\left( R/E = H/L \\right) + ... + \\widehat{\\beta}_5 \\cdot Age \\right)}  {1+\\exp \\left(\\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot I \\left( R/E = H/L \\right) + ... + \\widehat{\\beta}_5 \\cdot Age \\right)}$$\n\n    -   This is an inverse logit calculation\n\n-   We can calculate this using the the `predict()` function like in BSTA 512\n\n    - Another option: taking inverse logit of fitted values from `augment()` function\n\n## Predicting probability in R \n\n::: example\n::: ex-title\nPredicting probability of late stage breast cancer diagnosis\n:::\n::: ex-cont\nFor someone who is 60 years old and Non-Hispanic Asian/Pacific Islander, what is the predicted probability for late stage breast cancer diagnosis (with confidence intervals)?\n:::\n:::\n\n**Needed steps:**\n\n1. Calculate probability prediction\n2. Check if we can use Normal approximation\n3. Calculate confidence interval\n\n    a.   Using logit scale then converting\n    b.   Using Normal approximation \n    \n4. Interpret results\n\n## Predicting probability in R \n\n::: example\n::: ex-title\nPredicting probability of late stage breast cancer diagnosis\n:::\n::: ex-cont\nFor someone who is 60 years old and Non-Hispanic Asian/Pacific Islander, what is the predicted probability for late stage breast cancer diagnosis (with confidence intervals)?\n:::\n:::\n\n1. Calculate probability prediction\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnewdata = data.frame(Age_c = 60 - mean_age, \n                     Race_Ethnicity = \"NH Asian/Pacific Islander\")\npred1 = predict(multi_bc, newdata, se.fit = T, type=\"response\")\npred1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$fit\n        1 \n0.2685667 \n\n$se.fit\n         1 \n0.01572695 \n\n$residual.scale\n[1] 1\n```\n:::\n:::\n\n\n    \n\n## Predicting probability in R \n\n::: example\n::: ex-title\nPredicting probability of late stage breast cancer diagnosis\n:::\n::: ex-cont\nFor someone who is 60 years old and Non-Hispanic Asian/Pacific Islander, what is the predicted probability for late stage breast cancer diagnosis (with confidence intervals)?\n:::\n:::\n\n2. Check if we can use Normal approximation\n\nWe can use the Normal approximation if: $\\widehat{p}n = \\widehat{\\pi}(X)\\cdot n > 10$ and $(1-\\widehat{p})n = (1-\\widehat{\\pi}(X))\\cdot n > 10$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = nobs(multi_bc)\np = pred1$fit\nn*p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n2685.667 \n```\n:::\n\n```{.r .cell-code}\nn*(1-p)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n7314.333 \n```\n:::\n:::\n\n\n\nWe can use the Normal approximation!\n\n## Predicting probability in R \n\n::: example\n::: ex-title\nPredicting probability of late stage breast cancer diagnosis\n:::\n::: ex-cont\nFor someone who is 60 years old and Non-Hispanic Asian/Pacific Islander, what is the predicted probability for late stage breast cancer diagnosis (with confidence intervals)?\n:::\n:::\n\n3b. Calculate confidence interval (Option 2: with Normal approximation)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred = predict(multi_bc, newdata, se.fit = T, type = \"response\")\n\nLL_CI = pred$fit - qnorm(1-0.05/2) * pred$se.fit\nUL_CI = pred$fit + qnorm(1-0.05/2) * pred$se.fit\n\nc(Pred = pred$fit, LL_CI, UL_CI) %>% round(digits=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPred.1      1      1 \n 0.269  0.238  0.299 \n```\n:::\n:::\n\n\n\n## Predicting probability in R \n\n::: example\n::: ex-title\nPredicting probability of late stage breast cancer diagnosis\n:::\n::: ex-cont\nFor someone who is 60 years old and Non-Hispanic Asian/Pacific Islander, what is the predicted probability for late stage breast cancer diagnosis (with confidence intervals)?\n:::\n:::\n    \n4. Interpret results\n\nFor someone who is 60 years old and Non-Hispanic Asian/Pacific Islander, the predicted probability of late stage breast cancer diagnosis is 0.269 (95% CI: 0.238, 0.299).\n\n# Learning Objectives\n\n1.  Construct and fit a multiple logistic regression model\n\n2.  Test for significance of individual coefficients or sets of coefficients in multiple logistic regression\n\n3.  Estimate the predicted probability of our outcome using multiple logistic regression\n\n::: lob\n4.  Present the odds ratios for multiple variables at once\n:::\n\n5.  Interpret odds ratios for coefficients while adjusting for other variables\n\n## How to present odds ratios: Table\n\n-   `tbl_regression()` in the `gtsummary` package is helpful for presenting the odds ratios in a clean way\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gtsummary)\ntbl_regression(multi_bc, exponentiate = TRUE) %>% \n  as_gt() %>% # allows us to use tab_options()\n  tab_options(table.font.size = 38)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ideynrdtcx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ideynrdtcx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ideynrdtcx thead, #ideynrdtcx tbody, #ideynrdtcx tfoot, #ideynrdtcx tr, #ideynrdtcx td, #ideynrdtcx th {\n  border-style: none;\n}\n\n#ideynrdtcx p {\n  margin: 0;\n  padding: 0;\n}\n\n#ideynrdtcx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 38px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ideynrdtcx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ideynrdtcx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ideynrdtcx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ideynrdtcx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ideynrdtcx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ideynrdtcx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ideynrdtcx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ideynrdtcx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ideynrdtcx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ideynrdtcx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ideynrdtcx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ideynrdtcx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ideynrdtcx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ideynrdtcx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ideynrdtcx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ideynrdtcx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ideynrdtcx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ideynrdtcx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ideynrdtcx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ideynrdtcx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ideynrdtcx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ideynrdtcx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ideynrdtcx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ideynrdtcx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ideynrdtcx .gt_left {\n  text-align: left;\n}\n\n#ideynrdtcx .gt_center {\n  text-align: center;\n}\n\n#ideynrdtcx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ideynrdtcx .gt_font_normal {\n  font-weight: normal;\n}\n\n#ideynrdtcx .gt_font_bold {\n  font-weight: bold;\n}\n\n#ideynrdtcx .gt_font_italic {\n  font-style: italic;\n}\n\n#ideynrdtcx .gt_super {\n  font-size: 65%;\n}\n\n#ideynrdtcx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ideynrdtcx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ideynrdtcx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ideynrdtcx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ideynrdtcx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ideynrdtcx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ideynrdtcx .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;OR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>OR</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Race_Ethnicity</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH White</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Hispanic-Latino</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.98</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.83, 1.16</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH American Indian/Alaskan Native</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.92</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.33, 2.25</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH Asian/Pacific Islander</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.14</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.97, 1.35</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.11</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH Black</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.43</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.24, 1.65</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.06</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.05, 1.07</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n## How to present odds ratios: Forest Plot Setup\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom.helpers)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'broom.helpers'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:gtsummary':\n\n    all_continuous\n```\n:::\n\n```{.r .cell-code}\nMLR_tidy = tidy_and_attach(multi_bc, conf.int=T, exponentiate = T) %>%\n  tidy_remove_intercept() %>%\n  tidy_add_reference_rows() %>%\n  tidy_add_estimate_to_reference_rows() %>%\n  tidy_add_term_labels()\nglimpse(MLR_tidy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 6\nColumns: 16\n$ term           <chr> \"Race_EthnicityNH White\", \"Race_EthnicityHispanic-Latin…\n$ variable       <chr> \"Race_Ethnicity\", \"Race_Ethnicity\", \"Race_Ethnicity\", \"…\n$ var_label      <chr> \"Race_Ethnicity\", \"Race_Ethnicity\", \"Race_Ethnicity\", \"…\n$ var_class      <chr> \"factor\", \"factor\", \"factor\", \"factor\", \"factor\", \"nume…\n$ var_type       <chr> \"categorical\", \"categorical\", \"categorical\", \"categoric…\n$ var_nlevels    <int> 5, 5, 5, 5, 5, NA\n$ contrasts      <chr> \"contr.treatment\", \"contr.treatment\", \"contr.treatment\"…\n$ contrasts_type <chr> \"treatment\", \"treatment\", \"treatment\", \"treatment\", \"tr…\n$ reference_row  <lgl> TRUE, FALSE, FALSE, FALSE, FALSE, NA\n$ label          <chr> \"NH White\", \"Hispanic-Latino\", \"NH American Indian/Alas…\n$ estimate       <dbl> 1.0000000, 0.9846940, 0.9178662, 1.1433526, 1.4300256, …\n$ std.error      <dbl> NA, 0.083653090, 0.484110085, 0.083796726, 0.071788616,…\n$ statistic      <dbl> NA, -0.1843845, -0.1770333, 1.5986877, 4.9825778, 17.81…\n$ p.value        <dbl> NA, 8.537118e-01, 8.594822e-01, 1.098900e-01, 6.274274e…\n$ conf.low       <dbl> NA, 0.8344282, 0.3262638, 0.9688184, 1.2414629, 1.05221…\n$ conf.high      <dbl> NA, 1.158411, 2.254643, 1.345732, 1.645053, 1.065538\n```\n:::\n:::\n\n\n\n## How to present odds ratios: Forest Plot Setup {.smaller}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMLR_tidy = MLR_tidy %>%\n  mutate(var_label = case_match(var_label, \n                               \"Race_Ethnicity\" ~ \"Race and ethnicity\", \n                               \"Age_c\" ~ \"\"), \n         label = case_match(label, \n                            \"NH White\" ~ \"Non-Hispanic White\", \n                            \"Hispanic-Latino\" ~ \"Hispanic-Latinx\", \n                            \"NH American Indian/Alaskan Native\" ~ \"Non-Hispanic American \\n Indian/Alaskan Native\", \n                            \"NH Asian/Pacific Islander\" ~ \"Non-Hispanic \\n Asian/Pacific Islander\",\n                            \"NH Black\" ~ \"Non-Hispanic Black\", \n                               \"Age_c\" ~ \"Age (yrs)\"))\n  # %>%\n  #                       fct_relevel(\"Age (yrs)\", \"Non-Hispanic \\n Asian/Pacific Islander\", \"Non-Hispanic American \\n Indian/Alaskan Native\", \"Non-Hispanic White\", \"Hispanic-Latinx\", \"Non-Hispanic Black\"))\n```\n:::\n\n\n\n## How to present odds ratios: Forest Plot\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMLR_tidy = MLR_tidy %>% mutate(label = fct_reorder(label, term))\n\nplot_MLR = ggplot(data=MLR_tidy, \n       aes(y=label, x=estimate, xmin=conf.low, xmax=conf.high)) + \n  geom_point(size = 3) +  geom_errorbarh(height=.2) + \n  \n  geom_vline(xintercept=1, color='#C2352F', linetype='dashed', alpha=1) +\n  theme_classic() +\n  \n  facet_grid(rows = vars(var_label), scales = \"free\",\n             space='free_y', switch = \"y\") + \n  \n  labs(x = \"OR (95% CI)\", \n       title = \"Odds ratios of Late Stage Breast Cancer Diagnosis\") +\n  theme(axis.title = element_text(size = 25), \n        axis.text = element_text(size = 25), \n        title = element_text(size = 25), \n        axis.title.y=element_blank(), \n        strip.text = element_text(size = 25), \n        strip.placement = \"outside\", \n        strip.background = element_blank())\n# plot_MLR\n```\n:::\n\n\n\n## How to present odds ratios: Forest Plot\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 row containing missing values or values outside the scale range\n(`geom_errorbarh()`).\n```\n:::\n\n::: {.cell-output-display}\n![](10_Multiple_logistic_regression_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=1440}\n:::\n:::\n\n\n\n## Adding odds ratios\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMLR_tidy = MLR_tidy %>% \n  mutate(estimate_r = round(estimate, 2), \n         conf.low_r = round(conf.low, 2), \n         conf.high_r = round(conf.high, 2), \n         OR_char = paste0(estimate_r, \" (\", conf.low_r, \", \", conf.high_r, \")\"), \n         OR_char = ifelse(reference_row == F | is.na(reference_row), OR_char, NA))\n```\n:::\n\n\n\n \n\n- \"Plot\" of the text for odds ratios estimates\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nOR_labs = ggplot(data=MLR_tidy, aes(y=label)) +\n  geom_text(aes(x = -1, label = OR_char), hjust = 0, size=8) +   \n  xlim(-1, 1) +\n  facet_grid(rows = vars(var_label), scales = \"free\",\n             space='free_y') +\n  theme_void() + \n    theme(strip.text = element_blank())\n```\n:::\n\n\n\n## Combine them!!\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(cowplot)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'cowplot'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:ggpubr':\n\n    get_legend\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:lubridate':\n\n    stamp\n```\n:::\n\n```{.r .cell-code}\nplot_grid(plot_MLR, OR_labs, ncol=2, align = \"h\", rel_widths = c(4, 1))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 row containing missing values or values outside the scale range\n(`geom_errorbarh()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 row containing missing values or values outside the scale range\n(`geom_text()`).\n```\n:::\n\n::: {.cell-output-display}\n![](10_Multiple_logistic_regression_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=1440}\n:::\n:::\n\n\n\n# Learning Objectives\n\n1.  Construct and fit a multiple logistic regression model\n\n2.  Test for significance of individual coefficients or sets of coefficients in multiple logistic regression\n\n3.  Estimate the predicted probability of our outcome using multiple logistic regression\n\n4.  Present the odds ratios for multiple variables at once\n\n::: lob\n5.  Interpret odds ratios for coefficients while adjusting for other variables\n:::\n\n## Multivariable Logistic Regression Model\n\n-   The multivariable model of logistic regression (called multiple logistic regression) is useful in that it statistically adjusts the estimated effect of each variable in the model\n\n \n\n-   Each estimated coefficient provides an estimate of the log odds *adjusting for all other variables included in the model*\n\n     \n    \n    -   The **adjusted odds ratio** can be different from or similar to the unadjusted odds ratio\n    \n     \n    \n    -   Comparing adjusted vs. unadjusted odds ratios can be a useful activity \n\n## Interpretation of Coefficients in MLR\n\n-   The interpretation of coefficients in multiple logistic regression is *essentially the same as the interpretation of coefficients in simple logistic regression*\n\n \n\n-   For interpretation, we need to \n\n    -   point out that these are adjusted estimates\n    -   provide a list of other variables in the model\n\n## Example: Race and Ethnicity and Age model fit (FIXED)\n\n::: columns\n::: {.column width=\"40%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"vveuieuclj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vveuieuclj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vveuieuclj thead, #vveuieuclj tbody, #vveuieuclj tfoot, #vveuieuclj tr, #vveuieuclj td, #vveuieuclj th {\n  border-style: none;\n}\n\n#vveuieuclj p {\n  margin: 0;\n  padding: 0;\n}\n\n#vveuieuclj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vveuieuclj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vveuieuclj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vveuieuclj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vveuieuclj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vveuieuclj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vveuieuclj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vveuieuclj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vveuieuclj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vveuieuclj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vveuieuclj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vveuieuclj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vveuieuclj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vveuieuclj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vveuieuclj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vveuieuclj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vveuieuclj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vveuieuclj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vveuieuclj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vveuieuclj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vveuieuclj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vveuieuclj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vveuieuclj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vveuieuclj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vveuieuclj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vveuieuclj .gt_left {\n  text-align: left;\n}\n\n#vveuieuclj .gt_center {\n  text-align: center;\n}\n\n#vveuieuclj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vveuieuclj .gt_font_normal {\n  font-weight: normal;\n}\n\n#vveuieuclj .gt_font_bold {\n  font-weight: bold;\n}\n\n#vveuieuclj .gt_font_italic {\n  font-style: italic;\n}\n\n#vveuieuclj .gt_super {\n  font-size: 65%;\n}\n\n#vveuieuclj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vveuieuclj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vveuieuclj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vveuieuclj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vveuieuclj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vveuieuclj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vveuieuclj .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;OR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>OR</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Race_Ethnicity</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH White</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Hispanic-Latino</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.98</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.83, 1.16</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH American Indian/Alaskan Native</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.92</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.33, 2.25</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH Asian/Pacific Islander</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.14</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.97, 1.35</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.11</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NH Black</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.43</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.24, 1.65</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.06</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.05, 1.07</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n::: {.column width=\"60%\"}\n-   The estimated odds of late stage breast cancer diagnosis for Hispanic-Latinx individuals is 0.98 times that of Non-Hispanic White individuals, controlling for age (95% CI: 0.83, 1.16).\n\n-   The estimated odds of late stage breast cancer diagnosis for Non-Hispanic American Indian/Alaskan Natives is 0.92 times that of Non-Hispanic White individuals, controlling for age (95% CI: 0.33, 2.25).\n\n-   The estimated odds of late stage breast cancer diagnosis for Non-Hispanic Asian/Pacific Islanders is 1.14 times that of Non-Hispanic White individuals, controlling for age (95% CI: 0.97, 1.35).\n\n-   The estimated odds of late stage breast cancer diagnosis for Non-Hispanic Black individuals is 1.43 times that of Non-Hispanic White individuals, controlling for age (95% CI: 1.24, 1.65).\n\n-   For every one year increase in age, there is an 6% increase in the estimated odds of late stage breast cancer diagnosis, adjusting for race and ethnicity (95% CI: 5%, 7%).\n:::\n:::\n\n# Learning Objectives\n\n\n",
    "supporting": [
      "10_Multiple_logistic_regression_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}