---
title: "Lab 1"
author: "Your name here!!!"
subtitle: "BSTA 513/613"
description: "Due: April 18, 2024 at 11pm"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
    self-contained: true
    embed-resources: true
    number-sections: true
    number-depth: 4
editor_options: 
  chunk_output_type: console
execute:
  freeze: auto  # re-render only when source changes
---

## Directions

### Grading

**This lab is graded out of 12 points.** The TAs will go through and grade your lab. They will make sure each section is complete and will follow the rubric below. I have instructed them that completion and clear effort is all that is needed to receive 100%. Nicky will go through the labs to give you feedback.

#### Rubric

|             | 4 points                                                                                                                                                                                                        | 3 points                                                                                                                                                                                       | 2 points                                                                                                                                                                                                   | 1 point                                                                                                                                                                                  | 0 points                                                                                                               |
|------------|------------|------------|------------|------------|------------|
| Formatting  | Lab submitted on Sakai with `.html` file. Answers are written in complete sentences with no major grammatical nor spelling errors. With little editing, the answer can be incorporated into the project report. | Lab submitted on Sakai with `.html` file. Answers are written in complete sentences with grammatical or spelling errors. With editing, the answer can be incorporated into the project report. | Lab submitted on Sakai with `.html` file. Answers are written in complete sentences with major grammatical or spelling errors. With major editing, the answer can be incorporated into the project report. | Lab submitted on Sakai with `.html` file. Answers are bulletted or do not use complete sentences.                                                                                        | Lab *not* submitted on Sakai with `.html` file.                                                                        |
| Code/Work   | All tasks are directly followed or answered. This includes all the needed code, in code chunks, with the requested output.                                                                                      | All tasks are directly followed or answered. This includes all the needed code, in code chunks, with the requested output. In a few tasks, the code syntax or output is not quite right.       | Most tasks are directly followed or answered. This includes all the needed code, in code chunks, with the requested output.                                                                                | Some tasks are directly followed or answered.This includes all the needed code, in code chunks, with the requested output. In a few tasks, the code syntax or output is not quite right. | More than a quarter of the tasks are not completed properly.                                                           |
| Reasoning\* | Answers demonstrate understanding of research context and investigation of the data. Answers are thoughtful and can be easily integrated into the final report.                                                 | Answers demonstrate understanding of research context and investigation of the data. Answers are thoughtful, but lack the clarity needed to easily integrate into the final report.            | Answers demonstrate some understanding of research context and investigation of the data. Answers are fairly thoughtful, but lack connection to the research.                                              | Answers demonstrate some understanding of research context and investigation of the data. Answers seem rushed and with minimal thought.                                                  | Answers lack understanding of research context and investigation of the data. Answers seem rushed and without thought. |

\*Applies to questions with reasoning

## Lab activities

### Reading and listening activities

### Familiarize yourself with the Well-Being and Basic Needs Survey

::: callout-important
#### Task

Answer the following questions using information on WBNS:

-   What is the motivation for this study? 
-   How could an analysis that looks at associations with food insecurity help facilitate change in policy?
-   Why is it important to study food insecurity?
:::

### File organization

::: callout-important
#### Task

Display your working directory using the `here` package and `here()` function.
:::

### Access and download the data

::: callout-important
#### Task

No task to report back on. Just make sure you have the data!
:::

### Decide on list of variables to focus on {#sec-pred}

::: callout-important
#### Task

List the 10 predictors that you plan to use in your analysis. Note which variables are numeric, binary, or multi-level categorical. 
:::

### Get a sense of how you would like to analyze the data

::: callout-important
#### Task

Complete the following statement to identify your research question: 

We will investigate the association between food insecurity and \_\_\_\_.
:::

### Save data for processing with `.Rda`

::: callout-important
#### Task

Include a screenshot showing the new `.Rda` file within your Data folder.
:::

### Getting data in working format

::: callout-important
#### Task

-   Select the variables that will be used in your analysis and make a new dataset. Include the code that you used.
-   Remove the parentheses with values that are in front of the category names.
:::

### Explore the outcome and predictors

::: callout-important
#### Task

-   To check that you have looked that the variables, please report the percent of respondents that were food insecure in the past 12 months.
-   List any categorical variables that have less than 100 observations in a group
:::

### Compile above work into an introduction

::: callout-important
#### Task

Write an introduction to the analysis. 
:::
