{
  "hash": "f68e24da85df1b96cfc38ad70210f085",
  "result": {
    "markdown": "---\ntitle: \"Lesson 7: Prediction and Visualization in Simple Logistic Regression\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#C2352F\"\ndate: \"04/17/2024\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"Lesson 7: Prediction and Visualization in Simple Logistic Regression\"\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n---\n\n::: {.cell}\n\n:::\n\n\n# Learning Objectives\n\n\n::: {.cell}\n<style type=\"text/css\">\n.reveal code {\n  max-height: 80% !important;\n}\n</style>\n:::\n\n\n## Predicted Probability\n\n-   We may be interested in predicting probability of having a late stage breast cancer diagnosis for a specific age.\n-   The predicted probability is the estimated probability of having the event for given values of covariate(s)\n-   In simple logistic regression, the predicted probability is: $$\\hat{\\pi}\\left(X\\right)=\\frac{\\exp({\\hat{\\beta}}_0+{\\hat{\\beta}}_1X)}{1+\\exp({\\hat{\\beta}}_0+{\\hat{\\beta}}_1X)}$$\n\n-   We can calculate this using the the `predict()` function like in BSTA 512\n\n## Confidence Interval of Predicted Probability\n\n-   Not as easy to construct\n-   I have searched around for a function that does this for us, but I cannot find one\n-   So we have to construct the confidence interval \"by hand\"\n-   There are a couple ways to do this\n\n    -   Construct the 95% confidence interval in the logit scale, then convert to probability scale\n    -   Use Normal approximation (if appropriate) to construct confidence interval in probability scale\n\n## 95% confidence interval in logit scale\n\n-   We start by predicting the log-odds and forming \n\n## Example: Late stage breast cancer diagnosis\n\n::: example\n::: ex-title\nPredicting probability of late stage breast cancer diagnosis\n:::\n::: ex-cont\nFor someone 50 years old, what is the predicted probability for late stage breast cancer diagnosis (with confidence intervals)?\n:::\n:::\n\n**Needed steps:**\n\n1. Calculate estimate and confidence interval\n2. Interpret results\n\n## Example: Late stage breast cancer diagnosis\n\n::: example\n::: ex-title\nPredicting probability of late stage breast cancer diagnosis\n:::\n::: ex-cont\nFor someone 50 years old, what is the predicted probability for late stage breast cancer diagnosis (with confidence intervals)?\n:::\n:::\n\n1. Calculate estimate and confidence interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbc_reg = glm(Late_stage_diag ~ Age_c, data = bc, family = binomial)\n\nnewdata = data.frame(Age_c = 60 - mean_age)\n\npred = predict(bc_reg, newdata = newdata, se.fit = T, type = \"response\")\n\nLL_CI = pred$fit - qnorm(1-0.05/2) * pred$se.fit\nUL_CI = pred$fit + qnorm(1-0.05/2) * pred$se.fit\n\nc(Pred = pred$fit, LL_CI, UL_CI) %>% round(digits=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPred.1      1      1 \n 0.252  0.243  0.261 \n```\n:::\n\n```{.r .cell-code}\npred1 = predict(bc_reg, newdata = newdata, se.fit = T, type = \"link\")\n\nLL_CI1 = pred1$fit - qnorm(1-0.05/2) * pred1$se.fit\nUL_CI1 = pred1$fit + qnorm(1-0.05/2) * pred1$se.fit\n\npred_link = c(Pred = pred1$fit, LL_CI1, UL_CI1)\n(exp(pred_link)/(1+exp(pred_link))) %>% round(., digits=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPred.1      1      1 \n 0.252  0.243  0.262 \n```\n:::\n\n```{.r .cell-code}\ninv.logit(pred_link) %>% round(., digits=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPred.1      1      1 \n 0.252  0.243  0.262 \n```\n:::\n:::\n\n\n## Example: Late stage breast cancer diagnosis\n\n::: example\n::: ex-title\nPredicting probability of late stage breast cancer diagnosis\n:::\n::: ex-cont\nFor someone 50 years old, what is the predicted probability for late stage breast cancer diagnosis (with confidence intervals)?\n:::\n:::\n\n2. Interpret results\n\nFor someone who is 60 years old, the predicted probability of late stage breast cancer diagnosis is 0.252 (95% CI: 0.243, 0.261).\n\n## Predicted Probability\n\n-   Predicted probability is NOT our predicted outcome\n\n    -   We cannot interpret it as the predicted Y for individuals with certain covariate values\n\n    -   Example: our predicted probability does not tell us that one individual is or is not diagnosed with late stage breast cancer\n\n-   The predicted probability is the estimate of the mean (i.e., proportion) of individuals at a certain age who are diagnosed with late stage breast cancer\n\n## Predicted outcome\n\n-   Typically, the predicted probability is the most important thing to use in a clinical setting\n\n-   If you ever need to predict the outcome itself, remember that the predicted probability can be used in a Bernoulli distribution to find the predicted outcome\n\n-   By putting it back through a Bernoulli distribution, we are re-introducing the random component of our observed outcome\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(8392)\nrbinom(n=1, size=1, prob = pred$fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nrbinom(n=10, size=1, prob = pred$fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 0 0 0 0 1 0 0 0 1 0\n```\n:::\n:::\n\n\n## We can also make a plot of all the predictions\n\n## Visualization\n\n\n::: {.cell}\n\n:::\n\n::: {.cell layout-align=\"left\"}\n::: {.cell-output-display}\n![](07_Pred_Viz_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='left' width=1920}\n:::\n:::\n\n\n## Visualization of ORs?\n",
    "supporting": [
      "07_Pred_Viz_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}