---
title: "Lesson 3: Measurement of Association for Contingency Tables"
author: "Nicky Wakim"
title-slide-attributes:
    data-background-color: "#C2352F"
date: "04/08/2024"
format: 
  revealjs:
    theme: "../simple_NW.scss"
    chalkboard: true
    slide-number: true
    show-slide-number: all
    width: 1955
    height: 1100
    footer: "Lesson 3: Measurement of Association for Contingency Tables"
    html-math-method: mathjax
    highlight-style: ayu
execute:
  echo: true
  freeze: auto  # re-render only when source changes
---

```{r}
#| echo: false

library(tidyverse)
library(gt)
library(janitor)
library(rstatix)
library(knitr)
library(gtsummary)
library(moderndive)
library(broom) 
library(here) 
```

## Poll Everywhere Question 1

# Learning Objectives

1. Understand the difference between testing for association and measuring association
2. Calculate the estimated risk difference, relative risk, and odds ratios, and their confidence intervals
3. Interpret the meaning of risk difference, relative risk, and odds ratios
4. Identify cases when it is appropriate to use risk difference, relative risk, or odds ratios
5. Expand work on contingency tables to evaluate the agreement or reproducibility using Cohen’s Kappa
6. Define confounders and construct three-way tables to demonstrate how they affect the relationship between two other variables
7. Calculate and test significance for adjusted odds ratio across confounder strata

# Learning Objectives 

## Review of Test of Association

Last week: learned some tests of association for contingency tables
• For studies with two independent samples
• General association (Chi-squared test, LRT, Fisher’s Exact test)
• Test of trends
• Cochran-Armitage test
• Mantel-Haenszel test
• Test of association does not provide an effective measure of association

## Test of association does not measure association

# Learning Objectives 

## Measures of Association

## Before we discuss each further...

# Learning Objectives 

## Risk Difference

## Risk Difference Example

## When is the risk difference misleading?

# Learning Objectives 

## Relative Risk (RR)

## Poll Everywhere Question 2

## Log-transformation of RR

## How do we get back to the RR scale?

## Relative Risk (RR)

## Relative Risk (RR) Example

# Learning Objectives 

## Odds (building up to Odds Ratio)

## Odds Ratio (OR)

## Poll Everywhere Question 3

## Odds Ratio (OR)

## Log-transformation of OR

## How do we get back to the OR scale?

## Odds Ratio (OR) Example

## Poll Everywhere Question 4

# Learning Objectives

## Relationship Between RR and OR

## Notes for Odds Ratios

## RR in retrospective case-control study

## OR in retrospective case-control study

## Which measurement should one use?

# Learning Objective

## Poll Everywhere Question 5

## Measuring Agreement

## Example: Beef Consumption in Survey

## Measuring Agreement

## Example: Beef Consumption in Survey

## Poll Everywhere Question 6

## Measuring Agreement Between Two Raters

## Testing Measuring Agreement

## Example: Beef Consumption

# Learning Objective

## Measurement of Association So Far

## Confounding

## Measurement of Association for Three-way Tables

## Example: Lung cancer and drinking status

## Types of confounders

## Poll Everywhere Question 7

## Example: Scottish Health Heart Study

## Confounding

# Learning Objective

## Adjusted OR: Mantel-Haenszel Method

## Stratified tables

## Adjusted OR: Mantel-Haenszel Method

## Example: Scottish Health Heart Study

## Poll Everywhere Question 7

## Cochran-Mantel-Haenszel (CMH) Test

## Example: Scottish Health Heart Study

# Learning Objectives 

