{
  "hash": "72d590df6055fdf4b0356f810aef364b",
  "result": {
    "markdown": "---\ntitle: \"Lesson 11: Interactions\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#C2352F\"\ndate: \"05/08/2024\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"Lesson 11: Interactions\"\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n:::\n\n\n\n# Learning Objectives\n\n1.    Connect understanding of confounding and interactions from linear regression to logistic regression.\n\n2.    Determine if an additional independent variable is a not a confounder nor effect modifier, is a confounder but not effect modifier, or is an effect modifier.\n\n3.    Calculate and interpret fitted interactions, including plotting the log-odds, predicted probability, and odds ratios. \n\n\n\n::: {.cell}\n<style type=\"text/css\">\n.reveal code {\n  max-height: 80% !important;\n}\n</style>\n:::\n\n\n\n\n# Learning Objectives\n\n::: lob\n1.    Connect understanding of confounding and interactions from linear regression to logistic regression.\n:::\n\n2.    Determine if an additional independent variable is a not a confounder nor effect modifier, is a confounder but not effect modifier, or is an effect modifier.\n\n3.    Calculate and interpret fitted interactions, including plotting the log-odds, predicted probability, and odds ratios. \n\n## Revisit from 512: What is a confounder?\n\n-   A confounding variable, or **confounder**, is a factor/variable that wholly or partially accounts for the observed effect of the risk factor on the outcome\n\n-   A confounder must be...\n\n    -   Related to the outcome Y, but not a consequence of Y\n    -   Related to the explanatory variable X, but not a consequence of X\n\n::: columns\n::: {.column width=\"10%\"}\n:::\n\n::: {.column width=\"80%\"}\n![](images/confounder.png){fig-align=\"center\" width=\"1200\"}\n:::\n:::\n\n## Including a confounder in the model\n\n-   In the following model we have two variables, $X_1$ and $X_2$\n\n$$Y= \\beta_0 + \\beta_1X_{1}+ \\beta_2X_{2} + \\epsilon$$\n\n-   And we assume that every level of the confounder, there is parallel slopes\n\n-   Note: to interpret $\\beta_1$, we did not specify any value of $X_2$; only specified that it be held constant\n\n    -   Implicit assumption: effect of $X_1$ is equal across all values of $X_2$\n\n-   The above model assumes that $X_{1}$ and $X_{2}$ do not *interact* (with respect to their effect on $Y$)\n\n    -   epidemiology: no \"effect modification\"\n\n    -   meaning the effect of $X_{1}$ is the same regardless of the values of $X_{2}$\n\n## What is an effect modifier?\n\n::: columns\n::: column\n-   An additional variable in the model\n\n    -   Outside of the main relationship between $Y$ and $X_1$ that we are studying\n\n-   An effect modifier will change the effect of $X_1$ on $Y$ depending on its value\n\n    -   Aka: as the effect modifier's values change, so does the association between $Y$ and $X_1$\n\n    -   So the coefficient estimating the relationship between $Y$ and $X_1$ changes with another variable\n:::\n\n::: column\n\n![](images/int_example2.png){fig-align=\"center\" width=\"497\"}\n\n![](images/int_example.png){fig-align=\"center\" width=\"474\"}\n:::\n:::\n\n## Confounding vs. Interaction\n\n::: columns\n::: {.column width=\"70%\"}\n-   [**Confounders:**]{style=\"color:#70AD47\"} The adjusted odds ratio for one variable adjusting for confounders can be quite different from unadjusted odds ratio\n\n    -   Adjusting for them is called *controlling for confounding.*\n\n \n\n\n-   [**Interactions:**]{style=\"color:#5B9BD5\"} When odds ratio for one variable is not constant over the levels of another variable, the two variables are said to have a statistical interaction (sometimes also called *effect modification*)\n\n    -   i.e.: the log odds of one variable is modified/changed with different values of the other variable\n    -   A variable is an **effect modifier** if it interacts with a risk factor\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"28%\"}\n::: proof1\n::: proof-title\nNote\n:::\n::: proof-cont\nPlease refer to [Lesson 11 from BSTA 512/612](https://nwakim.github.io/W2024_BSTA_512/lessons.html) – lots of information about these concepts!\n:::\n:::\n:::\n:::\n\n## How do we include an effect modifier in the model?\n\n-   Interactions!!\n\n-   We can incorporate interactions into our model through product terms: $$Y  =  \\beta_0 + \\beta_1X_{1}+ \\beta_2X_{2} +\n    \\beta_3X_{1}X_{2} + \\epsilon$$\n\n-   Terminology:\n\n    -   main effect parameters: $\\beta_1,\\beta_2$\n\n        -   The main effect models estimate the *average* $X_{1}$ and $X_{2}$ effects\n\n    -   interaction parameter: $\\beta_3$\n\n## Example of interaction\n\n::: columns\n::: {.column width=\"55%\"}\n-   In a cohort study of elderly people the chance of death (outcome) within 2 years was much higher for those who had previously suffered a hip fracture at the start of these 2 years, but the excess risk associated with a hip fracture was significantly higher for males vs. females\n\n \n\n-   This is an interaction between hip fracture status (yes/no) and sex (unclear if assigned at birth or no)\n\n \n\n-   Odds ratio for females > odds ratio for males\n\n:::\n::: {.column width=\"45%\"}\n![](images/int_ex.png){fig-align=\"center\"}\n:::\n:::\n\n## Types of interactions / non-interactions\n\n\nNo interaction and three potential effects of interaction between two covariates A and B: \n\n-   **No interaction** between A and B (confounder with no interaction)\n\n \n\n-   **Unilateralism:** exposure to A has no effect in the absence of exposure to B, but a considerable effect when B is present.\n\n \n\n-   **Synergism:** the effect of A is in the same direction, but stronger in the presence of B.\n\n \n\n-   **Antagonism:** the effect of A works in the opposite direction in the presence of B.\n\n\n## Types of interactions / non-interactions\n\n![](images/interactions.png){fig-align=\"center\"}\n\n## Poll Everywhere Question 1\n\n\n\n## Understand the interaction (1/3)\n\n::: columns\n::: {.column width=\"25%\"}\n-   Figure plots the logits (log-odds) under three different models showing the presence and absence of interaction. \n\n \n\n-   Response variable: CHD\n\n \n\n-   Risk factor: sex \n\n \n\n-   Covariate to be controlled: age\n\n\n:::\n::: {.column width=\"75%\"}\n![](images/understand_int1.png){fig-align=\"center\"}\n:::\n:::\n\n## Understand the interaction (2/3)\n\n::: columns\n::: {.column width=\"50%\"}\n-    [**If age does not interact with sex**]{style=\"color:#70AD47\"}, the distance between $l_2$ and $l_1$ is the log odds ratio for sex, controlling for age ($l_2 - l_1$) stays the same for all values of age.\n\n \n\n-   [**If age interacts with sex**]{style=\"color:#5B9BD5\"}, the distance between $l_3$ and $l_1$ is the log odds ratio for sex, controlling for age. \n\n    -   Age values need to be specified because ($l_3 - l_1$) differs for different values of age.\n\n    -   Must specify age when reporting odds ratio comparing sex\n\n\n\n:::\n::: {.column width=\"50%\"}\n\n \n\n![](images/understand_int2.png){fig-align=\"center\"}\n:::\n:::\n\n## Understand the interaction (3/3)\n\n::: columns\n::: {.column width=\"50%\"}\n-   In the real world, it is rare to see two completely parallel logit plots as we see $l_2$ and $l_1$\n\n    -   But we need to determine if the difference between $l_2$ and $l_3$ is important in the model\n\n \n\n-   We may not want to include the interaction term unless it is statistically significant and/or clinically meaningful\n\n \n\n-   Likelihood ratio test (or Wald test) may be used to test the significance of coefficients for variables of the interaction term\n\n:::\n::: {.column width=\"50%\"}\n\n \n\n![](images/understand_int2.png){fig-align=\"center\"}\n:::\n:::\n\n## Poll Everywhere Question 2\n\n## Summary\n\n-   In a logistic model with two covariates : $X_1$ (the risk factor, a binary variable) and $X_2$ (potential confounder/effect modifier)\n\n-   The role of $X_2$ can be one of the three possibilities:\n\n    1.    **Not a confounder nor effect modifier**, and not significantly associated with Y\n\n          -   No need to include $X_2$ in the model (for your dataset)\n\n          -   May still be nice to include if other literature in the field includes it\n          \n     \n\n    2.    It is a **confounder but not an effect modifier**. There is statistical adjustment but no statistical interaction\n\n          -   Should include $X_2$ in the model as main effect\n\n     \n\n    3.    It is an **effect modifier**. There is statistical interaction.\n\n          -   Should include $X_2$ in the model as main effect and interaction term  \n\n\n# Learning Objectives\n\n1.    Connect understanding of confounding and interactions from linear regression to logistic regression.\n\n::: lob\n2.    Determine if an additional independent variable is a not a confounder nor effect modifier, is a confounder but not effect modifier, or is an effect modifier.\n:::\n\n3.    Calculate and interpret fitted interactions, including plotting the log-odds, predicted probability, and odds ratios. \n\n## Deciding between confounder and effect modifier\n\n-   This is more of a model selection question (in coming lectures)\n\n-   But if we had a model with **only TWO covariates**, we could step through the following process:\n\n    1.  Test the interaction (of potential effect modifier): use a partial F-test to test if interaction term(s) explain enough variation compared to model without interaction\n\n        -   Recall that for two continuous covariates, we will **test a single coefficient**\n        -   For a binary and continuous covariate, we will **test a single coefficient**\n        -   For two binary categorical covariates, we will **test a single coefficient**\n        -   **For a multi-level categorical covariate (with any other type of covariate), we must test a group of coefficients!!**\n\n    2.  Then look at the main effect (or potential confounder)\n\n        -   If interaction already included, then automatically included as main effect (and thus not checked for confounding)\n\n        -   For variables that are not included in any interactions:\n\n            -   Check to see if they are confounders by seeing whether exclusion of the variable changes any of the main effect of the primary explanatory variable by more than 10%\n\n\n## Step 1: Testing the interaction\n\n-   We test with $\\alpha = 0.10$\n\n-   Follow the LRT procedure in [Lesson 6](https://nwakim.github.io/S2024_BSTA_513/lessons.html), slide 38\n\n-   Use the hypothesis tests for the specific covariate combo:\n\n::: columns\n\n::: column\n::: fact\n\n::: fact-title\nBinary & continuous variable\n:::\n\n::: fact-cont\nTesting a **single coefficient** for the interaction term using LRT comparing full model (with interaction) to reduced model (without interaction)\n:::\n\n:::\n:::\n\n::: column\n::: definition\n::: def-title\nBinary & continuous variables\n:::\n\n::: def-cont\nTesting a **group of coefficients** for the interaction term using LRT comparing full model (with interaction) to reduced model (without interaction)\n:::\n:::\n:::\n\n:::\n\n::: columns\n::: column\n::: proposition\n::: prop-title\nBinary & multi-level variable\n:::\n\n::: prop-cont\nTesting a **group of coefficients** for the interaction term using LRT comparing full model (with interaction) to reduced model (without interaction)\n:::\n:::\n:::\n\n::: column\n::: proof1\n::: proof-title\nTwo continuous variables\n:::\n\n::: proof-cont\nTesting a **single coefficient** for the interaction term using LRT comparing full model (with interaction) to reduced model (without interaction)\n:::\n:::\n:::\n\n:::\n\n## Poll Everywhere Question 2\n\n## Step 2: Testing a confounder\n\n-   If interaction already included:\n\n    -   Meaning: LRT showed evidence for alternative/full model\n    -   Then the variable is an effect modifier and we don't need to consider it as a confounder\n    -   Then automatically included as main effect (and thus not checked for confounding)\n\n-   For variables that are not included in any interactions:\n\n    -   Check to see if they are confounders\n    -   One way to do this is by seeing whether exclusion of the variable changes any of the main effect of the primary explanatory variable by more than 10%\n\n-   If the main effect of the primary explanatory variable changes by less than 10%, then the additional variable is neither an effect modifier nor a confounder\n\n    -   We leave the variable out of the model\n\n## Testing for percent change ( $\\Delta\\%$) in a coefficient\n\n-   Let's say we have $X_1$ and $X_2$, and we specifically want to see if $X_2$ is a confounder for $X_1$ (the explanatory variable or variable of interest)\n\n-   If we are only considering $X_1$ and $X_2$, then we need to run the following two models:\n\n    -   [**Fitted model 1 / reduced model (`mod1`): **]{style=\"color:#ED7D31\"} $\\text{logit}\\left(\\widehat\\pi(\\mathbf{X})\\right) = \\widehat\\beta_0 + \\widehat\\beta_1X_1$\n\n        -   We call the above $\\widehat\\beta_1$ the reduced model coefficient: $\\widehat\\beta_{1, \\text{mod1}}$ or $\\widehat\\beta_{1, \\text{red}}$\n\n    -   [**Fitted model 2 / full model (`mod2`): **]{style=\"color:#D6295E\"} $\\text{logit}\\left(\\widehat\\pi(\\mathbf{X})\\right) = \\widehat\\beta_0 + \\widehat\\beta_1X_1 +\\widehat\\beta_2X_2$\n\n        -   We call this $\\widehat\\beta_1$ the full model coefficient: $\\widehat\\beta_{1, \\text{mod2}}$ or $\\widehat\\beta_{1, \\text{full}}$\n\n::: columns\n::: {.column width=\"15%\"}\n:::\n\n::: {.column width=\"70%\"}\n::: fact\n::: fact-title\nCalculation for % change in coefficient\n:::\n\n::: fact-cont\n$$\n\\Delta\\% = 100\\% \\cdot\\frac{\\widehat\\beta_{1, \\text{mod1}} - \\widehat\\beta_{1, \\text{mod2}}}{\\widehat\\beta_{1, \\text{mod2}}} = 100\\% \\cdot \\frac{\\widehat\\beta_{1, \\text{red}} - \\widehat\\beta_{1, \\text{full}}}{\\widehat\\beta_{1, \\text{full}}}\n$$\n:::\n:::\n:::\n\n::: {.column width=\"15%\"}\n:::\n:::\n\n## Poll Everywhere Question 3\n\n## Example: GLOW Study\n\n-   From GLOW (Global Longitudinal Study of Osteoporosis in Women) study\n\n \n\n-   **Outcome variable:** any fracture in the first year of follow up (FRACTURE: 0 or 1)\n\n \n\n-   **Risk factor/variable of interest:** history of prior fracture (PRIORFRAC: 0 or 1)\n\n \n\n-   **Potential confounder or effect modifier:** age (AGE, a continuous variable)\n\n    -   Center age will be used! We will center around the rounded mean age of 69 years old\n    \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(aplore3)\nmean_age = mean(glow500$age) %>% round()\nglow = glow500 %>% mutate(age_c = age - mean_age)\n```\n:::\n\n\n\n## Example: GLOW Study: Try to visual the sample proportions\n\n-   Back in BSTA 512/612, we could visual the data to get a sense if there was an interaction before fitting a model\n\n \n\n-   With a binary outcome, this is a little harder\n\n    -   We could use a contingency table or plot proportions of the outcome\n\n    -   Hard to do this when our potential confounder or effect modifier is continuous \n\n## Example: GLOW Study: Calculate the proportions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglow2 = glow %>% \n  group_by(age, priorfrac, fracture) %>% # last one needs to be outcome\n  summarise(n = n()) %>%\n  mutate(freq = n / sum(n)) %>% # takes the proportion of yes/no\n  filter(fracture == \"Yes\") # Filtering so only \"success\" shown\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'age', 'priorfrac'. You can override using\nthe `.groups` argument.\n```\n:::\n\n```{.r .cell-code}\n  #filter(freq != 1 | n != 1) \n\nhead(glow2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n# Groups:   age, priorfrac [6]\n    age priorfrac fracture     n  freq\n  <int> <fct>     <fct>    <int> <dbl>\n1    56 No        Yes          3 0.15 \n2    56 Yes       Yes          1 1    \n3    57 No        Yes          3 0.158\n4    57 Yes       Yes          1 0.333\n5    58 No        Yes          3 0.15 \n6    59 Yes       Yes          2 0.667\n```\n:::\n:::\n\n\n\n## Example: GLOW Study: Plot the proportions {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = glow2, aes(y = freq, x = age, color = priorfrac)) +\n  geom_point() + ylim(0, 1) + geom_smooth(se = F) +\n  labs(x = \"Age (years)\", y = \"Proportion of fracture\", \n       color = \"Prior fracture\", title = \"Sample proportion of fracture by age and prior fracture\") +\n  theme(axis.title = element_text(size = 18), axis.text = element_text(size = 18), \n        title = element_text(size = 18), legend.text=element_text(size=18))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](11_Interactions_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=864}\n:::\n:::\n\n\n\n-   From sample proportions, looks like age and prior fracture may have an interaction!\n\n## Example: GLOW Study\n\nWe also *could jump right into model fitting* (connecting to the three possible roles of Age):\n\n-   [**Model 1: **]{style=\"color:#F6C342\"} Age not included \n\n$$\\text{logit}\\left(\\pi(\\mathbf{X})\\right) = \\beta_0 + \\beta_1\\cdot I(\\text{PF})$$\n\n \n\n-   [**Model 2: **]{style=\"color:#5B9BD5\"} Age as main effect (age as potential confounder) \n\n$$\\text{logit}\\left(\\pi(\\mathbf{X})\\right) = \\beta_0 + \\beta_1\\cdot I(\\text{PF}) +\\beta_2\\cdot Age$$\n\n \n\n-   [**Model 3: **]{style=\"color:#70AD47\"} Age and Prior Fracture interaction (age as potential effect modifier) \n\n$$\\text{logit}\\left(\\pi(\\mathbf{X})\\right) = \\beta_0 + \\beta_1\\cdot I(\\text{PF}) +\\beta_2\\cdot Age + \\beta_3 \\cdot I(\\text{PF}) \\cdot Age$$\n\n## Example: GLOW Study\n\nWe also *could jump right into model fitting* (connecting to the three possible roles of Age):\n\n-   [**Model 1: **]{style=\"color:#F6C342\"} Age not included \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglow_m1 = glm(fracture ~ priorfrac, \n              data = glow, family = binomial)\n```\n:::\n\n\n\n \n\n-   [**Model 2: **]{style=\"color:#5B9BD5\"} Age as main effect (age as potential confounder) \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglow_m2 = glm(fracture ~ priorfrac + age_c, \n              data = glow, family = binomial)\n```\n:::\n\n\n\n \n\n-   [**Model 3: **]{style=\"color:#70AD47\"} Age and Prior Fracture interaction (age as potential effect modifier) \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglow_m3 = glm(fracture ~ priorfrac + age_c + priorfrac*age_c, \n              data = glow, family = binomial)\n```\n:::\n\n\n\n## Example: GLOW Study: Age an effect modifier or confounder?\n\n::: columns\n::: {.column width=\"60%\"}\n\n-   [**Model 1: **]{style=\"color:#F6C342\"} Age not included \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"efmpueowef\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#efmpueowef table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#efmpueowef thead, #efmpueowef tbody, #efmpueowef tfoot, #efmpueowef tr, #efmpueowef td, #efmpueowef th {\n  border-style: none;\n}\n\n#efmpueowef p {\n  margin: 0;\n  padding: 0;\n}\n\n#efmpueowef .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#efmpueowef .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#efmpueowef .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#efmpueowef .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#efmpueowef .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#efmpueowef .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#efmpueowef .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#efmpueowef .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#efmpueowef .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#efmpueowef .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#efmpueowef .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#efmpueowef .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#efmpueowef .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#efmpueowef .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#efmpueowef .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#efmpueowef .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#efmpueowef .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#efmpueowef .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#efmpueowef .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#efmpueowef .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#efmpueowef .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#efmpueowef .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#efmpueowef .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#efmpueowef .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#efmpueowef .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#efmpueowef .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#efmpueowef .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#efmpueowef .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#efmpueowef .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#efmpueowef .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#efmpueowef .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#efmpueowef .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#efmpueowef .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#efmpueowef .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#efmpueowef .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#efmpueowef .gt_left {\n  text-align: left;\n}\n\n#efmpueowef .gt_center {\n  text-align: center;\n}\n\n#efmpueowef .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#efmpueowef .gt_font_normal {\n  font-weight: normal;\n}\n\n#efmpueowef .gt_font_bold {\n  font-weight: bold;\n}\n\n#efmpueowef .gt_font_italic {\n  font-style: italic;\n}\n\n#efmpueowef .gt_super {\n  font-size: 65%;\n}\n\n#efmpueowef .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#efmpueowef .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#efmpueowef .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#efmpueowef .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#efmpueowef .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#efmpueowef .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#efmpueowef .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.417</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.130</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−10.859</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.679</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.167</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.064</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.223</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.769</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.626</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.502</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n\n-   [**Model 2: **]{style=\"color:#5B9BD5\"} Age as main effect (age as potential confounder) \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"ntgcevkcje\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ntgcevkcje table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ntgcevkcje thead, #ntgcevkcje tbody, #ntgcevkcje tfoot, #ntgcevkcje tr, #ntgcevkcje td, #ntgcevkcje th {\n  border-style: none;\n}\n\n#ntgcevkcje p {\n  margin: 0;\n  padding: 0;\n}\n\n#ntgcevkcje .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ntgcevkcje .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ntgcevkcje .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ntgcevkcje .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ntgcevkcje .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ntgcevkcje .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ntgcevkcje .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ntgcevkcje .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ntgcevkcje .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ntgcevkcje .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ntgcevkcje .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ntgcevkcje .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ntgcevkcje .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ntgcevkcje .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ntgcevkcje .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ntgcevkcje .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ntgcevkcje .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ntgcevkcje .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ntgcevkcje .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ntgcevkcje .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ntgcevkcje .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ntgcevkcje .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ntgcevkcje .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ntgcevkcje .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ntgcevkcje .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ntgcevkcje .gt_left {\n  text-align: left;\n}\n\n#ntgcevkcje .gt_center {\n  text-align: center;\n}\n\n#ntgcevkcje .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ntgcevkcje .gt_font_normal {\n  font-weight: normal;\n}\n\n#ntgcevkcje .gt_font_bold {\n  font-weight: bold;\n}\n\n#ntgcevkcje .gt_font_italic {\n  font-style: italic;\n}\n\n#ntgcevkcje .gt_super {\n  font-size: 65%;\n}\n\n#ntgcevkcje .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ntgcevkcje .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ntgcevkcje .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ntgcevkcje .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ntgcevkcje .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ntgcevkcje .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ntgcevkcje .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.372</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.132</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−10.407</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.637</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.120</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.839</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.234</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.582</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.378</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.297</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.041</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.012</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.382</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.001</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.017</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.065</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n\n-   [**Model 3: **]{style=\"color:#70AD47\"} Age and Prior Fracture interaction (age as potential effect modifier) \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"ayfrelurcz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ayfrelurcz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ayfrelurcz thead, #ayfrelurcz tbody, #ayfrelurcz tfoot, #ayfrelurcz tr, #ayfrelurcz td, #ayfrelurcz th {\n  border-style: none;\n}\n\n#ayfrelurcz p {\n  margin: 0;\n  padding: 0;\n}\n\n#ayfrelurcz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ayfrelurcz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ayfrelurcz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ayfrelurcz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ayfrelurcz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ayfrelurcz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ayfrelurcz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ayfrelurcz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ayfrelurcz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ayfrelurcz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ayfrelurcz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ayfrelurcz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ayfrelurcz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ayfrelurcz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ayfrelurcz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ayfrelurcz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ayfrelurcz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ayfrelurcz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ayfrelurcz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ayfrelurcz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ayfrelurcz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ayfrelurcz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ayfrelurcz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ayfrelurcz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ayfrelurcz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ayfrelurcz .gt_left {\n  text-align: left;\n}\n\n#ayfrelurcz .gt_center {\n  text-align: center;\n}\n\n#ayfrelurcz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ayfrelurcz .gt_font_normal {\n  font-weight: normal;\n}\n\n#ayfrelurcz .gt_font_bold {\n  font-weight: bold;\n}\n\n#ayfrelurcz .gt_font_italic {\n  font-style: italic;\n}\n\n#ayfrelurcz .gt_super {\n  font-size: 65%;\n}\n\n#ayfrelurcz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ayfrelurcz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ayfrelurcz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ayfrelurcz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ayfrelurcz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ayfrelurcz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ayfrelurcz .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.376</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.134</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−10.270</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.646</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.120</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.002</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.240</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.184</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.530</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.471</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.063</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.015</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.043</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.032</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.093</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes:age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−0.057</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.025</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−2.294</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.022</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−0.107</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−0.008</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n::: {.column width=\"40%\"}\n\n:::\n\n:::\n\n## Example: GLOW Study: Age an effect modifier or confounder?\n\n::: columns\n::: {.column width=\"60%\"}\n\n-   [**Model 1: **]{style=\"color:#F6C342\"} Age not included \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"revojxjzjh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#revojxjzjh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#revojxjzjh thead, #revojxjzjh tbody, #revojxjzjh tfoot, #revojxjzjh tr, #revojxjzjh td, #revojxjzjh th {\n  border-style: none;\n}\n\n#revojxjzjh p {\n  margin: 0;\n  padding: 0;\n}\n\n#revojxjzjh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#revojxjzjh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#revojxjzjh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#revojxjzjh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#revojxjzjh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#revojxjzjh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#revojxjzjh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#revojxjzjh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#revojxjzjh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#revojxjzjh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#revojxjzjh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#revojxjzjh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#revojxjzjh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#revojxjzjh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#revojxjzjh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#revojxjzjh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#revojxjzjh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#revojxjzjh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#revojxjzjh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#revojxjzjh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#revojxjzjh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#revojxjzjh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#revojxjzjh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#revojxjzjh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#revojxjzjh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#revojxjzjh .gt_left {\n  text-align: left;\n}\n\n#revojxjzjh .gt_center {\n  text-align: center;\n}\n\n#revojxjzjh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#revojxjzjh .gt_font_normal {\n  font-weight: normal;\n}\n\n#revojxjzjh .gt_font_bold {\n  font-weight: bold;\n}\n\n#revojxjzjh .gt_font_italic {\n  font-style: italic;\n}\n\n#revojxjzjh .gt_super {\n  font-size: 65%;\n}\n\n#revojxjzjh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#revojxjzjh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#revojxjzjh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#revojxjzjh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#revojxjzjh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#revojxjzjh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#revojxjzjh .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.417</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.130</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−10.859</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.679</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.167</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.064</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.223</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.769</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.626</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.502</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n\n-   [**Model 2: **]{style=\"color:#5B9BD5\"} Age as main effect (age as potential confounder) \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"dpkgwvuufj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dpkgwvuufj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dpkgwvuufj thead, #dpkgwvuufj tbody, #dpkgwvuufj tfoot, #dpkgwvuufj tr, #dpkgwvuufj td, #dpkgwvuufj th {\n  border-style: none;\n}\n\n#dpkgwvuufj p {\n  margin: 0;\n  padding: 0;\n}\n\n#dpkgwvuufj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dpkgwvuufj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dpkgwvuufj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dpkgwvuufj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dpkgwvuufj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dpkgwvuufj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dpkgwvuufj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dpkgwvuufj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dpkgwvuufj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dpkgwvuufj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dpkgwvuufj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dpkgwvuufj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dpkgwvuufj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dpkgwvuufj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dpkgwvuufj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dpkgwvuufj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dpkgwvuufj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dpkgwvuufj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dpkgwvuufj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dpkgwvuufj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dpkgwvuufj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dpkgwvuufj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dpkgwvuufj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dpkgwvuufj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dpkgwvuufj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dpkgwvuufj .gt_left {\n  text-align: left;\n}\n\n#dpkgwvuufj .gt_center {\n  text-align: center;\n}\n\n#dpkgwvuufj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dpkgwvuufj .gt_font_normal {\n  font-weight: normal;\n}\n\n#dpkgwvuufj .gt_font_bold {\n  font-weight: bold;\n}\n\n#dpkgwvuufj .gt_font_italic {\n  font-style: italic;\n}\n\n#dpkgwvuufj .gt_super {\n  font-size: 65%;\n}\n\n#dpkgwvuufj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dpkgwvuufj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dpkgwvuufj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dpkgwvuufj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dpkgwvuufj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dpkgwvuufj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dpkgwvuufj .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.372</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.132</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−10.407</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.637</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.120</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.839</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.234</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.582</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.378</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.297</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.041</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.012</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.382</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.001</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.017</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.065</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n\n-   [**Model 3: **]{style=\"color:#70AD47\"} Age and Prior Fracture interaction (age as potential effect modifier) \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"vawykxgohw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vawykxgohw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vawykxgohw thead, #vawykxgohw tbody, #vawykxgohw tfoot, #vawykxgohw tr, #vawykxgohw td, #vawykxgohw th {\n  border-style: none;\n}\n\n#vawykxgohw p {\n  margin: 0;\n  padding: 0;\n}\n\n#vawykxgohw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vawykxgohw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vawykxgohw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vawykxgohw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vawykxgohw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vawykxgohw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vawykxgohw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vawykxgohw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vawykxgohw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vawykxgohw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vawykxgohw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vawykxgohw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vawykxgohw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vawykxgohw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vawykxgohw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vawykxgohw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vawykxgohw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vawykxgohw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vawykxgohw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vawykxgohw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vawykxgohw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vawykxgohw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vawykxgohw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vawykxgohw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vawykxgohw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vawykxgohw .gt_left {\n  text-align: left;\n}\n\n#vawykxgohw .gt_center {\n  text-align: center;\n}\n\n#vawykxgohw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vawykxgohw .gt_font_normal {\n  font-weight: normal;\n}\n\n#vawykxgohw .gt_font_bold {\n  font-weight: bold;\n}\n\n#vawykxgohw .gt_font_italic {\n  font-style: italic;\n}\n\n#vawykxgohw .gt_super {\n  font-size: 65%;\n}\n\n#vawykxgohw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vawykxgohw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vawykxgohw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vawykxgohw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vawykxgohw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vawykxgohw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vawykxgohw .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.376</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.134</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−10.270</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.646</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.120</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.002</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.240</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.184</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.530</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.471</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.063</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.015</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.043</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.032</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.093</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes:age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−0.057</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.025</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−2.294</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.022</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−0.107</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−0.008</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n::: {.column width=\"40%\"}\n-   Is age an effect modifier?\n\n    -   Test the significance of the interaction term in Model 3\n    \n    -   We can use the Wald test or LRT\n\n \n\n-   If not an effect modifier, check the change in coefficient for prior fracture between Model 1 and Model 2\n\n \n\n:::\n\n:::\n\n## Example: GLOW Study: Age an effect modifier or confounder?\n\n::: columns\n::: {.column width=\"60%\"}\n\n-   [**Model 1: **]{style=\"color:#F6C342\"} Age not included \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"lfnprbprnr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lfnprbprnr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lfnprbprnr thead, #lfnprbprnr tbody, #lfnprbprnr tfoot, #lfnprbprnr tr, #lfnprbprnr td, #lfnprbprnr th {\n  border-style: none;\n}\n\n#lfnprbprnr p {\n  margin: 0;\n  padding: 0;\n}\n\n#lfnprbprnr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lfnprbprnr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lfnprbprnr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lfnprbprnr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lfnprbprnr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lfnprbprnr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lfnprbprnr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lfnprbprnr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lfnprbprnr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lfnprbprnr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lfnprbprnr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lfnprbprnr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lfnprbprnr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lfnprbprnr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lfnprbprnr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lfnprbprnr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lfnprbprnr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lfnprbprnr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lfnprbprnr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lfnprbprnr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lfnprbprnr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lfnprbprnr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lfnprbprnr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lfnprbprnr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lfnprbprnr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lfnprbprnr .gt_left {\n  text-align: left;\n}\n\n#lfnprbprnr .gt_center {\n  text-align: center;\n}\n\n#lfnprbprnr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lfnprbprnr .gt_font_normal {\n  font-weight: normal;\n}\n\n#lfnprbprnr .gt_font_bold {\n  font-weight: bold;\n}\n\n#lfnprbprnr .gt_font_italic {\n  font-style: italic;\n}\n\n#lfnprbprnr .gt_super {\n  font-size: 65%;\n}\n\n#lfnprbprnr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lfnprbprnr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lfnprbprnr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lfnprbprnr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lfnprbprnr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lfnprbprnr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lfnprbprnr .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.417</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.130</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−10.859</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.679</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.167</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.064</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.223</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.769</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.626</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.502</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n\n-   [**Model 2: **]{style=\"color:#5B9BD5\"} Age as main effect (age as potential confounder) \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"sinrbwydry\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#sinrbwydry table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sinrbwydry thead, #sinrbwydry tbody, #sinrbwydry tfoot, #sinrbwydry tr, #sinrbwydry td, #sinrbwydry th {\n  border-style: none;\n}\n\n#sinrbwydry p {\n  margin: 0;\n  padding: 0;\n}\n\n#sinrbwydry .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sinrbwydry .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sinrbwydry .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sinrbwydry .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sinrbwydry .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sinrbwydry .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sinrbwydry .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sinrbwydry .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sinrbwydry .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sinrbwydry .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sinrbwydry .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sinrbwydry .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sinrbwydry .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sinrbwydry .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sinrbwydry .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sinrbwydry .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sinrbwydry .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sinrbwydry .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sinrbwydry .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sinrbwydry .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sinrbwydry .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sinrbwydry .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sinrbwydry .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sinrbwydry .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sinrbwydry .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sinrbwydry .gt_left {\n  text-align: left;\n}\n\n#sinrbwydry .gt_center {\n  text-align: center;\n}\n\n#sinrbwydry .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sinrbwydry .gt_font_normal {\n  font-weight: normal;\n}\n\n#sinrbwydry .gt_font_bold {\n  font-weight: bold;\n}\n\n#sinrbwydry .gt_font_italic {\n  font-style: italic;\n}\n\n#sinrbwydry .gt_super {\n  font-size: 65%;\n}\n\n#sinrbwydry .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sinrbwydry .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sinrbwydry .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sinrbwydry .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sinrbwydry .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sinrbwydry .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sinrbwydry .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.372</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.132</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−10.407</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.637</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.120</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.839</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.234</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.582</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.378</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.297</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.041</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.012</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.382</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.001</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.017</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.065</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n\n-   [**Model 3: **]{style=\"color:#70AD47\"} Age and Prior Fracture interaction (age as potential effect modifier) \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"sjrmlxfahf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#sjrmlxfahf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sjrmlxfahf thead, #sjrmlxfahf tbody, #sjrmlxfahf tfoot, #sjrmlxfahf tr, #sjrmlxfahf td, #sjrmlxfahf th {\n  border-style: none;\n}\n\n#sjrmlxfahf p {\n  margin: 0;\n  padding: 0;\n}\n\n#sjrmlxfahf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sjrmlxfahf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sjrmlxfahf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sjrmlxfahf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sjrmlxfahf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sjrmlxfahf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sjrmlxfahf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sjrmlxfahf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sjrmlxfahf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sjrmlxfahf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sjrmlxfahf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sjrmlxfahf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sjrmlxfahf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sjrmlxfahf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sjrmlxfahf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sjrmlxfahf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sjrmlxfahf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sjrmlxfahf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sjrmlxfahf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sjrmlxfahf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sjrmlxfahf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sjrmlxfahf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sjrmlxfahf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sjrmlxfahf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sjrmlxfahf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sjrmlxfahf .gt_left {\n  text-align: left;\n}\n\n#sjrmlxfahf .gt_center {\n  text-align: center;\n}\n\n#sjrmlxfahf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sjrmlxfahf .gt_font_normal {\n  font-weight: normal;\n}\n\n#sjrmlxfahf .gt_font_bold {\n  font-weight: bold;\n}\n\n#sjrmlxfahf .gt_font_italic {\n  font-style: italic;\n}\n\n#sjrmlxfahf .gt_super {\n  font-size: 65%;\n}\n\n#sjrmlxfahf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sjrmlxfahf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sjrmlxfahf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sjrmlxfahf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sjrmlxfahf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sjrmlxfahf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sjrmlxfahf .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.376</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.134</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−10.270</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.646</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.120</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.002</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.240</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.184</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.530</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.471</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.063</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.015</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.043</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.032</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.093</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes:age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−0.057</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.025</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−2.294</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.022</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−0.107</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−0.008</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n::: {.column width=\"40%\"}\n-   Is age an effect modifier?\n\n    -   Test the significance of the interaction term in Model 3\n    \n    -   We can use the Wald test or LRT\n\n \n\n-   If not an effect modifier, check the change in coefficient for prior fracture between Model 1 and Model 2\n\n \n\n::: box2\n**Short version of testing the interaction:** Wald statistic for the interaction coefficient, $\\widehat{\\beta}_3$, is statistically significant with $p= 0.022$. Thus, there is evidence of a statistical interaction between these age and prior fracture.\n:::\n\n:::\n\n:::\n\n## Poll Everywhere Question 4\n\n## Please please please reference your work from BSTA 512/612\n\n-   We had lessons and homeworks dedicated to this process!\n\n-   The process will be the same!\n\n    -   Only differences are t-test and F-test are replaced by Wald test and Likelihood ratio test, respectively!!\n    \n# Learning Objectives\n\n1.    Connect understanding of confounding and interactions from linear regression to logistic regression.\n\n2.    Determine if an additional independent variable is a not a confounder nor effect modifier, is a confounder but not effect modifier, or is an effect modifier.\n\n::: lob\n3.    Calculate and interpret fitted interactions, including plotting the log-odds, predicted probability, and odds ratios. \n:::\n\n## Example: GLOW Study\n\n-   Age is an **effect modifier** of prior fracture\n\n \n\n-   When a covariate is an **effect modifier**, its status as a confounder is of secondary importance since the estimate of the effect of the risk factor depends on the specific value of the covariate\n\n \n\n-   Must summarize the effect of prior fracture on current fracture *by age* \n\n    -   Cannot summarize as a single (log) odds ratio\n\n## Example: GLOW – Interaction interpretation\n\n-   [**Model 3: **]{style=\"color:#70AD47\"} $$\\begin{aligned} \\text{logit}\\left(\\widehat\\pi(\\mathbf{X})\\right) & = \\widehat\\beta_0 &+ &\\widehat\\beta_1\\cdot I(\\text{PF}) & + &\\widehat\\beta_2\\cdot Age& + &\\widehat\\beta_3 \\cdot I(\\text{PF}) \\cdot Age \\\\  \n\\text{logit}\\left(\\widehat\\pi(\\mathbf{X})\\right) & = -1.376 &+ &1.002\\cdot I(\\text{PF})& + &0.063\\cdot Age& -&0.057 \\cdot I(\\text{PF}) \\cdot Age\n\\end{aligned}$$\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"wupypojkst\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wupypojkst table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wupypojkst thead, #wupypojkst tbody, #wupypojkst tfoot, #wupypojkst tr, #wupypojkst td, #wupypojkst th {\n  border-style: none;\n}\n\n#wupypojkst p {\n  margin: 0;\n  padding: 0;\n}\n\n#wupypojkst .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wupypojkst .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wupypojkst .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wupypojkst .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wupypojkst .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wupypojkst .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wupypojkst .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wupypojkst .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wupypojkst .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wupypojkst .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wupypojkst .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wupypojkst .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wupypojkst .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wupypojkst .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wupypojkst .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wupypojkst .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wupypojkst .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wupypojkst .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wupypojkst .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wupypojkst .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wupypojkst .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wupypojkst .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wupypojkst .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wupypojkst .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wupypojkst .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wupypojkst .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wupypojkst .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wupypojkst .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wupypojkst .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wupypojkst .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wupypojkst .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wupypojkst .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wupypojkst .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wupypojkst .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wupypojkst .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wupypojkst .gt_left {\n  text-align: left;\n}\n\n#wupypojkst .gt_center {\n  text-align: center;\n}\n\n#wupypojkst .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wupypojkst .gt_font_normal {\n  font-weight: normal;\n}\n\n#wupypojkst .gt_font_bold {\n  font-weight: bold;\n}\n\n#wupypojkst .gt_font_italic {\n  font-style: italic;\n}\n\n#wupypojkst .gt_super {\n  font-size: 65%;\n}\n\n#wupypojkst .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wupypojkst .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wupypojkst .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wupypojkst .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wupypojkst .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wupypojkst .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wupypojkst .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.376</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.134</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−10.270</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.646</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.120</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.002</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.240</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.184</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.530</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.471</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.063</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.015</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.043</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.032</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.093</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes:age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−0.057</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.025</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−2.294</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.022</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−0.107</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−0.008</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n## Example: GLOW – Interaction interpretation\n\n::: columns\n::: {.column width=\"40%\"}\n-   Model 3 estimated **coefficients**:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"ocfxuwkiqc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ocfxuwkiqc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ocfxuwkiqc thead, #ocfxuwkiqc tbody, #ocfxuwkiqc tfoot, #ocfxuwkiqc tr, #ocfxuwkiqc td, #ocfxuwkiqc th {\n  border-style: none;\n}\n\n#ocfxuwkiqc p {\n  margin: 0;\n  padding: 0;\n}\n\n#ocfxuwkiqc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 32px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ocfxuwkiqc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ocfxuwkiqc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ocfxuwkiqc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ocfxuwkiqc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ocfxuwkiqc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ocfxuwkiqc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ocfxuwkiqc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ocfxuwkiqc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ocfxuwkiqc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ocfxuwkiqc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ocfxuwkiqc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ocfxuwkiqc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ocfxuwkiqc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ocfxuwkiqc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ocfxuwkiqc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ocfxuwkiqc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ocfxuwkiqc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ocfxuwkiqc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ocfxuwkiqc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ocfxuwkiqc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ocfxuwkiqc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ocfxuwkiqc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ocfxuwkiqc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ocfxuwkiqc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ocfxuwkiqc .gt_left {\n  text-align: left;\n}\n\n#ocfxuwkiqc .gt_center {\n  text-align: center;\n}\n\n#ocfxuwkiqc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ocfxuwkiqc .gt_font_normal {\n  font-weight: normal;\n}\n\n#ocfxuwkiqc .gt_font_bold {\n  font-weight: bold;\n}\n\n#ocfxuwkiqc .gt_font_italic {\n  font-style: italic;\n}\n\n#ocfxuwkiqc .gt_super {\n  font-size: 65%;\n}\n\n#ocfxuwkiqc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ocfxuwkiqc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ocfxuwkiqc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ocfxuwkiqc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ocfxuwkiqc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ocfxuwkiqc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ocfxuwkiqc .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.376</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.646</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−1.120</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.002</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.530</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.471</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.063</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.032</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.093</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes:age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−0.057</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.022</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−0.107</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">−0.008</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n-   Model 3 estimated **odds ratios**:\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"itupnxjkde\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#itupnxjkde table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#itupnxjkde thead, #itupnxjkde tbody, #itupnxjkde tfoot, #itupnxjkde tr, #itupnxjkde td, #itupnxjkde th {\n  border-style: none;\n}\n\n#itupnxjkde p {\n  margin: 0;\n  padding: 0;\n}\n\n#itupnxjkde .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 32px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#itupnxjkde .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#itupnxjkde .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#itupnxjkde .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#itupnxjkde .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#itupnxjkde .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#itupnxjkde .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#itupnxjkde .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#itupnxjkde .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#itupnxjkde .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#itupnxjkde .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#itupnxjkde .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#itupnxjkde .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#itupnxjkde .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#itupnxjkde .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itupnxjkde .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#itupnxjkde .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#itupnxjkde .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#itupnxjkde .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itupnxjkde .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#itupnxjkde .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itupnxjkde .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#itupnxjkde .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itupnxjkde .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#itupnxjkde .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itupnxjkde .gt_left {\n  text-align: left;\n}\n\n#itupnxjkde .gt_center {\n  text-align: center;\n}\n\n#itupnxjkde .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#itupnxjkde .gt_font_normal {\n  font-weight: normal;\n}\n\n#itupnxjkde .gt_font_bold {\n  font-weight: bold;\n}\n\n#itupnxjkde .gt_font_italic {\n  font-style: italic;\n}\n\n#itupnxjkde .gt_super {\n  font-size: 65%;\n}\n\n#itupnxjkde .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#itupnxjkde .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#itupnxjkde .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#itupnxjkde .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#itupnxjkde .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#itupnxjkde .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#itupnxjkde .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.25</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.19</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.33</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">2.72</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.70</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">4.35</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.06</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.03</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.10</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">priorfracYes:age_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.94</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.02</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.90</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.99</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n::: \n\n::: {.column width=\"60%\"}\n-   $\\widehat\\beta_3 = -0.057$\n-   The effect of having a prior fracture on the log odds of having a new fracture decreases by an estimated 0.057 for every one year increase in age (95% CI: 0.008, 0.107).\n\n    -   Aka the *log odds of a new fracture* comparing prior fracture to no prior fracture gets closer to one another as age increases\n\n-   $\\widehat\\beta_1 = 1.002$\n-   For individuals 69 years old, the estimated difference in log odds for a new fracture is 1.002 comparing individuals with a prior fracture to individuals with no prior fracture (95% CI: 0.530, 1.471).\n\n-   $\\exp(\\widehat\\beta_1) = 2.72$   \n-   For individuals 69 years old, the estimated odds of a new fracture for individuals with prior fracture is 2.72 times the estimated odds of a new fracture for individuals with no prior fracture (95% CI: 1.70, 4.35).\n:::\n:::\n\n## Poll Everywhere Question 5\n\n## Plot of estimated log odds\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprior_age = expand_grid(priorfrac = c(\"No\", \"Yes\"), age_c = (55:90)-69)\nfrac_pred_log = predict(glow_m3, prior_age, se.fit = T, type=\"link\")\npred_glow2 = prior_age %>% mutate(frac_pred_log = frac_pred_log$fit, \n                                  age = age_c + mean_age)\n\nggplot(pred_glow2) + #geom_point(aes(x = age, y = frac_pred, color = priorfrac)) +\n  geom_smooth(method = \"loess\", aes(x = age, y = frac_pred_log, color = priorfrac)) +\n  theme(text = element_text(size=20), title = element_text(size=16)) +\n  labs(color = \"Prior Fracture\", x = \"Age (years)\", y = \"Log-Odds of Fracture\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](11_Interactions_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n## Poll Everywhere Question 6 (Bonus q if we're feeling it)\n\n## Plot the predicted probability of fracture\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfrac_pred = predict(glow_m3, prior_age, se.fit = T, type=\"response\")\npred_glow = prior_age %>% mutate(frac_pred = frac_pred$fit, \n                                  age = age_c + mean_age)\n\nggplot(pred_glow) + #geom_point(aes(x = age, y = frac_pred, color = priorfrac)) +\n  geom_smooth(method = \"loess\", aes(x = age, y = frac_pred, color = priorfrac)) +\n  theme(text = element_text(size=20), title = element_text(size=16)) + ylim(0,1) +\n  labs(color = \"Prior Fracture\", x = \"Age (years)\", y = \"Predicted Probability of Fracture\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](11_Interactions_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n## Odds Ratio in the Presence of Interaction (1/2)\n\n-   When interaction exists between a risk factor (F) and another variable (X), the estimate of the odds ratio for F  depends on the value of X\n\n \n\n-   When an interaction term (F*X) exists in the model\n\n    -   ${\\widehat{OR}}_F \\neq \\exp(\\widehat\\beta_F)$ in general\n\n \n\n-   Assume we want to compute the odds ratio for ($F = f_1$ and $F = f_0$, the correct model-based estimate is $$\\begin{aligned}\n{\\widehat{OR}}_F = &\\exp{\\left(\\hat{g}\\left(F=f_1,X=x\\right)-\\hat{g}\\left(F=f_0,X=x\\right)\\right)} \n\\end{aligned}$$\n\n    -   Let's work this out on the next slide!\n\n## Odds Ratio in the Presence of Interaction (2/2)\n\n-   We may write the two logits (log-odds) for given x as below:\n\n$$ \\begin{aligned} \n\\hat{g}\\left(F = f_1,X = x\\right)&={\\hat{\\beta}}_0+{\\hat{\\beta}}_1f_1+{\\hat{\\beta}}_2x+{\\hat{\\beta}}_3f_1\\cdot\\ x \\\\\n\\hat{g}\\left(F = f_0,X=x\\right)&={\\hat{\\beta}}_0+{\\hat{\\beta}}_1f_0+{\\hat{\\beta}}_2x+{\\hat{\\beta}}_3f_0\\cdot\\ x\n\\end{aligned}$$\n\n-   The difference in two logits (log-odds) is:\n\n$$ \\begin{aligned} \n\\hat{g}\\left(f_1,x\\right)-\\hat{g}\\left(f_0,x\\right) & = \\left[{\\hat{\\beta}}_0+{\\hat{\\beta}}_1f_1+{\\hat{\\beta}}_2x+{\\hat{\\beta}}_3f_1\\cdot\\ x \\right] - \\left[{\\hat{\\beta}}_0+{\\hat{\\beta}}_1f_0+{\\hat{\\beta}}_2x+{\\hat{\\beta}}_3f_0\\cdot\\ x \\right] \\\\\n\\hat{g}\\left(f_1,x\\right)-\\hat{g}\\left(f_0,x\\right) & = \\hat{\\beta}_1 f_1- \\hat{\\beta}_1f_0 + \\hat{\\beta}_3 x f_1 - \\hat\\beta_3 x f_0\\\\ \n\\hat{g}\\left(f_1,x\\right)-\\hat{g}\\left(f_0,x\\right) & = {\\hat{\\beta}}_1\\left(f_1-f_0\\right)+{\\hat{\\beta}}_3x\\left(f_1-f_0\\right)\n\\end{aligned}$$\n\n-   Therefore, \n\n$$\\widehat{OR}(F=f-1, F=f_0, X=x) = \\widehat{OR}_F = \\exp\\left[ {\\hat{\\beta}}_1\\left(f_1-f_0\\right)+{\\hat{\\beta}}_3x\\left(f_1-f_0\\right) \\right]$$\n\n## Steps to compute OR under interation\n\n-   Note: You don't need to know the math itself, but I think it's helpful to think of it this way\n\n1.    Identify two sets of values that you want to compare with only one variable changed\n\n      -   In previous slides, one set was $(F=f_1, X=x)$ and the other was $(F=f_0, X=x)$\n      \n2.    Substitute values in the fitted log-odds model\n\n      -   You should have two equations, one for each set of values\n\n3.    Take the difference of the two log-odds\n\n4.    Exponentiate the resulting difference\n\n## Example: GLOW Study\n\n1.    Identify two sets of values that you want to compare with only one variable changed \n\n      -   Set 1: $PF = 1, Age = a$\n      \n      -   Set 2: $PF = 0, Age = a$\n\n \n\n2.    Substitute values in the fitted log-odds model\n\n$$\\text{logit}\\left(\\widehat\\pi(\\mathbf{X})\\right) = \\widehat\\beta_0 + \\widehat\\beta_1\\cdot I(\\text{PF}) + \\widehat\\beta_2\\cdot Age + \\widehat\\beta_3 \\cdot I(\\text{PF}) \\cdot Age$$\n$$\\begin{aligned} \\text{logit}\\left(\\widehat\\pi(PF = 1, Age = a)\\right) =& \\widehat\\beta_0 + \\widehat\\beta_1\\cdot 1 + \\widehat\\beta_2\\cdot a + \\widehat\\beta_3 \\cdot 1\\cdot Age \\\\\n=& \\widehat\\beta_0 + \\widehat\\beta_1 + \\widehat\\beta_2\\cdot a + \\widehat\\beta_3\\cdot a\n\\end{aligned}$$\n\n$$\\begin{aligned} \\text{logit}\\left(\\widehat\\pi(PF = 0, Age = a)\\right) =& \\widehat\\beta_0 + \\widehat\\beta_1\\cdot 0 + \\widehat\\beta_2\\cdot a + \\widehat\\beta_3 \\cdot 0\\cdot Age \\\\\n=& \\widehat\\beta_0 + \\widehat\\beta_2\\cdot a\n\\end{aligned}$$\n\n## Example: GLOW Study\n\n3.    Take the difference of the two log-odds\n\n$$\\begin{aligned}\n\\left[logit\\left(\\pi\\left(PF=1,\\ Age=a\\right)\\right)\\right]- & \\left[logit\\left(\\pi\\left(PF=0,\\ Age=a\\right)\\right)\\right]\n\\\\ & =\\left[{\\hat{\\beta}}_0+{\\hat{\\beta}}_1+{\\hat{\\beta}}_2a+{\\hat{\\beta}}_3a\\right]-\\left[{\\hat{\\beta}}_0+{\\hat{\\beta}}_2a\\right]\\\\ &={\\hat{\\beta}}_1+{\\hat{\\beta}}_3a\n\\end{aligned}$$\n\n4.    Exponentiate the resulting difference  \n\n$$\\widehat{OR}\\left[\\left(PF=1,\\ Age=a\\right),\\left(PF=0,\\ Age=a\\right)\\right]=exp\\ \\left({\\hat{\\beta}}_1+{\\hat{\\beta}}_3a\\right)$$\n\n## We can put in values for age to see how the OR changes\n\n-   If we let $a = 60$, i.e., compute OR for age = 60, then $${\\widehat{OR}}_{a=60}=\\exp(1.002-0.057\\cdot(60-69))\\ =4.55$$\n\n-   If we let $a = 70$, i.e., compute OR for age = 70, then\n$${\\widehat{OR}}_{a=70}=\\exp(1.002-0.057\\cdot(70-69))\\ =2.57$$\n\n## Calculate odds ratios across values\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_age = expand_grid(priorfrac = c(\"No\", \"Yes\"), age_c = (55:90)-69)\nfrac_pred_logit = predict(glow_m3, prior_age, se.fit = T, type=\"link\")\npred_glow2 = prior_age %>% mutate(frac_pred = frac_pred_logit$fit, \n                                  age = age_c + mean_age) %>%\n\n                pivot_wider(names_from = priorfrac, values_from = frac_pred) %>%\n\n                mutate(OR_YN = exp(Yes - No))\nhead(pred_glow2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  age_c   age    No    Yes OR_YN\n  <dbl> <dbl> <dbl>  <dbl> <dbl>\n1   -14    55 -2.25 -0.446  6.08\n2   -13    56 -2.19 -0.441  5.74\n3   -12    57 -2.13 -0.436  5.42\n4   -11    58 -2.06 -0.430  5.12\n5   -10    59 -2.00 -0.425  4.83\n6    -9    60 -1.94 -0.420  4.56\n```\n:::\n:::\n\n\n\n## Plotting the odds ratio for an interaction\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(pred_glow2) +\n  geom_hline(yintercept = 1) +\n  geom_smooth(method = \"loess\", aes(x = age, y = OR_YN)) +\n  theme(text = element_text(size=20), title = element_text(size=16)) +\n  labs(x = \"Age (years)\", y = \"Estimated odds ratio\", title = \"Odds ratio of fracture outcome comparing \\n prior fracture to no prior fracture\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](11_Interactions_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n\n## How would I report these results?\n\n-   Remember our main covariate is prior fracture, so we want to focuse on how age changes the relationship between prior fracture and a new fracture!\n\n::: columns\n::: column\nFor individuals 69 years old, the estimated odds of a new fracture for individuals with prior fracture is 2.72 times the estimated odds of a new fracture for individuals with no prior fracture (95% CI: 1.70, 4.35). As seen in @fig-plots-1, the odds ratio of a new fracture when comparing prior fracture status decreases with age, indicating that the effect of prior fractures on new fractures decreases as individuals get older. In @fig-plots-2, it is evident that for both prior fracture statuses, the predict probability of a new fracture increases as age increases. However, the predicted probability of new fracture for those without a prior fracture increases at a higher rate than that of individuals with a prior fracture. Thus, the predicted probabilities of a new fracture converge at age [insert age here]. \n:::\n::: column\n\n\n::: {#fig-plots .cell layout-ncol=\"2\"}\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![Odds ratio of fracture outcome comparing prior fracture to no prior fracture](11_Interactions_files/figure-html/fig-plots-1.png){#fig-plots-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Predicted probability of fracture](11_Interactions_files/figure-html/fig-plots-2.png){#fig-plots-2 width=672}\n:::\n\nPlots of odds ratio and predicted probability from fitted interaction model\n:::\n\n\n:::\n\n:::\n\n",
    "supporting": [
      "11_Interactions_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}